### ISSUE TITLE
Duplicating the "dps" line in faucet.yaml should not cause a silent failure

### ISSUE THREAD

**Issue by bcoleman532** [faucetsdn/faucet#1034]
When adding a new switch to our faucet deployment I accidentally duplicated the dps line when pasting in config for the new switch.  The end result was the new switch I added was the sole datapath configured in faucet and everything else got dropped.

My expectation is that such an error should result in a loud warning to the user and that the configuration check would not succeed.

**Comment by anarkiwi** [comment]
There is a problem with the python yaml library that makes this a bit tricky to work around - will investigate FAUCET doing its own YAML parsing to avoid it. Unfortunately this is more than a 5 minute fix.

https://web.archive.org/web/20170712151500/pyyaml.org/ticket/128

**Comment by gizmoguy** [comment]
Looks like some have had success overriding the pyyaml constructor to account for duplicated keys:

http://www.codegist.net/snippet/python/pyyaml-duplicatespy_pypt_python

Obviously this could have side effects and I'm not sure if this works in python3, so more investigation required to ensure something like this is safe.

@anarkiwi is this a function check_faucet_config could supply more easily? I forget how much of its own parsing that script performns

**Comment by anarkiwi** [comment]
That's right, possible but will take some careful testing.

**Comment by Bairdo** [comment]
There is https://bitbucket.org/ruamel/yaml which was originally a fork of pyyaml, and is actively maintained. 
According to the docs & changelog it will throw an error on duplicate keys. http://yaml.readthedocs.io/en/latest/api.html#duplicate-keys

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/53ff3b66266f8b7ab94d28e42b5ea064ed50b402

The new config testing suite made testing this simple.
