### ISSUE TITLE
Get Switch/Datapath information via Guage

### ISSUE THREAD

**Issue by shivarammysore** [faucetsdn/faucet#1091]
Currently, Gauge does not have a way to get Switch related information.  Need a method to push the same to all the databases (prometheus, Influx, Couch, Text.JSON)
Per https://github.com/osrg/ryu/blob/master/ryu/ofproto/ofproto_v1_3_parser.py 

```
   def send_desc_stats_request(self, datapath):
            ofp_parser = datapath.ofproto_parser
            req = ofp_parser.OFPDescStatsRequest(datapath, 0)
            datapath.send_msg(req)
```

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/b8f8060134b807e9ea01d813c62e6ed38c521136

I have implemented this for Prometheus.

**Comment by shivarammysore** [comment]
Thanks.  This is very useful work.  Will default faucet.yaml and gauge.yaml files updated to include these changes?

/Shivaram
::Sent from my mobile device::

**Comment by anarkiwi** [comment]
There is no need to update, the new variable will appear when Prometheus is
used.
