### ISSUE TITLE
Config validation issue: reference nonexistent vlan

### ISSUE THREAD

**Issue by simeonmiteff** [faucetsdn/faucet#1125]
The exception when referencing a non-existent vlan in a port config does not make the error obvious:

```
	top_confs['vlans'])
  File "/usr/local/lib/python3.6/site-packages/faucet/config_parser.py", line 144, in _dp_parser_v2
	_dp_add_ports(dp, dp_conf, dp_id, vlans)
  File "/usr/local/lib/python3.6/site-packages/faucet/config_parser.py", line 123, in _dp_add_ports
	port = _dp_parse_port(dp_id, port_num, port_conf, vlans)
  File "/usr/local/lib/python3.6/site-packages/faucet/config_parser.py", line 100, in _dp_parse_port
	vlan = _get_vlan_by_identifier(dp_id, v_identifier, vlans)
  File "/usr/local/lib/python3.6/site-packages/faucet/config_parser.py", line 76, in _get_vlan_by_identifier
	vid = int(vlan_ident, 0)
TypeError: int() can't convert non-string with explicit base
```

**Comment by aappachi** [comment]
Can I take this bug?

Analysis:

For int(), if base is passed, first parameter must be string. In this case it is an int and hence this error.
Since it is a TypeError it was not captured in the except section.
        try:
          vid = int(vlan_ident, 0)
        except ValueError:
            assert False, 'VLAN VID value (%s) is invalid' % vlan_ident

**Comment by anarkiwi** [comment]
Please do - github for some reason won't let me assign you but we won't let that stop you. :)

**Comment by KitL** [comment]
One thing to watch out for: the vlan identifier may be the configured name of the vlan rather than the vid. I suspect this is code that is leftover from the old days when you would only refer to vlans in config by vid. So it would be good to double check that you handle both the case of refering to a non-existent vlan by vid and a non-existent vlan by name.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/pull/1180
