### ISSUE TITLE
Provide a CI for package builds and integration testing

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#1151]
The kind folks at Cybera have donated us some compute time on their openstack cluster to act as build hosts for FAUCET.

I propose we deploy a CI (probably gitlab CI) and use these openstack VMs to build docker containers, pypi packages, VM images and run our integration test suite regularly.

This is part of a bigger project to reduce dependence on Travis & Docker cloud due to many issues we've seen attempting to run our large test suite and build our containers.

**Comment by shivarammysore** [comment]
My suggestion would be to reduce number of times built on Travis, but keep
travis going at a smaller scale.  This will help others to continue using
Travis.  Advanced testing with Openstack infrastructure will be a welcome
addition.

**Comment by gizmoguy** [comment]
@shivarammysore Note: this only affects integration tests not unit tests which will continue on Travis.

**Comment by anarkiwi** [comment]
Trying this: https://blog.hypriot.com/post/setup-simple-ci-pipeline-for-arm-images/

**Comment by gizmoguy** [comment]
Implemented in #1774
