### ISSUE TITLE
faucet-pi container should supply tagged versions

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#1152]
At the moment the faucet/faucet-pi container only provides the "latest" tag which points to the current git master version of FAUCET.

Ideally we'd provide a docker tag of each stable release of FAUCET to make upgrades/downgrades easier.

This can probably be part of ongoing work on #1151

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/blob/master/build-faucet-pi-on-pi.sh

The Pi build farm now does this (catching up with the backlog now).
