### ISSUE TITLE
Learned MAC not exported with Prometheus.

### ISSUE THREAD

**Issue by Bairdo** [faucetsdn/faucet#1183]
Running faucet 1.6.8 and [gasket](https://github.com/bairdo/gasket)'s tests (the authentication app), I'm running into an issue where MAC addresses aren't being exported via Prometheus.

In the logs below the prometheus_output.txt is dumped after line 22 of auth_app.log (time 23:43:29-702)

[auth_app.log](https://github.com/faucetsdn/faucet/files/1455831/auth_app.log)
[faucet.log](https://github.com/faucetsdn/faucet/files/1455823/faucet.log)
[prometheus_output.txt](https://github.com/faucetsdn/faucet/files/1455824/prometheus_output.txt)

**Comment by anarkiwi** [comment]
https://github.com/anarkiwi/faucet/commit/c882e9df7d5f137c5f91855139c5d9dd24e64b03 et al.
