### ISSUE TITLE
max_len in OUTPUT action to CONTROLLER?

### ISSUE THREAD

**Issue by byllyfish** [faucetsdn/faucet#1197]
I'm noticing a difference in behavior between OVS 2.7 and OVS 2.5. It appears that OVS 2.7 does **not** honor the max_len in the OUTPUT action that sends a PacketIn message, but OVS 2.5 does.

This has implications when pinging a controller vip (or running the mininet tests), because of the new code that checks for a complete packet:

```python
    def packet_complete(self):
        """True if we have the complete packet."""
        return len(self.data) == self.orig_len
```

When running against OVS 2.5, I can't ping a controller vip because len(self.data) is 96, but self.orig_len is 102.  With OVS 2.7, there's no truncation and both values are 102.

My question is whether anyone else sees this, and if so, which behavior is correct. It seems like the OF agent should honor the max_len setting when sending to a controller. 

Faucet may need to increase its max_len values for the vip table which are currently set to 96 -- these are too small. For default pings to work, max_len needs to be at least 102 for ipv4 and 122 for ipv6.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/c5ae9a735ca4a30cafa682c280ab380ff8cbc0a5
