### ISSUE TITLE
Support output only ports

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#1232]
When mirroring it is handy to have a port configured with no VLAN on it. Faucet currently explicitly requires a VLAN on every port.

As a workaround, currently we can create a blank vlan with `max_hosts` set to 0 on the VLAN and apply this to the mirror port.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/036eba5e5149aaf4f1effebac2a6d789b6803ef7
