### ISSUE TITLE
ValveFloodStackManager incorrectly comparing path length.

### ISSUE THREAD

**Issue by Dualis** [faucetsdn/faucet#1308]
ValveFloodStackManager.__init__ (valve_flood.py 198:216) compares with '>' / '<' what it calls distances, but are in fact lists.
Can cause flooding to fail, depending on the topology.
Fix should be adding a couple of len() calls.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/f632cc9867bb3ac3281bc0e73153cb2907adbfd5

Thanks! Always good to having stacking users! If you have time let us know what you use it for.
