### ISSUE TITLE
FAUCET event notification

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#1312]
@cglewis @corelight - FYI.

FAUCET knows about topology and network state changes - e.g. a host was learned, a port went up or down. We want a way to send these events to an external system, but we also can't have FAUCET block on sending the event (since that would affect the network).

We propose to provide an adaptor process that streams JSON'd events (first to RabbitMQ, later to the new Bro Broker). Current proposal is FAUCET will stream the events over a Unix domain socket to the adaptor process (fire/forget). We don't guarantee all events (FAUCET may be restarted, etc) will be streamed. Ryu hijacks thread/scheduling/sockets which FAUCET-side must be careful of.

This feature would not replace Prometheus in any way (the more general purpose NMS interface for FAUCET).

In the future an gNMI adaptor would be provided also.

Notes from Bro follow on the Broker implementation.
==

to use the new Broker version, there are branches called
topic/actor-system in both the main Bro repository
(git://git.bro.org/bro) and the Broker repository
(git://git.bro.org/broker); if you start with the Bro branch, it'll
check out the Broker submodule in the correct version.

Compiling Broker requires CAF 0.15.x from
https://github.com/actor-framework/actor-framework (0.15.4 minimum)

The Broker branch comes with updated documentation describing the new
APIs for C++ and Python: "make doc", then look into
build/doc/html/index.html (building the docs requires Sphinx, rst2pdf,
and "pip install sphinx_bootstrap_theme"). Look at "2.3. Exchanging
Bro Events" in particular. Broker's unit tests in tests/ demonstrate
further how the API works.

On the Bro side, you find the Broker API in
scripts/base/frameworks/broker/main.bro. Tests showing how to use it
are in testing/btest/broker/. Broker's C++ API maps pretty much
directly over to Bro. We are working on some more higher-level
communication patterns, too, but that's probably not that important
for you if it's only about sending events into Bro.

**Comment by cglewis** [comment]
Perfect, sounds like a good approach to me. I think fire/forget as you mention is a good compromise here.  Happy to test RMQ on my end when the time comes.

**Comment by shivarammysore** [comment]
Josh,
Well articulated.

Instead of sending events via Unix sockets - which means another port open
(need to guard it from security perspective), how about sending event
related data to Prometheus itself.  We can configure Alert Manager in
Prometheus to consume them appropriately.  It is my opinion that sending
event information itself will not be sufficient - there will be a followup
ask of other items.  If we feed Prometheus will all the data, then app
developers such as Bro would be able to consume it appropriately.  Another
advantage of Prometheus Alter Manager is its integration with other
notification partners such as email, pagers, etc

[1] https://prometheus.io/docs/introduction/overview/

**Comment by anarkiwi** [comment]
There are a few things here. Opening a Unix socket is entirely local to the
system and we're using file system/Unix permissions, so securing it is much
easier than with a TCP port. It's write only for FAUCET, so there's no
authentication or need for FAUCET to process requests which could block it.
On the Prometheus side, firstly, Prometheus currently doesn't have a
streaming interface, so we have to wait for events to appear in when they
are polled. Secondly, Prometheus doesn't really support constantly changing
string based data (it's built for a relatively smaller number of timeseries
which are just all floats - we can put things in labels, but Prometheus
prefers you don't - see https://prometheus.io/docs/practices/naming/ - "Do
not use labels to store dimensions with high cardinality ... or other
unbounded sets of values" - we will be storing network event data which
will have too many dimensions). We make sure we use values that don't
change that often or have limited dimensions (that's why the MAC table is
encoded the way it is).

**Comment by shivarammysore** [comment]
Thanks for the clarification Josh.

Agree with you that "pull" model does not work for events.
yes - agree with you that time series model of Prometheus does not help
here.

In terms of port, I think if we run Faucet on a docker container, there
will be one more port that needs to be exposed which other apps interested
in events can consume.  Another possibility is that "event queue" may be
hooked to that port and interested apps can subscribe to that "event queue"

**Comment by anarkiwi** [comment]
The current proposal is that a helper process will push the events it
receives from FAUCET to something like RabbitMQ. That means there's no need
for another process to interact with FAUCET's container at all. It can
simply simply subscribe to the message bus.

**Comment by anarkiwi** [comment]
@cglewis:

{"version": 1, "dp_name": "faucet-1", "DP_CHANGE": {"reason": "cold_start"}, "time": 1512437251.8729575, "dp_id": 320994128}
{"version": 1, "dp_name": "faucet-1", "L2_LEARN": {"l3_src_ip": null, "vid": 100, "eth_type": 34525, "port_no": 3, "eth_src": "26:9d:9f:37:39:bd"}, "time": 1512437252.0014641, "dp_id": 320994128}
{"version": 1, "dp_name": "faucet-1", "L2_LEARN": {"l3_src_ip": null, "vid": 100, "eth_type": 34525, "port_no": 1, "eth_src": "9e:f4:6b:cb:6d:a5"}, "time": 1512437252.0041497, "dp_id": 320994128}
{"version": 1, "dp_name": "faucet-1", "L2_LEARN": {"l3_src_ip": "fe80::14e2:27ff:fe34:63ab", "vid": 100, "eth_type": 34525, "port_no": 4, "eth_src": "16:e2:27:34:63:ab"}, "time": 1512437255.4592326, "dp_id": 320994128}
{"version": 1, "dp_name": "faucet-1", "L2_LEARN": {"l3_src_ip": "fe80::5c2c:8cff:fe35:6a2d", "vid": 100, "eth_type": 34525, "port_no": 2, "eth_src": "5e:2c:8c:35:6a:2d"}, "time": 1512437255.715223, "dp_id": 320994128}

This is the prototype installation - FAUCET ships events as json blobs, with version, dp_id and dp_name and the event over a Unix domain socket, if you set FAUCET_EVENT_SOCK. 

Things are fairly schema-less, the point here is to check that's broadly what you're after - then it's simple to annotate other significant events. 

The expectation is that the consumer should write their own adaptor for now (eg. netcat -U to flat file ;) or perhaps to RabbitMQ. 

Comments welcome,

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/0f76717923020d442b124e756f202ac2f6c360f3 in master.

**Comment by cglewis** [comment]
@anarkiwi thanks for this. I got it minimally working, will do some more testing to make it can do the things I'm thinking of using it for.

I also ran into this crash when connecting it with `netcat -U`

```
faucet_1      | hub: uncaught exception: Traceback (most recent call last):
faucet_1      |   File "/usr/lib/python3.6/site-packages/ryu/lib/hub.py", line 59, in _launch
faucet_1      |     return func(*args, **kwargs)
faucet_1      |   File "/usr/lib/python3.6/site-packages/faucet/faucet_experimental_event.py", line 57, in _loop
faucet_1      |     event = self.event_q.get_nowait()
faucet_1      |   File "/usr/lib/python3.6/site-packages/eventlet/queue.py", line 326, in get_nowait
faucet_1      |     return self.get(False)
faucet_1      |   File "/usr/lib/python3.6/site-packages/eventlet/queue.py", line 318, in get
faucet_1      |     raise Empty
faucet_1      | queue.Empty
```

**Comment by cglewis** [comment]
For consumers writing their own adapters, would it be amenable to have an `adapters/vendor` directory in FAUCET (kind of like the `docs/vendor` directory) that could have community submitted adapters that would still be available from this repository?

Assuming that would be something that is feasible, I could then imagine having perhaps something in the `faucet.yaml` definition that would let someone specify adapter(s) they want to enable and have running - default being no adapters.

**Comment by anarkiwi** [comment]
Just fixed that - thanks. Should get rapidly beyond prototype quality (there will be more test today that events arrive etc as expected).

Yes contributed adaptors would be great - I would imagine them though in their own container independent from FAUCET but referencing the same UDS (per the docker compose PR you just sent). This among other things allows the adaptor to be managed/upgraded/secured separately from FAUCET.

**Comment by cglewis** [comment]
Sounds good. I'll try and cook something up that we can throw stones at ;)

**Comment by anarkiwi** [comment]
OK, tests are now slightly less tragic. There's an event_id which is also logged in Prometheus, so an adaptor can check for queue overflows or controller restarts and assert its own signal that events are being lost.

**Comment by byllyfish** [comment]
The current implementation seems to work well when a single client is connected. 

The queue implementation causes the first client that connects to get the first 120 events that have occurred since Faucet started. If more than 120 events have occurred, you only get the first 120 (not the recent 120.) Is this special case of publishing the event backlog for the first client part of the desired behavior? It looks like the backlog might be published whenever the client count goes from 0 to 1.

Once a second client connects, events are only published to one of the connections (random luck of the thread?) Is multiple client support desired? I don't know how the ryu StreamServer works, so this might be tricky.

**Comment by anarkiwi** [comment]
That's right - only one client at a time is intended (I'll add some
enforcement of that). The idea is the client does any copying required (or
pushing to a message bus).

**Comment by anarkiwi** [comment]
OK, this is now fixed - multiple clients explicitly rejected and we keep
just the most recent N events.

**Comment by cglewis** [comment]
FWIW, this has been working quite well for me.

**Comment by anarkiwi** [comment]
That makes me so happy! Great. I will close this issue and open another for
the more generic feature (post processing ACL).
