### ISSUE TITLE
FAUCET cold starting DP when no config changes

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#1317]
https://gist.github.com/gizmoguy/bc9986711781f89accb4712034542ee3

Nov 30 15:47:18 faucet INFO     request to reload configuration
Nov 30 15:47:18 faucet INFO     configuration /etc/ryu/faucet/faucet.yaml changed
Nov 30 15:47:19 faucet.valve INFO     DPID 70 (0x46) reload configuration
Nov 30 15:47:19 faucet.valve INFO     DPID 70 (0x46) no VLAN config changes
Nov 30 15:47:19 faucet.valve INFO     DPID 70 (0x46) no port config changes
Nov 30 15:47:19 faucet.valve INFO     DPID 70 (0x46) L2 learned f0:1c:2d:7f:a6:f7 (L2 type 0x0800, L3 src 41.45.136.77) on Port 7 on VLAN 2406 (2 hosts total)
Nov 30 15:47:19 faucet.valve INFO     DPID 70 (0x46) L2 learned f0:1c:2d:7f:a6:f7 (L2 type 0x0800, L3 src 191.101.167.235) on Port 7 on VLAN 2406 (2 hosts total)
Nov 30 15:47:19 faucet.valve INFO     DPID 70 (0x46) L2 learned f0:1c:2d:7f:a6:f7 (L2 type 0x0800, L3 src 138.197.41.130) on Port 7 on VLAN 2406 (2 hosts total)
Nov 30 15:47:21 faucet INFO     Add new datapath DPID 70 (0x46)
Nov 30 15:47:22 faucet INFO     BGP add ::/0 nexthop 2404:138:39:120::1
Nov 30 15:47:22 faucet INFO     DPID 70 (0x46) connected
Nov 30 15:47:22 faucet.valve INFO     DPID 70 (0x46) Cold start configuring DP

**Comment by gizmoguy** [comment]
Here's the full configuration I was using with faucet at the time:

https://github.com/wandsdn/redcables-ansible/blob/bcd6c74068dd74cbed8a27f4520084efabcd3b6a/files/faucet/faucet.yaml

**Comment by anarkiwi** [comment]
I found the code path where if the config file changes (eg whitespace, comments) but the parsed output effectively doesn't change, we will unnecessarily cold start per this bug. Improving the logs now and will extend the tests appropriately.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/bd399015591de31f08f76a2310dd208e4706d744
