### ISSUE TITLE
vlan_vid output setting gets overwritten by default flow

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#1325]
The config below generates the following output where the vlan is set by the output rule, but then is immediately overwritten by the native_vlan setting.

 table=0, priority=9097,udp,in_port=1,tp_dst=57612 actions=push_vlan:0x8100,set_field:4296->vlan_vid,goto_table:1
 table=1, priority=9000,in_port=1,vlan_tci=0x0000/0x1fff actions=push_vlan:0x8100,set_field:4196->vlan_vid,goto_table:3

dps:
    switch-1:
        dp_id: 0x1
        timeout: 3600
        arp_neighbor_timeout: 3600
        interfaces:
            1:
                native_vlan: 100
                acl_in: bacnet
            2:
                native_vlan: 100
                acl_in: bacnet
            3:
                native_vlan: 100
            4:
                native_vlan: 200
            5:
                native_vlan: 200
            6:
                native_vlan: 200
vlans:
    100:
    200:
      
acls:
  bacnet:
    - rule:
        dl_type: 0x800
        nw_proto: 17
        tp_dst: 57612
        actions:
          output:
            vlan_vid: 200
          allow: 1

**Comment by anarkiwi** [comment]
We can add a feature that lets an ACL bypass the input port's VLAN checks - I'll add that.

**Comment by anarkiwi** [comment]
See https://github.com/faucetsdn/faucet/issues/1552.
