### ISSUE TITLE
Sending sighup to Faucet does not kill it.

### ISSUE THREAD

**Issue by Bairdo** [faucetsdn/faucet#1363]
I believe this is caused by the threads started at
https://github.com/faucetsdn/faucet/blob/master/faucet/faucet.py#L146 
being waited on to finish (with a joinall())

They can be killed with
```python
for t in self.threads:
    t.kill()
```

```
root@controller4 ~/gasket # docker exec -ti youthful_allen ps ax
PID   USER     TIME   COMMAND
    1 root       0:01 {ryu-manager} /usr/bin/python3.6 /usr/bin/ryu-manager fau
   15 root       0:00 ps ax
root@controller4 ~/gasket # docker kill -s int
gasket_freeradius_1  gasket_hostapd_1     youthful_allen
root@controller4 ~/gasket # docker kill -s int youthful_allen
youthful_allen
root@controller4 ~/gasket # docker exec -ti youthful_allen ps ax
PID   USER     TIME   COMMAND
    1 root       0:02 {ryu-manager} /usr/bin/python3.6 /usr/bin/ryu-manager fau
   21 root       0:00 ps ax

```

**Comment by Bairdo** [comment]
Possible fix:
https://github.com/Bairdo/faucet/tree/kill

**Comment by gizmoguy** [comment]
Possibly a typo in the title of your issue? Did you mean SIGINT?

**Comment by anarkiwi** [comment]
SIGINT's used for interrupting the CLI (we call self.close() there, so you have to another ^C to make it stop- this enables us to support cProfile).

SIGTERM works fine to stop Faucet.
