### ISSUE TITLE
dependencies for pip install missing

### ISSUE THREAD

**Issue by cglewis** [faucetsdn/faucet#1448]
not sure if this should just be updated in the documentation, or included as install script via `setup.py`, but noticed when trying to do `pip3 install faucet` the following dependencies were required that were missing (from Ubuntu 16.04.3 on ARM):

```
apt-get install python3-dev
pip3 install setuptools
pip3 install wheel
```

**Comment by anarkiwi** [comment]
Fixed in https://github.com/faucetsdn/faucet/commit/9426dba6fba005a669ac01966dbdf4877b036a76
