### ISSUE TITLE
When configuring DP on cold start, ports are logged as up which aren't up?

### ISSUE THREAD

**Issue by byllyfish** [faucetsdn/faucet#1465]
Here's a snippet from the log.  In this scenario, port 1 is down but it's logged as "up".

This could be just a logging issue. Port 1 can be proactively configured even though it is down.

```
Jan 07 16:34:50 faucet.valve INFO     DPID 1 (0x1) Cold start configuring DP
Jan 07 16:34:50 faucet.valve INFO     DPID 1 (0x1) Configuring VLAN office vid:100 ports:Port 5,Port 1,Port 2,Port 4
Jan 07 16:34:50 faucet.valve INFO     DPID 1 (0x1) Configuring VLAN guest vid:900 ports:Port 3
Jan 07 16:34:50 faucet.valve INFO     DPID 1 (0x1) Port 1 up, configuring
Jan 07 16:34:50 faucet.valve INFO     DPID 1 (0x1) Port 2 up, configuring
Jan 07 16:34:50 faucet.valve INFO     DPID 1 (0x1) Port 3 up, configuring
Jan 07 16:34:50 faucet.valve INFO     DPID 1 (0x1) Port 4 up, configuring
Jan 07 16:34:50 faucet.valve INFO     DPID 1 (0x1) Port 5 up, configuring
```

**Comment by anarkiwi** [comment]
This is the initial provision of each port on a cold start, so we know that the dataplane is in a consistent state no matter what the actual state of each port. We can change the log message to say provisioning rather than just "up" which as you say implies a state.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/c29059bd09eb76d37edd5b19a614e62111c9938f

Now clarifies the log message.
