### ISSUE TITLE
enable rule labeling with set_field or equivalent

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#1474]
Would be useful for debugging rule flows to be able to label table-0 rules with a ct_label rule (or equivalent).

An alternative would be something like adding a way to add a mod_dl_dst field *after* the normal output/goto instructions, so that the rule itself is marked/differentiated, but the mod_* has no effect itself.

The use case here is to be able to tag a rule with a unique ID so that it's easy to back-trace from a OF rule to the corresponding faucet rule that generated it.  Right now, in a system with 1000's of rules it's cumbersome to figure out which faucet rule generated which OF rule (although possible if they're unique).

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/fd5bd36c34577badf71553317768d91712e91022

Does this (you can set any field OF lets you set).
