### ISSUE TITLE
enable mirroring/output/counting of dropped packets

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#1475]
currently packets that are incoming on a mirrored port are dropped by the default priority 0 rule.  For system debugging, it would be useful to be able to know directly what's happening, rather than indirectly. Currently, if I have 47 input rules and one mirror port, I only know something coming in on the mirror port b/c it's not listed as one of the other 47. If I had two mirrored ports then this becomes ambiguous. One solution would be to create an explicit "drop" rule for a mirrored port, so that the ACL counter would specifically show which port dropped incoming packets were coming on.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/issues/1232
