### ISSUE TITLE
mirroring doesn't work with output tag

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#1482]
Trying to use a mirror: tag with an output: tag generates an OF rule that's rejected -- see the log below. Note there are two OFPInstructionActions() entries, which causes the error.

Jan 10 09:32:02 /var/log/ryu/faucet/dp-SW0B_of.log DEBUG    966/2023 DPID 246406200719977 (0xe01aea107a69) version=None,msg_type=None,msg_len=None,xid=None,OFPFlowMod(buffer_id=4294967295,command=0,cookie=1744,cookie_mask=0,flags=0,hard_timeout=0,idle_timeout=0,instructions=[OFPInstructionActions(actions=[OFPActionOutput(len=16,max_len=0,port=47,type=0)],type=4), OFPInstructionActions(actions=[OFPActionPushVlan(ethertype=33024,len=8,type=17), OFPActionSetField(vlan_vid=4219)],type=4), OFPInstructionGotoTable(len=8,table_id=1,type=1)],match=OFPMatch(oxm_fields={'in_port': 40, 'eth_src': 'a0:48:1c:94:69:fb', 'eth_type': 2048, 'ipv4_src': '172.28.64.57'}),out_group=0,out_port=0,priority=9037,table_id=0)

generated by:

  - rule:
      cookie: 1744
      dl_type: 0x0800
      dl_src: a0:48:1c:94:69:fb
      nw_src: 172.28.64.57
      actions:
        allow: 1
        mirror: 47
        output:
          vlan_vid: 123

**Comment by anarkiwi** [comment]
Can you include the full OFError? 

Also - what is the intent of the ACL?

mirror: 47 copies the packet as-is to port 47
allow: 1 proceeds with processing.

Are you intending that after mirroring, you want the packet switched into tagged_vlan 123?

Or something else?

**Comment by grafnu** [comment]
Not sure exactly which error is the full one, but this is the other
information I'm seeing in various logs.

Jan 11 12:04:26 faucet ERROR    DPID 246406200719977 (0xe01aea107a69)
OFError
version=0x4,msg_type=0x1,msg_len=0x50,xid=0xdd4d85a1,OFPErrorMsg(code=None,data=bytearray(b'\x04\x0e\x00\x98\xddM\x85\xa1\x00\x00\x00\x00Z\xdc\x15\xc0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00#M\xff\xff\xff\xff\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00$\x80\x00\x00\x04\x00\x00\x00(\x80\x00\x08\x06'),exp_type=2600,experimenter=1330529792,type=65535)

2018-01-11T12:07:14.295Z|43949|connmgr|INFO|br0<->tcp:127.0.0.1:6653:
sending OFPBIC_DUP_INST error reply to OFPT_FLOW_MOD message

Without mirroring, the result is:

 cookie=0x4d2, duration=78.061s, table=0, n_packets=0, n_bytes=0,
idle_age=78,
priority=9037,ip,in_port=40,dl_src=a0:48:1c:94:69:fb,nw_src=172.28.64.57
actions=mod_vlan_vid:200,resubmit(,1)

Which is WAI. With mirroring, I would expect the "output:47" action to be
inserted before the mod_vlan_vid clause:

 cookie=0x4d2, duration=78.061s, table=0, n_packets=0, n_bytes=0,
idle_age=78,
priority=9037,ip,in_port=40,dl_src=a0:48:1c:94:69:fb,nw_src=172.28.64.57
actions=output:47,mod_vlan_vid:200,resubmit(,1)

So yes, after mirroring I would like the packet switched onto tagged_vlan
123. The use-case is to essentially create an "internal only" vlan that's
specified by matching ACL rules. This vlan then would behave as per normal
through the faucet vlan processing logic, and then spit out appropriately.
In conjunction with the other issue I filed, it would be nice to then strip
off the vlan tag on output (so the process is entirely internal to OF), but
this is not strictly necessary (I think).

**Comment by anarkiwi** [comment]
Should be fixed by this.

https://github.com/faucetsdn/faucet/commit/3981ac2077be2679cd3f9fba07c2144da62277da
