### ISSUE TITLE
add comment field to rules section

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#1489]
It would be useful for debugging automatically generated configs to have a "comment" (or "description") field in the rule designation field. This is functionally similar to the OF "cookie" field, in that it allows for back-tracing from the target set to the source (for OF this would be from an OF rule to the faucet rule, so and the rule comment would be for the faucet rule up to the generating source, whatever that may be).

E.g., something like 

  - rule:
      comment: dstGroup FCU rule Headend Bacnet to FCU-LG-SW-07_340020_ from 963_Server_PC
      cookie: 1688
      dl_type: 0x0800
      dl_src: a0:48:1c:94:69:fb
      dl_dst: 00:40:AE:03:3D:14
      nw_proto: 17
      nw_src: 172.28.64.57
      nw_dst: 172.28.68.59
      udp_src: 47808
      udp_dst: 47808
      actions:
        allow: 1

(actual comments prefixed by a # are allowed in YAML files, but they can't easily be programatically generated because they aren't part of the internalized data model.)

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/dd8913b9a9fc17e3919e7f73c2faef3a5e4a5460

Added description field to ACL rules.
