### ISSUE TITLE
VIP table flow for IPv6 EchoRequests truncates them to 96Bytes

### ISSUE THREAD

**Issue by trentindav** [faucetsdn/faucet#1490]
While running regression tests on NoviFlow NS2128 I noticed that the test `FaucetSingleUntaggedIPv6ControlPlaneTest` is failing because the controller is not replying to ICMPv6 EchoRequest messages. The cause for this is that the packet_in which includes the EchoRequest message is incomplete: only 96Bytes of the original packet are included in it while the total length was 122Bytes. Increasing the max_len of this flow from 96B to 128B (like the other flows with output to controller action) would solve this problem.

OpenVSwitch seems to be ignoring this max_len value, and it always sends the entire echo request packet to the controller, and this is why the regression tests are passing when not run against a hardware switch.

**Comment by anarkiwi** [comment]
The test succeeds for hardware because ping6 doesn't consider a truncated payload, a failure.

Nonetheless as you say it should not truncate the minimum. Thanks for the fix!
