### ISSUE TITLE
interfaces does not properly override interface_ranges

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#1533]
See the attached config file. I would expect it to generate an error on interface 15 since it is configured without a native_vlan. What I think is happening is the vlan from the interface_ranges is being used instead. (But, according to chat, it should *completely* replace the interface definition.) At the very least the documentation should be updated to clarify behavior. Note that removing the vlan declaration from interface 10 achieves the desired/expected outcome (of an error).

[faucet.yaml.txt](https://github.com/faucetsdn/faucet/files/1644780/faucet.yaml.txt)

**Comment by trungdtbk** [comment]
It's incremental. Config parameters in individual interfaces have higher priority and override interface_ranges config.

**Comment by grafnu** [comment]
I assume, though, that it's not recursive. E.g., a new tagged_vlan section would completely overwrite a interface_ranges tagged_vlans section, not add to the list?  Might be worthwhile to clarify the configuration.rst section (it just says "This can be overwritten by configuring those interfaces directly." which is ambiguous in this situation).

**Comment by anarkiwi** [comment]
I propose to change the docs to say, per trungdtbk's implementation:

1. A more specific interface will inherit from the range, and override/add any attributes.
2. Attributes will not be merged (you will be the range's tagged_vlans, or the overridden tagged_vlans, but you will not get the addition of range + specific).

What do you think?

**Comment by grafnu** [comment]
Sounds about right to me!

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/710ee7463c16fbc67085637d379e03d193328279
