### ISSUE TITLE
stacked ports do not broadcast locally

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#1535]
See attached config. The expected behavior is that a broadcast on an in-port of a secondary (not-prority) switch is locally broadcast to all other interfaces. This does not seem to be the case when stacking is enabled. When stacking is removed from the config then it's WAI.  (bridge br0 is mapped to SWSEC0B)

[faucet.yaml.txt](https://github.com/faucetsdn/faucet/files/1644814/faucet.yaml.txt)

$ sudo ovs-appctl ofproto/trace br0 udp,in_port=15,dl_src=00:40:ae:03:3e:fa,dl_dst=ff:ff:ff:ff:ff:ff,nw_src=172.28.64.32,nw_dst=172.28.71.255,udp_src=47808,udp_dst=47808 -generate
Flow: udp,in_port=15,vlan_tci=0x0000,dl_src=00:40:ae:03:3e:fa,dl_dst=ff:ff:ff:ff:ff:ff,nw_src=172.28.64.32,nw_dst=172.28.71.255,nw_tos=0,nw_ecn=0,nw_ttl=0,tp_src=47808,tp_dst=47808

bridge("br0")
-------------
 0. ip,in_port=15, priority 9094, cookie 0x3ed
    goto_table:1
 1. in_port=15,vlan_tci=0x0000/0x1fff, priority 9000, cookie 0x5adc15c0
    push_vlan:0x8100
    set_field:4196->vlan_vid
    goto_table:3
 3. in_port=15,dl_vlan=100,dl_src=00:40:ae:03:3e:fa, priority 9098, cookie 0x5adc15c0
    goto_table:7
 7. priority 9000, cookie 0x5adc15c0
    goto_table:8
 8. in_port=15,dl_vlan=100,dl_dst=ff:ff:ff:ff:ff:ff, priority 9008, cookie 0x5adc15c0
    output:49
     >> Nonexistent output port

Final flow: udp,in_port=15,dl_vlan=100,dl_vlan_pcp=0,vlan_tci1=0x0000,dl_src=00:40:ae:03:3e:fa,dl_dst=ff:ff:ff:ff:ff:ff,nw_src=172.28.64.32,nw_dst=172.28.71.255,nw_tos=0,nw_ecn=0,nw_ttl=0,tp_src=47808,tp_dst=47808
Megaflow: recirc_id=0,eth,udp,in_port=15,vlan_tci=0x0000/0x1fff,dl_src=00:40:ae:03:3e:fa,dl_dst=ff:ff:ff:ff:ff:ff,nw_src=128.0.0.0/1,nw_dst=172.28.71.255,nw_frag=no,tp_src=0x8000/0x8000
Datapath actions: drop

**Comment by anarkiwi** [comment]
A quick test shows that the expected flows are present on non-root switches.

Can we see the full flow tables please?

**Comment by anarkiwi** [comment]
I apologize, I wrongly described my own implementation.

We flood towards root (non-root switches do not flood locally), so the flood goes up and comes back down again.

See comments in _build_flood_rule_actions(), https://github.com/faucetsdn/faucet/blob/master/faucet/valve_flood.py.

We can look at an alternative if it's a problem.
