### ISSUE TITLE
interface-based mirroring can erroneously duplicate broadcast packets

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#1537]
Trying to use interface mirroring completely breaks things. See attached config 
[faucet.yaml.txt](https://github.com/faucetsdn/faucet/files/1644881/faucet.yaml.txt) -- br0 maps to SWSEC0B, trace below. Note that tyring to use in_port=11 WAI (output on port 49), but doesn't do any mirroring.

$ sudo ovs-appctl ofproto/trace br0 udp,in_port=10,dl_src=00:40:ae:03:3e:fa,dl_dst=ff:ff:ff:ff:ff:ff,nw_src=172.28.64.32,nw_dst=172.28.71.255,udp_src=47808,udp_dst=47808 -generate
Flow: udp,in_port=10,vlan_tci=0x0000,dl_src=00:40:ae:03:3e:fa,dl_dst=ff:ff:ff:ff:ff:ff,nw_src=172.28.64.32,nw_dst=172.28.71.255,nw_tos=0,nw_ecn=0,nw_ttl=0,tp_src=47808,tp_dst=47808

bridge("br0")
-------------
 0. priority 0, cookie 0x5adc15c0
    drop

Final flow: unchanged
Megaflow: recirc_id=0,eth,udp,in_port=10,dl_src=00:40:ae:03:3e:fa,dl_dst=ff:ff:ff:ff:ff:ff,nw_src=128.0.0.0/1,nw_dst=172.28.71.255,nw_frag=no
Datapath actions: drop

**Comment by grafnu** [comment]
Melodramatic, maybe?

[br0-flows.txt](https://github.com/faucetsdn/faucet/files/1645020/br0-flows.txt)

Sorry it's quite large -- but -- there is no entry for in_port=10 in table=0 -- which is what causes the problem!

**Comment by anarkiwi** [comment]
Thanks, I'll take a look. Can you try this also please on a non-stack DP?

**Comment by grafnu** [comment]
Can confirm -- behavior is the same with a non-stack DP.

**Comment by anarkiwi** [comment]
Very strange, will look for differences with the unit tested config.

**Comment by anarkiwi** [comment]
Oh, you're looking for mirror in table 0. It won't be in table 0, that's the port ACL table. The mirror functionality works differently, internally, if you specify it on an interface. 

From your flow dump, as you can see in table 8, floods from interface 10 will be mirrored to 47.

However, look at table 1 (VLAN table). in_port=10 is set to drop! It's behaving like this is a mirror destination port. But this doesn't match the config. This makes me thing the config and the flow dump are out of sync here.

Let's go back to basics with 1 DP, configured to do interface mirroring the same way the unit tests do it, removing any ACLs or other things that could be intefering.

 cookie=0x5adc15c0, duration=163.252s, table=1, n_packets=0, n_bytes=0, idle_age=163, priority=9099,in_port=10 actions=drop
 cookie=0x5adc15c0, duration=163.265s, table=8, n_packets=0, n_bytes=0, idle_age=163, priority=9008,in_port=10,dl_vlan=100,dl_dst=ff:ff:ff:ff:ff:ff actions=output:49
 cookie=0x5adc15c0, duration=163.260s, table=8, n_packets=0, n_bytes=0, idle_age=163, priority=9009,in_port=10,dl_vlan=100,dl_dst=ff:ff:ff:ff:ff:ff actions=output:47,output:49
 cookie=0x5adc15c0, duration=163.270s, table=8, n_packets=0, n_bytes=0, idle_age=163, priority=9006,in_port=10,dl_vlan=100,dl_dst=33:33:00:00:00:00/ff:ff:00:00:00:00 actions=output:49
 cookie=0x5adc15c0, duration=163.265s, table=8, n_packets=0, n_bytes=0, idle_age=163, priority=9007,in_port=10,dl_vlan=100,dl_dst=33:33:00:00:00:00/ff:ff:00:00:00:00 actions=output:47,output:49
 cookie=0x5adc15c0, duration=163.282s, table=8, n_packets=0, n_bytes=0, idle_age=163, priority=9002,in_port=10,dl_vlan=100,dl_dst=01:80:c2:00:00:00/ff:ff:ff:00:00:00 actions=output:49
 cookie=0x5adc15c0, duration=163.276s, table=8, n_packets=0, n_bytes=0, idle_age=163, priority=9003,in_port=10,dl_vlan=100,dl_dst=01:80:c2:00:00:00/ff:ff:ff:00:00:00 actions=output:47,output:49
 cookie=0x5adc15c0, duration=163.276s, table=8, n_packets=0, n_bytes=0, idle_age=163, priority=9004,in_port=10,dl_vlan=100,dl_dst=01:00:5e:00:00:00/ff:ff:ff:00:00:00 actions=output:49
 cookie=0x5adc15c0, duration=163.270s, table=8, n_packets=0, n_bytes=0, idle_age=163, priority=9005,in_port=10,dl_vlan=100,dl_dst=01:00:5e:00:00:00/ff:ff:ff:00:00:00 actions=output:47,output:49
 cookie=0x5adc15c0, duration=163.286s, table=8, n_packets=0, n_bytes=0, idle_age=163, priority=9000,in_port=10,dl_vlan=100 actions=output:49
 cookie=0x5adc15c0, duration=163.282s, table=8, n_packets=0, n_bytes=0, idle_age=163, priority=9001,in_port=10,dl_vlan=100 actions=output:47,output:49

**Comment by grafnu** [comment]
I'll put together a simplified config. But.... the problem is with table=0
-- the packet is dropped immediately and never makes it to table=1, or 8...
(maybe multiple problems).

**Comment by anarkiwi** [comment]
Table 0 is the ACL table. If the packet doesn't survive table 0 then you
must have an ACL that drops.

**Comment by grafnu** [comment]
Ports 10 and 11 should behave the same, except that port 10 should mirror,
correct?

dps:
  SWSEC0B:
    dp_id: 0xe01aea107a69
    interfaces:
      10:
        native_vlan: 100
        mirror: 47
      11:
        native_vlan: 100
      47:
        native_vlan: 200
vlans:
  100:
    description: Default VLAN
  200:
    description: Monitor VLAN

$ sudo ovs-ofctl dump-flows br0 | fgrep table=0
 cookie=0x5adc15c0, duration=29.764s, table=0, n_packets=0, n_bytes=0,
idle_age=29, priority=9099,in_port=11 actions=resubmit(,1)
 cookie=0x5adc15c0, duration=29.764s, table=0, n_packets=0, n_bytes=0,
idle_age=29, priority=9099,in_port=47 actions=resubmit(,1)
 cookie=0x5adc15c0, duration=29.772s, table=0, n_packets=0, n_bytes=0,
idle_age=29, priority=0 actions=drop

**Comment by anarkiwi** [comment]
Ahhh OK. The sense of the config is incorrect. It's the opposite of what you configured.

If you have  mirror on an interface, that means it mirrors from that interface. Not that it mirrors *to* that interface. It's different to the ACL meaning.

You want:

47:
   mirror: 10

**Comment by grafnu** [comment]
Oh - is there a way then to mirror multiple ports? Basically I'd want to be
able to mirror both 10 & 11 to 47... not sure how to do that with the
setting.

Once I understand what the behavior is supposed to be I can file
bugs/enhancements for the parts that don't align...

It only mirrors the input on the port, correct, not the output?  Is there
any way to mirror the output on a port?

Also, according to the trace it's mirroring the output twice. See below --
it outputs to port 47 twice.


sudo ovs-appctl ofproto/trace br0
udp,in_port=10,dl_src=00:40:ae:03:3e:fa,dl_dst=ff:ff:ff:ff:ff:ff,nw_src=172.28.64.32,nw_dst=172.28.71.255,udp_src=47809,udp_dst=47808
-generate
Flow:
udp,in_port=10,vlan_tci=0x0000,dl_src=00:40:ae:03:3e:fa,dl_dst=ff:ff:ff:ff:ff:ff,nw_src=172.28.64.32,nw_dst=172.28.71.255,nw_tos=0,nw_ecn=0,nw_ttl=0,tp_src=47809,tp_dst=47808

bridge("br0")
-------------
 0. in_port=10, priority 9099, cookie 0x5adc15c0
    goto_table:1
 1. in_port=10,vlan_tci=0x0000/0x1fff, priority 9000, cookie 0x5adc15c0
    output:47
     >> Nonexistent output port
    push_vlan:0x8100
    set_field:4196->vlan_vid
    goto_table:3
 3. in_port=10,dl_vlan=100,dl_src=00:40:ae:03:3e:fa, priority 9098, cookie
0x5adc15c0
    goto_table:7
 7. priority 9000, cookie 0x5adc15c0
    goto_table:8
 8. in_port=10,dl_vlan=100,dl_dst=ff:ff:ff:ff:ff:ff, priority 9009, cookie
0x5adc15c0
    output:47
     >> Nonexistent output port
    pop_vlan
    output:11
     >> Nonexistent output port

Final flow: unchanged
Megaflow:
recirc_id=0,eth,ip,in_port=10,vlan_tci=0x0000/0x1fff,dl_src=00:40:ae:03:3e:fa,dl_dst=ff:ff:ff:ff:ff:ff,nw_src=
128.0.0.0/1,nw_dst=128.0.0.0/1,nw_frag=no
Datapath actions: drop

**Comment by anarkiwi** [comment]
Right now the mirror setting only mirrors one port. We can certainly mirror more than one, it is just not implemented.

Output to that port is mirrored also. You will see flows in the flood table and then also the destination table where hosts are learned on that port.

I don't see the double mirror? I see output 11 and output 47, only.

**Comment by grafnu** [comment]
There's an output:47 after both table 1 and table 8 (in the trace I sent previously).

Here's the for input on port 11, which is output on port 10 (but is not mirrored). I don't see any entry in the OF table that trigger any mirroring on output to port 10. I've attached the OF dump... maybe I'm looking in the wrong place?  
[dump-flows.txt](https://github.com/faucetsdn/faucet/files/1645347/dump-flows.txt)


$ sudo ovs-appctl ofproto/trace br0 udp,in_port=11,dl_src=00:40:ae:03:3e:fa,dl_dst=ff:ff:ff:ff:ff:ff,nw_src=172.28.64.32,nw_dst=172.28.71.255,udp_src=47809,udp_dst=47808 -generate
Flow: udp,in_port=11,vlan_tci=0x0000,dl_src=00:40:ae:03:3e:fa,dl_dst=ff:ff:ff:ff:ff:ff,nw_src=172.28.64.32,nw_dst=172.28.71.255,nw_tos=0,nw_ecn=0,nw_ttl=0,tp_src=47809,tp_dst=47808

bridge("br0")
-------------
 0. in_port=11, priority 9099, cookie 0x5adc15c0
    goto_table:1
 1. in_port=11,vlan_tci=0x0000/0x1fff, priority 9000, cookie 0x5adc15c0
    push_vlan:0x8100
    set_field:4196->vlan_vid
    goto_table:3
 3. in_port=11,dl_vlan=100,dl_src=00:40:ae:03:3e:fa, priority 9098, cookie 0x5adc15c0
    goto_table:7
 7. priority 9000, cookie 0x5adc15c0
    goto_table:8
 8. in_port=11,dl_vlan=100,dl_dst=ff:ff:ff:ff:ff:ff, priority 9008, cookie 0x5adc15c0
    pop_vlan
    output:10
     >> Nonexistent output port

Final flow: unchanged
Megaflow: recirc_id=0,eth,ip,in_port=11,vlan_tci=0x0000/0x1fff,dl_src=00:40:ae:03:3e:fa,dl_dst=ff:ff:ff:ff:ff:ff,nw_src=128.0.0.0/1,nw_dst=128.0.0.0/1,nw_frag=no
Datapath actions: drop

**Comment by anarkiwi** [comment]
You don't see the flow because the output rule implementing the mirror on output isn't added until a host is learned (which won't be done by the time oftrace) has run the pipeline.

It maybe I github rendering problem, I don't see any double output.

I suggest configuring this and pushing some packets through and capturing the result including a flow dump.

If it does the wrong thing we can fix it.

**Comment by grafnu** [comment]
I uploaded the double-mirror case -- [duplicate_mirror.txt](https://github.com/faucetsdn/faucet/files/1645373/duplicate_mirror.txt) -- you should see output:47 after table=1 and table=8

Similarly, here's the flow that's not being mirrored (from 11->12) [reverse_mirror.txt](https://github.com/faucetsdn/faucet/files/1645372/reverse_mirror.txt) -- note that the flow has been learned (you can see it in the table 3 entry, I'm using the -generate option to trace which triggers the learning).

I'm working towards the "push some packets through" ability (need to figure out scapy still)... but, I don't see any entry in the OF table (even after learning) that would cause the output. Specifically, where in  
[learned_dump.txt](https://github.com/faucetsdn/faucet/files/1645379/learned_dump.txt) would the mirroring show up?  I see the "learned" rule, but no mirroring anywhere?

**Comment by grafnu** [comment]
Ug -- uploaded the wrong file for 
[reverse_mirror.txt](https://github.com/faucetsdn/faucet/files/1645380/reverse_mirror.txt) -- that's the updated one. (And it's 11->10, not 11->12 like I said before)

**Comment by anarkiwi** [comment]
Use the exact same config from the test FaucetUntaggedMirrorTest, to reduce external variables. Things aren't making sense to me.

Run the test with -k (causing it to keep output).

Observe in the flow tables, flows like the following:

 cookie=0x5adc15c0, duration=11.273s, table=7, n_packets=5, n_bytes=434, idle_timeout=298, priority=9099,dl_vlan=100,dl_dst=6e:14:b0:0e:a7:92 actions=output:3,pop_vlan,output:1

As you see, output to the mirror port, and output to the original port.

No double output.

**Comment by grafnu** [comment]
Ok, started with the test case and expanded it until I ran into the problem. Basically, unicast works fine, but broadcast behaves oddly.  See 
[test_config.yaml.txt](https://github.com/faucetsdn/faucet/files/1648629/test_config.yaml.txt) for the input config, 
[vtest.sh.txt](https://github.com/faucetsdn/faucet/files/1648630/vtest.sh.txt) for the test script, and 
[test_results.txt](https://github.com/faucetsdn/faucet/files/1648631/test_results.txt) for results.

Summary is that broadcast can sometimes triple the output, double, or drop some output, depending on the exact configuration. I think it has something to do with the fact that it's trying to mirror based on vlan usage, which doesn't quite work properly. 

That said -- this isn't blocking anything and so I wouldn't rate it as high-priority, more just something to be aware of in terms of mirroring implementation.

**Comment by anarkiwi** [comment]
OK thanks that's very helpful - broadcast mirroring not working as expected. That's a clear bug. I changed the description and will fix it.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/f4853c55781a1e9bf984aec2a05637d2f3d77286

We now require that no VLANs be configured on the mirroring port (it makes no sense to do any VLAN processing on the port at all, since it is just mirroring another port).
