### ISSUE TITLE
mirror interface should support more than one port

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#1547]
Right now interface monitoring supports just one interface:

interfaces:
   mirrored_interface:
      number: 1
      native_vlan: 100
   mirroring_interface:
      number: 2
      mirror: mirrored_interface

@cglewis  It'd be useful for mirror to support a list so it can mirror potentially lots of interfaces. 

It'd also be useful to be able to mirror an entire vlan/list of vlans.

**Comment by cglewis** [comment]
being able to mirror at L3 would be useful too.  perhaps some combination with ACLs?  but yes, for now just supporting multiple ports being mirrored to a port would be a great start.
