### ISSUE TITLE
explicit acl output tagged vlan gets dropped

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#1552]
I'm working through a use-case using tagged VLANs based off of ACLs to distribute broadcast packets to a subset of output ports. This all works fine and dandy, except that it requires that the input port have the appropriate VLAN indicated as a tagged vlan -- which is not required in my case since the input port will *never* be an output of that particular vlan. See [faucet.yaml.txt](https://github.com/faucetsdn/faucet/files/1655030/faucet.yaml.txt) for my test configuration. With this, the following behavior is observed:

in_port 10  => output 11, 12, 13
in_port 11 => drop
in_port 12 => output 10, 11, 13
in_port 13 => output 12

Of these, only in_port=11 exhibits the described behavior. I would *expect* the behavior of this flow to be:
1) Accept packet b/c acl_in rule is "accept all"
2) Assign vlan ID 200 based on acl output clause
3) Distribute to valid targets of VLAN 200 (12 and 13)

However, the result is surprising because the acl_rule explicitly indicates that the packet should be accepted, yet it is dropped.  Looking at the OF rules generated 
[dump-flows.txt](https://github.com/faucetsdn/faucet/files/1655048/dump-flows.txt)
, table 0 accepts the packet, then passed to table 1 where it's rejected. Simple fix would be to skip table 1 in the case (and straight to table 3?) where a vlan is explicitly added in the output clause, since theoretically at that point no more input vlan processing is required.

It can be made to work, as per in_port=13, but this requires creating many unnecessary vlans in the system -- functional, but not elegant. In my use case, this translates to one unnecessary vlan in the entire global (stacked) system, which will be ~1000 in my particular case.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/4b7790114f8c9c9ccea9ff3ee4fe6868096c230a

Implements this - see FaucetTaggedSwapVidMirrorTest. 

combinatorial_port_flood: False at dp level is required.
