### ISSUE TITLE
stacked broadcast gets echoed out input port for stacks with max hops from root > 2

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#1564]
When faucet switches are configured in stacking mode, a broadcast-in packet on a switch port will eventually get echoed out on the same port. This happens because the broadcast is always first sent all the way up to the root of the stacking tree, and then sent back down -- and then when it reaches the leaf node switch it no longer has the context of which input port it came from. This is different than in "normal" switch mode because in that case packets are broadcast locally at the leaf node first, implicitly sending it up the hierarchy, but they never come back!

Not sure how significance this is, but it's a "difference" so I thought I'd flag it.

**Comment by anarkiwi** [comment]
It is as you say - I should have documented this (in ensuring no loops
between switches). It is not ideal. On my list for cleaning up. Thank you
for documentating.

**Comment by anarkiwi** [comment]
This is addressed/tested in https://github.com/faucetsdn/faucet/pull/3117 - ensure that when an external switch is connected to a FAUCET stack, that the switch is connected on a FAUCET port with loop_protect_external: True (necessary for any size FAUCET stack to prevent a loop appearing to the non-FAUCET network).
