### ISSUE TITLE
faucet fails to start with stack and non-stack in the same config

### ISSUE THREAD

**Issue by trungdtbk** [faucetsdn/faucet#1574]
The config test passes but Faucet can't start. I figure out the bug with how we build stack graph for each dp in line 360 in dp.py. graph.size() is always non-zero for all dps, so when Faucet starts and adds Valves, it hits networkx NodeNotFound exception.
It is a simple fix. I wonder if we need another test?

**Comment by anarkiwi** [comment]
Thank you for finding and reporting it. Yes, another test will be required.

**Comment by trungdtbk** [comment]
Ok, I'll work on this.

**Comment by anarkiwi** [comment]
I was able to fix it while adding missing test coverage (thanks again for reporting it).

https://github.com/faucetsdn/faucet/commit/15c98d6f86c774d453d78be301da62cf7c797ae0
