### ISSUE TITLE
config reload does not properly reconfigure flood table.

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#1592]
As per the sequence of commands below, sending a HUP to faucet will cause it to reload the configuration, but it does not properly reprogram table 8. This might be because I'm changing the value of "unicast_flood" and VLAN configuration. This is switching from [config_a.yaml.txt](https://github.com/faucetsdn/faucet/files/1682064/config_a.yaml.txt) to [config_b.yaml.txt](https://github.com/faucetsdn/faucet/files/1682065/config_b.yaml.txt). Specifically, note that the HUP does not change the number of flows in table=8, but a restart does the needful.

faucet$ **cp config_a.yaml.txt inst/faucet.yaml**
faucet$ **docker restart faucet**
faucet
faucet$ **sudo ovs-ofctl dump-flows SWSEC0B  | fgrep table=8 | wc -l**
396
faucet$ **fgrep request inst/faucet.log**
faucet$ **cp config_b.yaml.txt inst/faucet.yaml**
faucet$ **docker exec faucet pkill -HUP -f faucet.faucet**
faucet$ **fgrep request inst/faucet.log**
Jan 31 12:43:27 faucet INFO     request to reload configuration
faucet$ **sudo ovs-ofctl dump-flows SWSEC0B  | fgrep table=8 | wc -l**
396
faucet$ **docker restart faucet**
faucet
faucet$ **sudo ovs-ofctl dump-flows SWSEC0B  | fgrep table=8 | wc -l**
491

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/5306627188f1e150cc5adf961cbe477c82544047 et al should fix this, if this was a problem where stacking was enabled (we did not correctly update stacking state).

If not fixed still, please include faucet.log to show whether there's a warm start problem.

**Comment by grafnu** [comment]
Unfortunately, still not WAI. Here's the [faucet.log](https://github.com/faucetsdn/faucet/files/1739028/faucet.log)
