### ISSUE TITLE
Allow mirroring to VLAN

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#1600]
Instead of mirroring to an explicit output port, in a stacked system, it would be great to be able to mirror to a specific VLAN. This way, it would allow any individual dataplane could mirror to the vlan, it would then be routed through the system as normal, and then output in one place (one port on one dataplane).  Otherwise, in order to mirror anything in the system would require hooking up dedicated mirroring cables to every physical switch.

**Comment by cglewis** [comment]
Really interesting idea, I have a use case this would be handy for as well.

**Comment by anarkiwi** [comment]
I believe this is obsolete (the tunnel feature can do this, or for more complex cases a coprocessor can do it). Please reopen with details if stack tunneling/coprocessing doesn't cover it.
