### ISSUE TITLE
acl rule out mirroring sometimes crashes FAUCET on startup

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#1611]
Mirroring from an ACL ([mirror_error.yaml.txt](https://github.com/faucetsdn/faucet/files/1692464/mirror_error.yaml.txt)) *sometimes* will cause the system to crash on startup with 
[error_msg.txt](https://github.com/faucetsdn/faucet/files/1692465/error_msg.txt). It happens about half the time. I've tried to distill it down to the bare minimum, and it seems to be that something is getting crossed by the ACLs between the two dataplanes. Sometimes, it seems like it's looking to configure port 47 on the _wrong_ dataplane to be a mirrored output. Sometimes. Commenting out one or the other of the acl_in clauses makes the problem go away.

**Comment by grafnu** [comment]
My Python-foo is still weak, but I think it's because mirror_destinations is effectively declared as a global/static class variable in acl.py, so that the same set of ports is shared across all VLANs. I think the initializer needs to be moved to the __init__ method... If this is the right analysis and fix, let me know and I can put together my first-ever Pull Request.

diff --git a/faucet/acl.py b/faucet/acl.py
index 2de29894..642a897f 100644
--- a/faucet/acl.py
+++ b/faucet/acl.py
@@ -56,7 +56,7 @@ The output action contains a dictionary with the following elements:
 """
 
     # Resolved port numbers which are mirror action destinations.
-    mirror_destinations = set() # type: set
+    mirror_destinations = None
     rules = None
     exact_match = None
     defaults = {
@@ -99,6 +99,7 @@ The output action contains a dictionary with the following elements:
             assert 'rules' in conf, 'no rules found for ACL %s' % _id
             rules = conf['rules']
         self.rules = []
+        self.mirror_destinations = set()
         assert isinstance(rules, list)
         for match_fields in (MATCH_FIELDS, OLD_MATCH_FIELDS):
             for match in list(match_fields.keys()):

**Comment by grafnu** [comment]
Now with less markdown formatting!

```
diff --git a/faucet/acl.py b/faucet/acl.py
index 2de29894..642a897f 100644
--- a/faucet/acl.py
+++ b/faucet/acl.py
@@ -56,7 +56,7 @@ The output action contains a dictionary with the following elements:
 """
 
     # Resolved port numbers which are mirror action destinations.
-    mirror_destinations = set() # type: set
+    mirror_destinations = None
     rules = None
     exact_match = None
     defaults = {
@@ -99,6 +99,7 @@ The output action contains a dictionary with the following elements:
             assert 'rules' in conf, 'no rules found for ACL %s' % _id
             rules = conf['rules']
         self.rules = []
+        self.mirror_destinations = set()
         assert isinstance(rules, list)
         for match_fields in (MATCH_FIELDS, OLD_MATCH_FIELDS):
             for match in list(match_fields.keys()):

```

**Comment by anarkiwi** [comment]
Nice catch! However the problem is deeper - there is a bunch of inappropriate per-DP finalizing() being done which is the root cause. I'll fix that - unfortunately more than a few lines.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/d79bb9186bfbd41a78468b07003d4b6e466d7b5e, and https://github.com/faucetsdn/faucet/commit/f23ff040d754fd7c056ec40de86abfceaa374450
