### ISSUE TITLE
port mirroring doesn't mirror input ACLs

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#1622]
Port mirroring is applied to VLAN ACLs (table 1), so if a packet is received on a port but dropped in a port ACL then it won't be mirrored (even though it should be mirrored since it came in on the indicated port).

**Comment by anarkiwi** [comment]
This is working as intended. The port ACL always gets executed first by design - VLAN ACLs only see what the port ACL passes through for any reason.
