### ISSUE TITLE
BGP crash trying to parse IPv6 neighbor when IPv4 neighbor connects

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#1706]
Feb 26 15:06:43 faucet INFO     BGP add 0.0.0.0/0 nexthop 210.7.38.89
Feb 26 15:06:43 faucet ERROR    BGP nexthop 127.0.0.1 for prefix 163.7.136.0/23 is not a connected network
Feb 26 15:06:43 faucet ryu-manager[6373]: Connection to peer: 127.0.0.1 established
Feb 26 15:06:43 faucet ryu-manager[6373]: hub: uncaught exception: Traceback (most recent call last):
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/strategy/ipv4.py", line 127, in str_to_int
Feb 26 15:06:43 faucet ryu-manager[6373]:     return _struct.unpack('>I', _inet_aton(addr))[0]
Feb 26 15:06:43 faucet ryu-manager[6373]: OSError: illegal IP address string passed to inet_aton
Feb 26 15:06:43 faucet ryu-manager[6373]: During handling of the above exception, another exception occurred:
Feb 26 15:06:43 faucet ryu-manager[6373]: Traceback (most recent call last):
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/ip/__init__.py", line 311, in __init__
Feb 26 15:06:43 faucet ryu-manager[6373]:     self._value = self._module.str_to_int(addr, flags)
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/strategy/ipv4.py", line 129, in str_to_int
Feb 26 15:06:43 faucet ryu-manager[6373]:     raise AddrFormatError('%r is not a valid IPv4 address string!' % addr)
Feb 26 15:06:43 faucet ryu-manager[6373]: netaddr.core.AddrFormatError: '::1' is not a valid IPv4 address string!
Feb 26 15:06:43 faucet ryu-manager[6373]: During handling of the above exception, another exception occurred:
Feb 26 15:06:43 faucet ryu-manager[6373]: Traceback (most recent call last):
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/ryu/lib/addrconv.py", line 29, in text_to_bin
Feb 26 15:06:43 faucet ryu-manager[6373]:     return self._addr(text, **self._addr_kwargs).packed
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/ip/__init__.py", line 314, in __init__
Feb 26 15:06:43 faucet ryu-manager[6373]:     % (addr, self._module.version))
Feb 26 15:06:43 faucet ryu-manager[6373]: netaddr.core.AddrFormatError: base address '::1' is not IPv4
Feb 26 15:06:43 faucet ryu-manager[6373]: During handling of the above exception, another exception occurred:
Feb 26 15:06:43 faucet ryu-manager[6373]: Traceback (most recent call last):
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/strategy/ipv4.py", line 125, in str_to_int
Feb 26 15:06:43 faucet ryu-manager[6373]:     return _struct.unpack('>I', _inet_pton(AF_INET, addr))[0]
Feb 26 15:06:43 faucet ryu-manager[6373]: OSError: illegal IP address string passed to inet_pton
Feb 26 15:06:43 faucet ryu-manager[6373]: During handling of the above exception, another exception occurred:
Feb 26 15:06:43 faucet ryu-manager[6373]: Traceback (most recent call last):
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/ip/__init__.py", line 311, in __init__
Feb 26 15:06:43 faucet ryu-manager[6373]:     self._value = self._module.str_to_int(addr, flags)
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/strategy/ipv4.py", line 129, in str_to_int
Feb 26 15:06:43 faucet ryu-manager[6373]:     raise AddrFormatError('%r is not a valid IPv4 address string!' % addr)
Feb 26 15:06:43 faucet ryu-manager[6373]: netaddr.core.AddrFormatError: '::1' is not a valid IPv4 address string!
Feb 26 15:06:43 faucet ryu-manager[6373]: During handling of the above exception, another exception occurred:
Feb 26 15:06:43 faucet ryu-manager[6373]: Traceback (most recent call last):
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/ip/__init__.py", line 791, in parse_ip_network
Feb 26 15:06:43 faucet ryu-manager[6373]:     ip = IPAddress(val1, module.version, flags=INET_PTON)
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/ip/__init__.py", line 314, in __init__
Feb 26 15:06:43 faucet ryu-manager[6373]:     % (addr, self._module.version))
Feb 26 15:06:43 faucet ryu-manager[6373]: netaddr.core.AddrFormatError: base address '::1' is not IPv4
Feb 26 15:06:43 faucet ryu-manager[6373]: During handling of the above exception, another exception occurred:
Feb 26 15:06:43 faucet ryu-manager[6373]: Traceback (most recent call last):
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/ip/__init__.py", line 791, in parse_ip_network
Feb 26 15:06:43 faucet ryu-manager[6373]:     ip = IPAddress(val1, module.version, flags=INET_PTON)
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/ip/__init__.py", line 314, in __init__
Feb 26 15:06:43 faucet ryu-manager[6373]:     % (addr, self._module.version))
Feb 26 15:06:43 faucet ryu-manager[6373]: netaddr.core.AddrFormatError: base address '::1' is not IPv4
Feb 26 15:06:43 faucet ryu-manager[6373]: During handling of the above exception, another exception occurred:
Feb 26 15:06:43 faucet ryu-manager[6373]: Traceback (most recent call last):
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/ryu/lib/hub.py", line 59, in _launch
Feb 26 15:06:43 faucet ryu-manager[6373]:     return func(*args, **kwargs)
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/base.py", line 256, in start
Feb 26 15:06:43 faucet ryu-manager[6373]:     self._run(*args, **kwargs)
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/peer.py", line 683, in _run
Feb 26 15:06:43 faucet ryu-manager[6373]:     self._process_outgoing_msg_list()
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/peer.py", line 769, in _process_outgoing_msg_list
Feb 26 15:06:43 faucet ryu-manager[6373]:     self._send_outgoing_route(outgoing_msg)
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/peer.py", line 729, in _send_outgoing_route
Feb 26 15:06:43 faucet ryu-manager[6373]:     self._protocol.send(update_msg)
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/speaker.py", line 395, in send
Feb 26 15:06:43 faucet ryu-manager[6373]:     self._send_with_lock(msg)
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/speaker.py", line 384, in _send_with_lock
Feb 26 15:06:43 faucet ryu-manager[6373]:     self._socket.sendall(msg.serialize())
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/ryu/lib/packet/bgp.py", line 5237, in serialize
Feb 26 15:06:43 faucet ryu-manager[6373]:     tail = self.serialize_tail()
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/ryu/lib/packet/bgp.py", line 5457, in serialize_tail
Feb 26 15:06:43 faucet ryu-manager[6373]:     binpathattrs += pa.serialize()
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/ryu/lib/packet/bgp.py", line 3653, in serialize
Feb 26 15:06:43 faucet ryu-manager[6373]:     value = self.serialize_value()
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/ryu/lib/packet/bgp.py", line 3863, in serialize_value
Feb 26 15:06:43 faucet ryu-manager[6373]:     addrconv.ipv4.text_to_bin(self.value))
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/ryu/lib/addrconv.py", line 36, in text_to_bin
Feb 26 15:06:43 faucet ryu-manager[6373]:     ip = self._fallback(text, **self._addr_kwargs)
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/ip/__init__.py", line 916, in __init__
Feb 26 15:06:43 faucet ryu-manager[6373]:     implicit_prefix=implicit_prefix, flags=flags)
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/ip/__init__.py", line 795, in parse_ip_network
Feb 26 15:06:43 faucet ryu-manager[6373]:     expanded_addr = _ipv4.expand_partial_address(val1)
Feb 26 15:06:43 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/strategy/ipv4.py", line 259, in expand_partial_address
Feb 26 15:06:43 faucet ryu-manager[6373]:     raise error
Feb 26 15:06:43 faucet ryu-manager[6373]: netaddr.core.AddrFormatError: invalid partial IPv4 address: '::1'!
Feb 26 15:06:46 faucet ryu-manager[6373]: API method operator.show called with args: {'params': ['neighbor', 'summary'], 'format': 'json'}
Feb 26 15:06:51 faucet ryu-manager[6373]: API method operator.show called with args: {'params': ['neighbor', 'summary'], 'format': 'json'}
Feb 26 15:06:53 faucet ryu-manager[6373]: Connection to peer ::1 lost, reason: failed to write to socket Resetting retry connect loop: False
Feb 26 15:06:53 faucet ryu-manager[6373]: failed to write to socket
Feb 26 15:06:57 faucet ryu-manager[6373]: API method operator.show called with args: {'params': ['neighbor', 'summary'], 'format': 'json'}
Feb 26 15:07:02 faucet ryu-manager[6373]: API method operator.show called with args: {'params': ['neighbor', 'summary'], 'format': 'json'}
Feb 26 15:07:09 faucet ryu-manager[6373]: API method operator.show called with args: {'params': ['neighbor', 'summary'], 'format': 'json'}
Feb 26 15:07:11 faucet ryu-manager[6373]: hub: uncaught exception: Traceback (most recent call last):
Feb 26 15:07:11 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/ryu/lib/hub.py", line 59, in _launch
Feb 26 15:07:11 faucet ryu-manager[6373]:     return func(*args, **kwargs)
Feb 26 15:07:11 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/peer.py", line 1305, in _connect_loop
Feb 26 15:07:11 faucet ryu-manager[6373]:     password=password)
Feb 26 15:07:11 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/base.py", line 437, in _connect_tcp
Feb 26 15:07:11 faucet ryu-manager[6373]:     self._spawn(conn_name, conn_handler, sock)
Feb 26 15:07:11 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/base.py", line 219, in _spawn
Feb 26 15:07:11 faucet ryu-manager[6373]:     self._validate_callable(callable_)
Feb 26 15:07:11 faucet ryu-manager[6373]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/base.py", line 215, in _validate_callable
Feb 26 15:07:11 faucet ryu-manager[6373]:     raise ActivityException(desc='Tried to spawn a child thread '
Feb 26 15:07:11 faucet ryu-manager[6373]: ryu.services.protocols.bgp.base.ActivityException: 100.1 - Tried to spawn a child thread before this Activity was started.
Feb 26 15:07:11 faucet ryu-manager[6373]: Connection to peer closed for unknown reasons.

**Comment by gizmoguy** [comment]
> Feb 27 08:49:26 faucet ryu-manager[19754]: Connection to peer: 127.0.0.1 established
> Feb 27 08:49:26 faucet ryu-manager[19754]: hub: uncaught exception: Traceback (most recent call last):
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/strategy/ipv4.py", line 127, in str_to_int
> Feb 27 08:49:26 faucet ryu-manager[19754]:     return _struct.unpack('>I', _inet_aton(addr))[0]
> Feb 27 08:49:26 faucet ryu-manager[19754]: OSError: illegal IP address string passed to inet_aton
> Feb 27 08:49:26 faucet ryu-manager[19754]: During handling of the above exception, another exception occurred:
> Feb 27 08:49:26 faucet ryu-manager[19754]: Traceback (most recent call last):
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/ip/__init__.py", line 311, in __init__
> Feb 27 08:49:26 faucet ryu-manager[19754]:     self._value = self._module.str_to_int(addr, flags)
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/strategy/ipv4.py", line 129, in str_to_int
> Feb 27 08:49:26 faucet ryu-manager[19754]:     raise AddrFormatError('%r is not a valid IPv4 address string!' % addr)
> Feb 27 08:49:26 faucet ryu-manager[19754]: netaddr.core.AddrFormatError: '::1' is not a valid IPv4 address string!
> Feb 27 08:49:26 faucet ryu-manager[19754]: During handling of the above exception, another exception occurred:
> Feb 27 08:49:26 faucet ryu-manager[19754]: Traceback (most recent call last):
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/ryu/lib/addrconv.py", line 29, in text_to_bin
> Feb 27 08:49:26 faucet ryu-manager[19754]:     return self._addr(text, **self._addr_kwargs).packed
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/ip/__init__.py", line 314, in __init__
> Feb 27 08:49:26 faucet ryu-manager[19754]:     % (addr, self._module.version))
> Feb 27 08:49:26 faucet ryu-manager[19754]: netaddr.core.AddrFormatError: base address '::1' is not IPv4
> Feb 27 08:49:26 faucet ryu-manager[19754]: During handling of the above exception, another exception occurred:
> Feb 27 08:49:26 faucet ryu-manager[19754]: Traceback (most recent call last):
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/strategy/ipv4.py", line 125, in str_to_int
> Feb 27 08:49:26 faucet ryu-manager[19754]:     return _struct.unpack('>I', _inet_pton(AF_INET, addr))[0]
> Feb 27 08:49:26 faucet ryu-manager[19754]: OSError: illegal IP address string passed to inet_pton
> Feb 27 08:49:26 faucet ryu-manager[19754]: During handling of the above exception, another exception occurred:
> Feb 27 08:49:26 faucet ryu-manager[19754]: Traceback (most recent call last):
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/ip/__init__.py", line 311, in __init__
> Feb 27 08:49:26 faucet ryu-manager[19754]:     self._value = self._module.str_to_int(addr, flags)
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/strategy/ipv4.py", line 129, in str_to_int
> Feb 27 08:49:26 faucet ryu-manager[19754]:     raise AddrFormatError('%r is not a valid IPv4 address string!' % addr)
> Feb 27 08:49:26 faucet ryu-manager[19754]: netaddr.core.AddrFormatError: '::1' is not a valid IPv4 address string!
> Feb 27 08:49:26 faucet ryu-manager[19754]: During handling of the above exception, another exception occurred:
> Feb 27 08:49:26 faucet ryu-manager[19754]: Traceback (most recent call last):
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/ip/__init__.py", line 791, in parse_ip_network
> Feb 27 08:49:26 faucet ryu-manager[19754]:     ip = IPAddress(val1, module.version, flags=INET_PTON)
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/ip/__init__.py", line 314, in __init__
> Feb 27 08:49:26 faucet ryu-manager[19754]:     % (addr, self._module.version))
> Feb 27 08:49:26 faucet ryu-manager[19754]: netaddr.core.AddrFormatError: base address '::1' is not IPv4
> Feb 27 08:49:26 faucet ryu-manager[19754]: During handling of the above exception, another exception occurred:
> Feb 27 08:49:26 faucet ryu-manager[19754]: Traceback (most recent call last):
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/ryu/lib/hub.py", line 59, in _launch
> Feb 27 08:49:26 faucet ryu-manager[19754]:     return func(*args, **kwargs)
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/base.py", line 256, in start
> Feb 27 08:49:26 faucet ryu-manager[19754]:     self._run(*args, **kwargs)
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/peer.py", line 683, in _run
> Feb 27 08:49:26 faucet ryu-manager[19754]:     self._process_outgoing_msg_list()
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/peer.py", line 769, in _process_outgoing_msg_list
> Feb 27 08:49:26 faucet ryu-manager[19754]:     self._send_outgoing_route(outgoing_msg)
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/peer.py", line 729, in _send_outgoing_route
> Feb 27 08:49:26 faucet ryu-manager[19754]:     self._protocol.send(update_msg)
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/speaker.py", line 395, in send
> Feb 27 08:49:26 faucet ryu-manager[19754]:     self._send_with_lock(msg)
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/speaker.py", line 384, in _send_with_lock
> Feb 27 08:49:26 faucet ryu-manager[19754]:     self._socket.sendall(msg.serialize())
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/ryu/lib/packet/bgp.py", line 5237, in serialize
> Feb 27 08:49:26 faucet ryu-manager[19754]:     tail = self.serialize_tail()
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/ryu/lib/packet/bgp.py", line 5457, in serialize_tail
> Feb 27 08:49:26 faucet ryu-manager[19754]:     binpathattrs += pa.serialize()
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/ryu/lib/packet/bgp.py", line 3653, in serialize
> Feb 27 08:49:26 faucet ryu-manager[19754]:     value = self.serialize_value()
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/ryu/lib/packet/bgp.py", line 3863, in serialize_value
> Feb 27 08:49:26 faucet ryu-manager[19754]:     addrconv.ipv4.text_to_bin(self.value))
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/ryu/lib/addrconv.py", line 36, in text_to_bin
> Feb 27 08:49:26 faucet ryu-manager[19754]:     ip = self._fallback(text, **self._addr_kwargs)
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/ip/__init__.py", line 916, in __init__
> Feb 27 08:49:26 faucet ryu-manager[19754]:     implicit_prefix=implicit_prefix, flags=flags)
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/ip/__init__.py", line 795, in parse_ip_network
> Feb 27 08:49:26 faucet ryu-manager[19754]:     expanded_addr = _ipv4.expand_partial_address(val1)
> Feb 27 08:49:26 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/netaddr/strategy/ipv4.py", line 259, in expand_partial_address
> Feb 27 08:49:26 faucet ryu-manager[19754]:     raise error
> Feb 27 08:49:26 faucet ryu-manager[19754]: netaddr.core.AddrFormatError: invalid partial IPv4 address: '::1'!
> Feb 27 08:49:30 faucet ryu-manager[19754]: API method operator.show called with args: {'params': ['neighbor', 'summary'], 'format': 'json'}
> Feb 27 08:49:36 faucet ryu-manager[19754]: API method operator.show called with args: {'params': ['neighbor', 'summary'], 'format': 'json'}
> Feb 27 08:49:38 faucet ryu-manager[19754]: Connection to peer ::1 lost, reason: failed to write to socket Resetting retry connect loop: False
> Feb 27 08:49:38 faucet ryu-manager[19754]: failed to write to socket
> Feb 27 08:49:42 faucet ryu-manager[19754]: API method operator.show called with args: {'params': ['neighbor', 'summary'], 'format': 'json'}
> Feb 27 08:49:49 faucet ryu-manager[19754]: API method operator.show called with args: {'params': ['neighbor', 'summary'], 'format': 'json'}
> Feb 27 08:49:55 faucet ryu-manager[19754]: API method operator.show called with args: {'params': ['neighbor', 'summary'], 'format': 'json'}
> Feb 27 08:49:55 faucet dhcpd[2376]: DHCPREQUEST for 163.7.137.53 from 00:19:b9:19:6e:0c (necro) via ens5.250
> Feb 27 08:49:55 faucet dhcpd[2376]: DHCPACK on 163.7.137.53 to 00:19:b9:19:6e:0c (necro) via ens5.250
> Feb 27 08:49:56 faucet ryu-manager[19754]: hub: uncaught exception: Traceback (most recent call last):
> Feb 27 08:49:56 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/ryu/lib/hub.py", line 59, in _launch
> Feb 27 08:49:56 faucet ryu-manager[19754]:     return func(*args, **kwargs)
> Feb 27 08:49:56 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/peer.py", line 1305, in _connect_loop
> Feb 27 08:49:56 faucet ryu-manager[19754]:     password=password)
> Feb 27 08:49:56 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/base.py", line 437, in _connect_tcp
> Feb 27 08:49:56 faucet ryu-manager[19754]:     self._spawn(conn_name, conn_handler, sock)
> Feb 27 08:49:56 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/base.py", line 219, in _spawn
> Feb 27 08:49:56 faucet ryu-manager[19754]:     self._validate_callable(callable_)
> Feb 27 08:49:56 faucet ryu-manager[19754]:   File "/usr/local/lib/python3.5/dist-packages/ryu/services/protocols/bgp/base.py", line 215, in _validate_callable
> Feb 27 08:49:56 faucet ryu-manager[19754]:     raise ActivityException(desc='Tried to spawn a child thread '
> Feb 27 08:49:56 faucet ryu-manager[19754]: ryu.services.protocols.bgp.base.ActivityException: 100.1 - Tried to spawn a child thread before this Activity was started.
> Feb 27 08:49:56 faucet ryu-manager[19754]: Connection to peer closed for unknown reasons.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/c1ca62024a4d1434a1ef6cb1a77dc8d05a715291 et al.
