### ISSUE TITLE
Walk datapath on connection and enumerate port status

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#1713]
Currently we only collect port status events and export them to prometheus when we receive an event from ryu telling us of a change.

This causes us to miss the status of ports that were already up when faucet was started and that don't change status while faucet is running.

**Comment by gizmoguy** [comment]
Also applies to other inventory information about a port such as `of_port_curr_speed`

**Comment by cglewis** [comment]
this would also be a useful thing to send as events on faucet startup, though might have to think through that a bit so it doesn't flood messages on startup if there are a large number of devices or cause too big of a delay on startup/restart of faucet.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/3fceb055c0530637a1619af97edcf38ec622a58d

Done (Ryu gets this for us already at DP connect time, but we ignored it).
