### ISSUE TITLE
Some prometheus metrics claim to be gauges but aren't 

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#1720]
Both these metrics seem a little too large for my network.

TYPE port_vlan_hosts_learned gauge

port_vlan_hosts_learned{dp_id="0x46",dp_name="ovs-redcables",instance="faucet",job="faucet",port="4",vlan="250"} | 967

TYPE vlan_neighbors gauge

vlan_neighbors{dp_id="0x46",dp_name="ovs-redcables",instance="faucet",ipv="4",job="faucet",vlan="250"} | 252

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/31de54ed10029daf058409be5db2928b098b7e84 et al.
