### ISSUE TITLE
gRPC integration

### ISSUE THREAD

**Issue by kristiandrucker** [faucetsdn/faucet#1728]
Hi, is there a possibility to integrate faucet with gRPC for configuration of ports, vlans, acls. Simply everything that you can do with the config, plus monitoring stuff.

**Comment by anarkiwi** [comment]
Yes, there is that possibility. There is no work currently scheduled, but one possibility is the same as LINK022 (https://github.com/google/link022)  - ie. a gRPC agent, separate from the forwarding logic, receives config requests and rewrites config files/signals updates (in FAUCET's case, the YAML file). FAUCET already handles dynamic changes to its config including how to integrate those changes into runtime state so this would fit well. The gRPC agent can event do transactions on config if it likes (eg rollbacks).

**Comment by anarkiwi** [comment]
See https://github.com/faucetsdn/faucet/issues/1841 for RPC config/management.
