### ISSUE TITLE
ports with ACL action to output everything to another port never get an L2 learn

### ISSUE THREAD

**Issue by cglewis** [faucetsdn/faucet#1754]
For example:
```
acls:
    default:
        - rule:
            actions:
                output:
                    port: 48
dps:
    at-1:
        dp_id: 0x1
        hardware: "Allied-Telesis"
        group_table: True
        interfaces:
            1:
                native_vlan: 4090
                acl_in: default
            2:
                native_vlan: 4090
                acl_in: default
            48:
                permanent_learn: True
                native_vlan: 4090
vlans:
    4090:
```

And corresponding log file (notice only port48 gets an L2 learn):

```
Mar 08 21:03:07 faucet.valve INFO     DPID 1 (0x1) Cold start configuring DP
Mar 08 21:03:07 faucet.valve INFO     DPID 1 (0x1) Configuring VLAN 4090 vid:4090 ports:Port 1,Port 2,Port 48
Mar 08 21:03:07 faucet.valve INFO     DPID 1 (0x1) Port 1 configured
Mar 08 21:03:07 faucet.valve INFO     DPID 1 (0x1) Port 2 configured
Mar 08 21:03:07 faucet.valve INFO     DPID 1 (0x1) Port 48 configured
Mar 08 21:03:07 faucet.valve INFO     DPID 1 (0x1) Cold starting
Mar 08 21:03:07 faucet.valve INFO     DPID 1 (0x1) L2 learned xx:xx:xx:xx:xx:xx (L2 type 0x0806, L3 src x.x.x.x, L3 dst x.x.x.x) on Port 48 on VLAN 4090 (1 hosts total)
Mar 08 21:03:09 faucet.valve INFO     DPID 1 (0x1) L2 learned xx:xx:xx:xx:xx:xy (L2 type 0x9000, L3 src None, L3 dst None) on Port 48 on VLAN 4090 (2 hosts total)
Mar 08 21:04:51 faucet INFO     DPID 1 (0x1) port state 0 (reason 2)
Mar 08 21:04:51 faucet.valve INFO     DPID 1 (0x1) Port 2 down
Mar 08 21:04:51 faucet.valve INFO     DPID 1 (0x1) Port 2 up
```

**Comment by anarkiwi** [comment]
Is your intent, that packets are always output to port 48, but that FAUCET should know how to switch packets destined back there?

Seems like a very useful feature for an externalized NFV filter, so the external system can just poke a packet back in another port to that destination and FAUCET will switch it to the right place.

Just want to make sure of the intent before I implement.

**Comment by cglewis** [comment]
yeah, I think that's right.  Basically if I tell all packets for a given port, 1, to be output to a different port, 48, then FAUCET has no insight into the fact that traffic is happening on port 1.  so switching it back to the right place, or somehow handling that would be useful.

**Comment by Bairdo** [comment]
+1

> Is your intent, that packets are always output to port 48, but that FAUCET should know how to switch packets destined back there?

This is something I have been thinking would be good for the authentication app, except the rule would have match fields.

**Comment by anarkiwi** [comment]
OK, looks like I need to let the forwarding manager logic know explicitly it's OK to learn hosts on a port and provision null entries for them. Looks like that is a circa 1.5 coffee problem, so we may make it into today's release.

**Comment by anarkiwi** [comment]
OK, check out https://github.com/faucetsdn/faucet/pull/1784.

We'd like very much to keep the ACLs stateless. So the right ultimate solution for this is a post-learning pipeline ACL (basically to allow an ACL that can do post processing before the packet exits the standard pipeline). To do that there's some more intrusive refactoring to be done (planning to do that in the future anyway, to allow for example unused tables not to be provisioned which would save resources).

However this feature still lets you override with existing ACLs, just by default get both learning (and other hosts can send traffic back unicast, you just override the output direction).

What do you think?
