### ISSUE TITLE
log location of config file read on startup

### ISSUE THREAD

**Issue by shivarammysore** [faucetsdn/faucet#1789]
It would be good to have a informational log message as to which config file was loaded - ex. 

```
loaded /etc/ryu/ryu.conf
loaded /etc/faucet/faucet.yaml

```
etc.  This would greatly help in debugging ...

**Comment by gizmoguy** [comment]
In #1790 I have made faucet log which configuration file it is going to use on startup.

It is more difficult to log the ryu configuration file used as ryu handles this and not us, perhaps starting faucet with the --verbose flag will cause ryu to tell you what configuration file it loaded?

**Comment by shivarammysore** [comment]
Thanks Brad.  Totally understandable and makes perfect sense.  But, if we
are loading ryu.conf in /etc/faucet - which is "our" version, then it may
make sense to log it.

**Comment by gizmoguy** [comment]
Hi Shivaram, to clarify: I can't reliably log the ryu config as ultimately it's up to ryu to decide if it loads the argument I pass it or not.

**Comment by shivarammysore** [comment]
Ok - thanks.

**Comment by gizmoguy** [comment]
Further clarification on faucet's behaviour, after #1787 assuming the file /etc/faucet/ryu.conf exists (and you haven't overriden the path) faucet will always pass this configuration file to ryu-manager no matter how you started faucet

**Comment by shivarammysore** [comment]
Excellent clarification.

Thanks
