### ISSUE TITLE
Optimize bootup time of faucet/faucet-test docker

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#1888]
In addition to installing all our requirements in faucet/faucet-test we should prime the faucet/faucet-testbase docker with these requirements.

This will involve changing the build context of the faucet/faucet-testbase docker from /docker/base/ to /

**Comment by gizmoguy** [comment]
#1901 makes this more difficult than just changing build context.

I think we need to git checkout faucet during build process, install dependencies from requirements.txt then delete the checked out source code.

**Comment by anarkiwi** [comment]
Fixed by https://github.com/faucetsdn/faucet/pull/2054. The tests can now use the host's pip cache (which they do under Travis now), and when selected, pytype and pylint are now run in parallel.
