### ISSUE TITLE
Resolving ACL actions is tricky

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#1934]
Say we have an ACL like the following and apply it to a bunch of DPs:

>     nfv_dns:
>         # Force DNS to our DNS server
>         - rule:
>             dl_type: 0x800      # ipv4
>             nw_proto: 17        # udp
>             udp_dst: 53         # dns
>             actions:
>                 output:
>                     set_fields:
>                         eth_dst: "72:b8:3c:4c:dc:4d"
>                     port: 5 # s1 container

Resolving an ACL is a delicate process because not all DPs may be equal (some may have a port 5, others not). At the moment the set_field will always resolve so faucet will push this ACL to every DP without error, regardless of if there is a port 5 or not.

It gets worse than this as depending on which DP we use to resolve the ACL we may not successfully resolve the port number and we will push a broken ACL to all DPs.

Ideally what we want:

 * resolve ACL on each DP individually
 * only push ACL if all actions can be successfully resolved
 * produce error to log when things go wrong

**Comment by anarkiwi** [comment]
Fixed in https://github.com/faucetsdn/faucet/pull/1935.
