### ISSUE TITLE
vlan_vids documentation

### ISSUE THREAD

**Issue by shivarammysore** [faucetsdn/faucet#2175]
`vlan_vids` definition is documented as:

`list of [ integer or { integer, eth_type } ]`

Shouldn't this be documented as:

`list of [ integer or { vid:integer, eth_type: hex  } ]`

**Comment by gizmoguy** [comment]
Maybe more accurately?:

`list of [ vlan_vid or { vlan_vid, eth_type } ]`

**Comment by shivarammysore** [comment]
Examples in tests include "vid" and "eth_type" prefixes.  

https://github.com/faucetsdn/faucet/blob/master/tests/unit/test_config.py#L1580
https://github.com/faucetsdn/faucet/blob/master/tests/integration/mininet_tests.py#L3675
https://github.com/faucetsdn/faucet/blob/master/tests/integration/mininet_tests.py#L3622

/Shivaram
::Sent from my mobile device::

**Comment by gizmoguy** [comment]
Okay yeah from looking at this our configuration documentation it does need a bit of work, I have done some tidy in #2177 but part of #1897 I will endeavour to give it a much bigger cleanup

**Comment by shivarammysore** [comment]
Thanks Brad :-)

**Comment by shivarammysore** [comment]
FYI - I am sure you will address this later but noting this so that we
don't forget.
In the fix
https://github.com/faucetsdn/faucet/pull/2177/files#diff-eead337ed57b42e703fe8f51dc925c61R856

- list of [ vid or { vid, eth_type } ]

There is a explicit prefix "vid:" or "eth_type:" in the examples.  I think
this probably needs to be captured.

Thanks

**Comment by gizmoguy** [comment]
Oh right, sorry I misunderstood before. Corrected in #2177

**Comment by shivarammysore** [comment]
Perfect.  Thanks!

**Comment by jorgeclarck** [comment]
I was search on google related to Faucet, when I found https://faucet.ly/, If you want to create faucet for your website? then, you should visit this site for the same!
