### ISSUE TITLE
We shouldn't skip test_fuzz_controller() in the integration tests

### ISSUE THREAD

**Issue by lantz** [faucetsdn/faucet#2321]
Currently we're skipping the ICMPv6 version of `test_fuzz_controller()` in the integration tests, because it times out on travis (seems to be shard 2?)

We should figure out what is wrong and fix it if possible.

**Comment by lantz** [comment]
In my testing so far, it seems that `scapy` is getting really slow at some point, taking about 1 second per packet send. I'm not sure why that is.... is it a `scapy` problem or a mininet problem? Are we running out of entropy in the container?

**Comment by lantz** [comment]
I'm beginning to suspect that `scapy` itself is just getting really slow. I wrote a shell script that called `scapy` and ran it in the test environment and it also eventually got really slow.

**Comment by cglewis** [comment]
As a datapoint, I’ve experienced slowness and massive overuse of memory (including leaking) when using scapy for other things in the past (mostly analyzing packets and sessions), fwiw.

**Comment by lantz** [comment]
The weird thing is that we're running a separate `scapy` command for each test so memory leaks shouldn't be an issue.

**Comment by lantz** [comment]
I created a branch `fuzz-test-debug` for investigating this:

https://github.com/lantz/faucet/tree/fuzz-test-debug
https://travis-ci.org/lantz/faucet/builds

**Comment by lantz** [comment]
It seems a bit unpredictable. This test passed:
https://travis-ci.org/lantz/faucet/jobs/419482658

**Comment by lantz** [comment]
It seems we can at least do the first 12 tests consistently though, so that is something to think about...

**Comment by lantz** [comment]
@anarkiwi Have we seen any freezes or slowdowns since #2332 was merged and since #2330 was fixed in 054871d?

**Comment by anarkiwi** [comment]
Looks like it's fixed - I haven't seen any problems triggering a build, every 30m. Right, the TCP port busy is a workaround - we try to reserve ports, but of course we can't stop another process taking that source port, so we retry with another. 

Nice job!

**Comment by lantz** [comment]
Great, thanks!
