### ISSUE TITLE
Fix reliance on pip internal methods

### ISSUE THREAD

**Issue by KitL** [faucetsdn/faucet#2371]
https://github.com/faucetsdn/faucet/pull/2369 is a bit of a short term hack. We have no reason to think that pip wont change this interface without any notice. It would be better to have another way to deal with this.

**Comment by gizmoguy** [comment]
Pip's view on this is that they "do not provide a public API" and probably never will. Here is the NEWS file that relates to moving the methods to _internal:

https://github.com/pypa/pip/blob/95bcf8c5f6394298035a7332c441868f3b0169f4/news/4696.removal

And the bug where they state they have no plans to add one:

https://github.com/pypa/pip/issues/3121#issuecomment-290585892
