### ISSUE TITLE
Sunset python2 support

### ISSUE THREAD

**Issue by KitL** [faucetsdn/faucet#2372]
eg. https://github.com/faucetsdn/faucet/blob/1fd928a7eed637a3109ab591df460181e1cdf283/faucet/acl.py#L127

We convert this into a list unnecessarily so that the types are consistent between python 2 and 3. Now that we have deprecated python 2 we should not do this sort of thing.

**Comment by lantz** [comment]
As I understand it, Python 2's `iteritems()` provided an iterator over a snapshot of the collection, while Python 3's `items()` iterator doesn't, so using `list(x.items())` is the conservative replacement for `iteritems()` and that is what `2to3` uses. Usually it isn't necessary, however, since most loops over a collection don't add or delete items in the loop body.

**Comment by gizmoguy** [comment]
Reopening because we haven't added ``python_requires='>=3.4'`` to setup.cfg or setup.py yet.

**Comment by gizmoguy** [comment]
pip versions < 9.0 ignore python_requires so we should explicitly check the python version inside faucet and abort when running on python 2

```
import sys

if sys.version_info < (3,):
    raise ImportError(
    """You are running Frobulator 6.0 on Python 2

Frobulator 6.0 and above are no longer compatible with Python 2, and you still 
ended up with this version installed. That's unfortunate; sorry about that. 
It should not have happened. Make sure you have pip >= 9.0 to avoid this kind 
of issue, as well as setuptools >= 24.2:

 $ pip install pip setuptools --upgrade

Your choices:

- Upgrade to Python 3.

- Install an older version of Frobulator:

 $ pip install 'frobulator<6.0'

It would be great if you can figure out how this version ended up being
installed, and try to check how to prevent that for future users.

See the following URL for more up-to-date information:

https://i.am.an/url

""")


```

**Comment by lantz** [comment]
Ah, good point! Interesting about ‘pip’ - I guess adding it to the setup params is more useful for clarity or documentation.

**Comment by lantz** [comment]
Haha victory!
