### ISSUE TITLE
override_output_port

### ISSUE THREAD

**Issue by KitL** [faucetsdn/faucet#2448]
I am looking at tidying up the eth_src table.

The override_output_port option is a bit of a nuisance for this. It was created in response to https://github.com/faucetsdn/faucet/issues/1754
But it only affects layer 2 packets at the moment, which seems like not what was asked for. Since no one has noticed that I am wondering how much anyone is actually using this function?
@cglewis @Bairdo you guys said you were interested in this.

To make this work properly, we need a second extra table (I am already adding a table to move most of the eth_src stuff into). Or we can wait until we add egress ACLs (I actually do plan on adding these next or next-ish) when this kind of thing becomes a bit less haxy.

So how important is this functionality? Is it worth adding an extra table for?

**Comment by cglewis** [comment]
I admittedly haven't used this feature very often, but it was handy the few times I have.  So I'm not sure it's necessarily important enough for an extra table.

**Comment by anarkiwi** [comment]
There is a generic L2 tunnel facility available now (even works between endpoints on the same DP).

Shall we remove this old override feature in favor of tunnelling?
