### ISSUE TITLE
TRAVIS_COMMIT_RANGE is empty on the first commit on a new branch

### ISSUE THREAD

**Issue by byllyfish** [faucetsdn/faucet#2578]
When I pushed the table_config_tuple branch to github, my personal travis-ci build finished rather quickly. :)

It turns out it wasn't running any tests because TRAVIS_COMMIT_RANGE is empty. (I don't know why it thinks AUTHORS is in the list of file changes.) Maybe, all files could be considered changed?

https://travis-ci.org/byllyfish/faucet/jobs/440359334
```
$ ./run-travis-test.sh
TRAVIS_COMMIT_RANGE:
TRAVIS_COMMIT: 2cb1f4832dedd1ddaaea4d4819533e6f93f6a686
files changed: AUTHORS
no python source changed, not running docker tests.
```

The faucetsdn travis-ci.com build did the right thing when I submitted the pull request.

https://travis-ci.com/faucetsdn/faucet/jobs/151313090
```
$ ./run-travis-test.sh
TRAVIS_COMMIT_RANGE: 97996ed6cc97fd62ee701f21af1e35555272d4ee...2cb1f4832dedd1ddaaea4d4819533e6f93f6a686
TRAVIS_COMMIT: 0bf3d0b167b59ac5ebdd35b9c1278f0ba6590804
files changed: faucet/dp.py
```

In the zof port, rebasing leads to a different issue with TRAVIS_COMMIT_RANGE; the `git diff --name-only` fails. Again, this is only in the personal repo.

https://travis-ci.org/byllyfish/faucet/jobs/440293433
```
$ ./run-travis-test.sh
TRAVIS_COMMIT_RANGE: d5079079101a...aa1c5638642b
TRAVIS_COMMIT: aa1c5638642b1be2b1cd629cafa5d8c3f451eb29
fatal: ambiguous argument 'd5079079101a...aa1c5638642b': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'd5079079101a...aa1c5638642b': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
no files changed.
no python source changed, not running docker tests.
```

**Comment by anarkiwi** [comment]
OK... looks like the giff diff needs an explicit branch too (since of course the default is master).

**Comment by anarkiwi** [comment]
Fixed by https://github.com/faucetsdn/faucet/pull/2586

**Comment by anarkiwi** [comment]
More like, https://github.com/faucetsdn/faucet/pull/2602.
