### ISSUE TITLE
Faucet - UDP Forwarding

### ISSUE THREAD

**Issue by goonerboy6661** [faucetsdn/faucet#2650]
Is it possible to add UDP forwarding/Directed Broadcast to Faucet?

I would like to change an all host Subnet Broadcast (for instance 192.168.1.255/24 to 10.1.1.255/24 then to 192.168.1.255/24 to 172.16.1.255/24) and then forward out to the different VLANs (including the original VLAN)

This would be very useful as some IOT devices use a protocol know as BACNet. Bacnet discovers devices by sending out a udp:47808 all IP subnet Broadcast. This feature would also help sending other protocols such as DHCP server requests to multiple servers on different IP subnets.

I guess similar to tradidinal UDP forwarding/IP-Helper or even fallback bridging going way back.

Thanks

**Comment by gizmoguy** [comment]
After lots of internal discussions on this we think this feature is better served by an external service rather than faucet directly. Closing as wontfix for now unless someone comes up with a good idea on how to implement this in faucet.
