### ISSUE TITLE
Which tests to run to qualify a new switch?

### ISSUE THREAD

**Issue by antoninbas** [faucetsdn/faucet#2713]
If a vendor is interested in qualifying an OpenFlow switch for the Faucet pipeline, what are the steps that can be taken to run the Faucet system tests?
Everything I find in the repo seems to assume Mininet & OVS (https://github.com/faucetsdn/faucet/blob/master/docker/runtests.sh#L92).
Thanks!

**Comment by antoninbas** [comment]
I was able to find this: https://github.com/faucetsdn/faucet/blob/master/docs/testing.rst
Looks like I just need to provide the correct YAML config for my switch. I'm still unsure as to why "modprobe openvswitch" is required to run the HW version of the test suite?

**Comment by gizmoguy** [comment]
Hi @antoninbas,

There is a nicer rendered version of that documentation page here:

https://docs.faucet.nz/en/latest/testing.html#hardware-switch-testing-with-docker

I believe the openvswitch kernel module is required as we still use openvswitch on the test host to bridge virtual hosts onto the real switch to generate test packets.

Please feel to reach out directly to my email (brad@waikato.ac.nz) for any additional help I can provide in helping you qualify your devices.

A good tip is to first run the sanity test by itself to verify your hardware test environment is properly set up, once this is passing you can remove the "-e FAUCET_TESTS" option to run the entire test suite which will take over an hour to complete:

```
sudo docker run --privileged --net=host \
    -v $HOME/.cache/pip:/var/tmp/pip-cache \
    -v /etc/faucet:/etc/faucet \
    -v /var/tmp:/var/tmp \
    -e FAUCET_TESTS="FaucetSanityTest" \
    -ti faucet/tests
```

**Comment by antoninbas** [comment]
I forgot to get back to you, my apologies. Thanks for your help, I was able to run the "FaucetSanityTest"!

**Comment by gizmoguy** [comment]
Great to hear @antoninbas, if you get stuck trying to interpret test case failures my email is always open and I'm always happy to help!
