### ISSUE TITLE
flood actions generated for inactive output ports

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#2756]
If I have ports that are configured but not active (port down), flood logic still generates output actions for them. Specifically, my open-flow table looks like the following, even though, e.g., port 23 is down/unconnected.

 cookie=0x5adc15c0, duration=2.445s, table=4, n_packets=0, n_bytes=0, idle_age=27, priority=8216,dl_vlan=10,dl_dst=01:00:5e:00:00:00/ff:ff:ff:00:00:00 actions=output:1,strip_vlan,output:10,output:11,output:12,output:13,output:20,output:21,output:22,output:23,output:30,output:31,output:32,output:33,output:40,output:41,output:42,output:43,output:50,output:51,output:52,output:53,output:60,output:61,output:62,output:63,output:70,output:71,output:72,output:73,output:80,output:81,output:82,output:83,output:90,output:91,output:92,output:93,output:1000

**Comment by anarkiwi** [comment]
Fixed by https://github.com/faucetsdn/faucet/pull/2755, https://github.com/faucetsdn/faucet/pull/2773 et al.
