### ISSUE TITLE
FaucetSingleStackStringOfDPTaggedTest and start_faucet.sh timeout

### ISSUE THREAD

**Issue by byllyfish** [faucetsdn/faucet#2800]
As an FYI, the FaucetSingleStackStringOfDPTaggedTest seems to take more than 5 minutes to run in the latest Faucet. The integration tests start Faucet and Gauge using the unix `timeout` command with a timeout of 5 minutes, so the controllers are actually exiting before the test finishes.  This doesn't affect the result of the test.

Is there a reason for the controllers to be run under a timeout? (MAX_CTL_TIME=300)

https://github.com/faucetsdn/faucet/blob/c51e7c719e2ded0ada8aeae12514c81524d62f6c/clib/mininet_test_topo.py#L361-L370

Thanks.

**Comment by anarkiwi** [comment]
The timeout is there as a garbage collection measure. 300s is a long time, so will take a look at making that shorter. Tests overall are becoming significant time and resource problems and fixing that is part of a larger body of work.

**Comment by anarkiwi** [comment]
Fixed by https://github.com/faucetsdn/faucet/pull/2837.
