### ISSUE TITLE
Slow port up/down activities, performance regression

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#2809]
Issue was fixed previously, but then re-introduced by [this change](https://github.com/faucetsdn/faucet/commit/fa6cd55275fb211b4837f1c9228ccfb89c478fbb#diff-42797d9a122f45aca3f612a22b31a9d4L150). Core problem is O(n^2) calculation with the number of ports involved.

The check got moved, but the logic changed. It used to be:

` if not port.hairpin or not port.dyn_phys_up:`

which would be inverted to:

` if port.hairpin and port.dyn_phys_up:`

but the new (inverted) code is:

` if port.hairpin or port.dyn_phys_up`

Which means it ends up doing a lot of (unnecessary) calculations. Discussion was that this also needed a proper unit test (although I'm unsure how that would manifest itself).

**Comment by anarkiwi** [comment]
The test would test the problematic behavior (ie that flood rule calculation is too expensive/needs too many flows), not the implementation detailas. Will get to this when I can.

**Comment by anarkiwi** [comment]
Fixed by https://github.com/faucetsdn/faucet/pull/2853.

I improved config reload performance about 5x avoiding some unnecessary stringification, and added a profile based unit test that ensures reload time stays under 1s.

**Comment by anarkiwi** [comment]
Please reopen if not fixed - I believe config reload performance has significantly improved (as of today the change is in master).
