### ISSUE TITLE
802.1X controlled ACLs

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#2832]
We would like to be able to specify an ACL list, to be applied to a port in access-accept (just as we can configure an ACL list to a port directly).

**Comment by gizmoguy** [comment]
#2703 mostly does this, just needs a few updates to work against new chewie and faucet

**Comment by Bairdo** [comment]
@anarkiwi do you mean returning the ACL name via some RADIUS attribute e.g. filter-id?
Or the general success ACL that #2703 implements?

**Comment by anarkiwi** [comment]
Return the ACL name(s).

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/54b34c07d14509a637fde86dcb6b98ae575cfc95 et al.
