### ISSUE TITLE
Port is not recovered after Faucet8021XPortFlapTest

### ISSUE THREAD

**Issue by gunnelkantola** [faucetsdn/faucet#2836]
We use 1.8.35 and 1.8.36. When running the test case Faucet8021XPortFlapTest, it is successful, but when you check the port status afterwards, the port is still down and you have to manually put it up. 
In the logs, we can see the following:

Mar 05 14:56:55	DPID 147058196485 (0x223d5a0005) port 25 down
Mar 05 14:57:10	DPID 147058196485 (0x223d5a0005) port 25 down
Mar 05 14:57:13	DPID 147058196485 (0x223d5a0005) port 25 up
Mar 05 14:57:48	DPID 147058196485 (0x223d5a0005) port 25 down

Mar 05 14:56:23 faucet.valve INFO     DPID 147058196485 (0x223d5a0005) faucet-1 L2 learned 06:08:7b:c7:11:1c (L2 type 0x0806, L3 src 10.0.0.1, L3 dst 10.0.0.3) Port 25 VLAN 100  (3 hosts total)
Mar 05 14:56:23 faucet INFO     Logoff from MAC 06:08:7b:c7:11:1c on Port 25
Mar 05 14:56:55 faucet.valve INFO     DPID 147058196485 (0x223d5a0005) faucet-1 Port 25 up status False reason MODIFY state 1
Mar 05 14:56:55 faucet.valve INFO     DPID 147058196485 (0x223d5a0005) faucet-1 Port 25 (b25) down
Mar 05 14:56:55 faucet INFO     Logoff from MAC 06:08:7b:c7:11:1c on Port 25
Mar 05 14:57:10 faucet.valve INFO     DPID 147058196485 (0x223d5a0005) faucet-1 Port 25 up status False reason MODIFY state 1
Mar 05 14:57:10 faucet.valve INFO     DPID 147058196485 (0x223d5a0005) faucet-1 Port 25 (b25) down
Mar 05 14:57:10 faucet INFO     Logoff from MAC 06:08:7b:c7:11:1c on Port 25
Mar 05 14:57:13 faucet.valve INFO     DPID 147058196485 (0x223d5a0005) faucet-1 Port 25 up status True reason MODIFY state 4
Mar 05 14:57:13 faucet.valve INFO     DPID 147058196485 (0x223d5a0005) faucet-1 Port 25 (b25) up
Mar 05 14:57:16 faucet INFO     Successful auth from MAC 06:08:7b:c7:11:1c on Port 25
Mar 05 14:57:17 faucet.valve INFO     DPID 147058196485 (0x223d5a0005) faucet-1 L2 learned 06:08:7b:c7:11:1c (L2 type 0x0806, L3 src 10.0.0.1, L3 dst 10.0.0.3) Port 25 VLAN 100  (4 hosts total)
Mar 05 14:57:17 faucet INFO     Logoff from MAC 06:08:7b:c7:11:1c on Port 25
Mar 05 14:57:48 faucet.valve INFO     DPID 147058196485 (0x223d5a0005) faucet-1 Port 25 up status False reason MODIFY state 1
Mar 05 14:57:48 faucet.valve INFO     DPID 147058196485 (0x223d5a0005) faucet-1 Port 25 (b25) down
Mar 05 14:57:48 faucet INFO     Logoff from MAC 06:08:7b:c7:11:1c on Port 25

And in the mininet_tests.py we see the following:

class Faucet8021XPortFlapTest(Faucet8021XSuccessTest):

    RADIUS_PORT = 1880

    def test_untagged(self):
        port_no1 = self.port_map['port_1']
        port_labels1 = self.port_labels(port_no1)
        expected_successes = 0

        for _ in range(2):
            expected_successes += 1

            self.set_port_up(port_no1)
            self.wait_8021x_flows(port_no1)
            tcpdump_txt_1 = self.retry_8021x(
                self.eapol1_host, port_no1, self.wpasupplicant_conf_1, and_logoff=True)
            self.assertIn('Success', tcpdump_txt_1)
            self.assertIn('logoff', tcpdump_txt_1)
            self.assertEqual(
                expected_successes,
                self.scrape_prometheus_var('port_dot1x_success_total', labels=port_labels1, default=0))

            self.set_port_down(port_no1)
            self.try_8021x(
                self.eapol1_host, port_no1, self.wpasupplicant_conf_1, and_logoff=False)
            self.one_ipv4_ping(
                self.eapol1_host, self.nfv_host,
                require_host_learned=False, expected_result=False)
            wpa_status = self.get_wpa_status(self.eapol1_host, self.get_wpa_ctrl_path(self.eapol1_host))
            self.assertNotEqual('SUCCESS', wpa_status)

Is it supposed to put the port UP and then DOWN? 
Many thanks!

**Comment by anarkiwi** [comment]
You shouldn't have to manually put it up - the tests automatically send port up for each port, when the test starts.

Are you seeing tests fail for some reason on 1.8.36? If so please let us know how to reproduce it.

**Comment by gunnelkantola** [comment]
We are seeing it on 1.8.35 and 1.8.36 (have not checked older versions). The test case is passing, so you don't see it if you are running all the tests, or multiple test cases, as I guess in many test cases the port is set to up in the beginning (?). But if you execute only this particular test case, Faucet8021XPortFlapTest, you will see that after it has been executed and passed, the port is still down. And this can cause problems, if you run only single test cases...
I run it like this:
docker run --privileged --net=host -v $HOME/.cache/pip:/var/tmp/pip-cache -v $HOME/etc/faucet:/etc/faucet -v $HOME/var/tmp:/var/tmp -e FAUCET_TESTS="-ki Faucet8021XPortFlapTest" -ti faucet/1.8.36

Please, let me know if you need any logs.
Thank you for your help!

**Comment by anarkiwi** [comment]
So you are right, it does leave the port down at the end of the test.

But, it shouldn't cause a problem, because as above it always set port up at the beginning of a test, no matter whether you run all the tests, a subset, or just one. That's because we want to ensure that every test starts with a clean slate. 

Does this actually cause any problem (like a test to fail)? Please feel free to reopen with more detail if it causes an actual problem.
