### ISSUE TITLE
MAB support in 802.1x module

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#2839]
Needed for some IoT environments.

**Comment by MichaelWasher** [comment]
Should this be moved to Chewie?

**Comment by grafnu** [comment]
Looks like I already did with https://github.com/faucetsdn/chewie/issues/114

**Comment by grafnu** [comment]
Already an existing Issue as part of Chewie https://github.com/faucetsdn/chewie/issues/114
