### ISSUE TITLE
SequenceMatcher exception in ryu log

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#2843]
When running faucet/ryu with the --verbose flag for verbose console logging, I see the following exception on the console log. See below for a snippet, and a [complete log is available](https://travis-ci.org/grafnu/daq/jobs/503987630#L5663).  As far as I can tell, this happens every time the Faucet EventReconfigure event happens.  There's no consistent behavior in the [Faucet logs](https://travis-ci.org/grafnu/daq/jobs/503987630#L6031) that a I can see, but I think it's the cause of numerous ["connection closed by peer" messages in the OVS logs](https://travis-ci.org/grafnu/daq/jobs/503987630#L6731). This _might_ be the cause of a fatal Faucet problem, which I'll be posting shortly -- but this problem (SequenceMatcher error) happens every time, while that is only intermittent.

```
EVENT Faucet->Faucet EventReconfigure
EVENT ofp_event->dpset EventOFPStateChange
tried SequenceMatcher but got error
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/datadiff/__init__.py", line 202, in try_diff_seq
    return diff_seq(a, b, context, depth, fromfile=fromfile, tofile=tofile)
  File "/usr/lib/python3.6/site-packages/datadiff/__init__.py", line 211, in diff_seq
    raise NotSequence("Not a sequence %s" % type(a))
datadiff.NotSequence: Not a sequence <class 'faucet.dp.DP'>
tried SequenceMatcher but got error
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/datadiff/__init__.py", line 202, in try_diff_seq
    return diff_seq(a, b, context, depth, fromfile=fromfile, tofile=tofile)
  File "/usr/lib/python3.6/site-packages/datadiff/__init__.py", line 211, in diff_seq
    raise NotSequence("Not a sequence %s" % type(a))
datadiff.NotSequence: Not a sequence <class 'faucet.port.Port'>
DPSET: unregister datapath <ryu.controller.controller.Datapath object at 0x7f6fdebb13c8>
EVENT dpset->Faucet EventDP
```

**Comment by anarkiwi** [comment]
I have so far failed to reproduce this because I don't have the configs that cause the problem (your logs are helpful to guess it's related to trying to produce a diff for a port that has ACL and DP references, but that's it).

Please if you would be able to provide the "killer" configs that would allow us to fix it.

In the meantime https://github.com/faucetsdn/faucet/pull/2845 addresses the symptom.

**Comment by anarkiwi** [comment]
The symptom is taken care of in 2845, but we won't know the root cause until configs are supplied in the other bug.

**Comment by grafnu** [comment]
I do not think this is fixed... I'm still seeing an exception in the RYU
logs. However, I can confirm that it's just a noisy symptom that is not
causing any actual problem.
