### ISSUE TITLE
How-to Guide needed for --observe-links & gui_topology.py in Faucet

### ISSUE THREAD

**Issue by 42Network** [faucetsdn/faucet#2925]
I would like to use the Ryu gui_topology.py graphical topology viewer, but it is not clear how enable it with faucet.

It seem that putting "--observe-links" on the ExecStart line in the /lib/systemd/system/faucet.service causes faucet to not start. I was able to put "--ryu-app=ryu.app.gui_topology.gui_topology" there and the topology viewer is present on :8080, but there are no links, just switches.

**Comment by anarkiwi** [comment]
Unfortunately we don't support other Ryu modules with FAUCET (FAUCET assumes it is the only control function loaded, so it won't deal with another module attempting to do for example topology discovery ).
