### ISSUE TITLE
looped IGMP packets sometimes observed on non-root switch

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#3029]
On the non-root switch, many copies of:

11:09:34.708365 00:76:86:2c:ea:80 > 01:00:5e:00:00:01, ethertype IPv4 (0x0800), length 60: (tos 0xc0, ttl 1, id 0, offset 0, flags [none], proto IGMP (2), length 32, options (RA))
    172.20.1.139 > 224.0.0.1: igmp query v2

Are observed. The host originating the packet is on the root switch.

FAUCET does not log a host port move, so the bug must be in flood rule construction.

**Comment by anarkiwi** [comment]
Switch configs:

root:
            18:
                name: "port1.0.18"
                description: "ex4300-stack trunk-b"
                tagged_vlans: [redcables,redcables6]
                lacp: 2
                lldp_beacon:
                    enable: True
                acls_in: [lldp_allow, protect_from_access, default_allow]
            19:
                name: "port1.0.19"
                description: "at-x510-3 trunk-b"
                receive_lldp: True
                lldp_beacon:
                    enable: True
                stack:
                    dp: at-x510-3
                    port: 22
                acls_in: [lldp_allow, protect_from_access, default_allow]

non-root:

            22:
                name: "port1.0.22"
                description: "at-x510-3 trunk-b"
                receive_lldp: True
                lldp_beacon:
                    enable: True
                stack:
                    dp: at-x930-1
                    port: 19
                acls_in: [lldp_allow, protect_from_core, default_allow]
            23:
                name: "port1.0.23"
                description: "at-x510-3 trunk-a"
                receive_lldp: True
                lldp_beacon:
                    enable: True
                stack:
                    dp: at-x930-1
                    port: 20
                acls_in: [lldp_allow, protect_from_core, default_allow]

**Comment by anarkiwi** [comment]
The non-root switch has a missing flood rule - it should have one both in_port=18 and 19. The missing rule would cause a packet to go to the default flood rule which would propagate back tot he non-root.

faucet@faucet:~/tmp$ grep 01:00:5e:00:00:00 root.txt |grep in_port=18
faucet@faucet:~/tmp$ grep 01:00:5e:00:00:00 root.txt |grep in_port=19
table_id=5, duration=60349s, n_packets=0, n_bytes=0, priority=8217,in_port=19,dl_vlan=99,dl_dst=01:00:5e:00:00:00/ff:ff:ff:00:00:00,actions=output:21,output:9,output:10,output:11,output:24,pop_vlan,output:15
table_id=5, duration=60349s, n_packets=19928, n_bytes=1280903, priority=8217,in_port=19,dl_vlan=250,dl_dst=01:00:5e:00:00:00/ff:ff:ff:00:00:00,actions=output:21,output:5,output:6,output:9,output:10,output:11,output:12,
table_id=5, duration=60349s, n_packets=0, n_bytes=0, priority=8217,in_port=19,dl_vlan=251,dl_dst=01:00:5e:00:00:00/ff:ff:ff:00:00:00,actions=output:21,output:5,output:6,output:9,output:10,output:11,output:23,output:24
table_id=5, duration=60349s, n_packets=0, n_bytes=0, priority=8217,in_port=19,dl_vlan=252,dl_dst=01:00:5e:00:00:00/ff:ff:ff:00:00:00,actions=output:21,output:24
table_id=5, duration=60348s, n_packets=0, n_bytes=0, priority=8217,in_port=19,dl_vlan=253,dl_dst=01:00:5e:00:00:00/ff:ff:ff:00:00:00,actions=output:21,output:24,pop_vlan,output:1
table_id=5, duration=60348s, n_packets=0, n_bytes=0, priority=8217,in_port=19,dl_vlan=97,dl_dst=01:00:5e:00:00:00/ff:ff:ff:00:00:00,actions=output:21,pop_vlan,output:22

**Comment by anarkiwi** [comment]
Actually it's not missing a flood rule, I got the wrong stacking ports.

The problem turned out to be unwanted hybrid mode IGMP flooding.

no ip igmp snooping 

On the DP fixed the problem.

**Comment by rahul217** [comment]
Thanks for isolating this issue Josh.
We will be patching it up in the next official software release.
