### ISSUE TITLE
On DOT1X_EXPECTED_EVENTS failure, the mininet test crashes and does not output all of the debug information

### ISSUE THREAD

**Issue by MichaelWasher** [faucetsdn/faucet#3087]
On DOT1X_EXPECTED_EVENTS failure, the mininet test crashes and does not output all of the debug information. 
Look in mininet_tests.py, will need a try-catch somewhere there.

**Comment by MichaelWasher** [comment]
How would you prefer to resolve this? Here's two alternatives; to me they both don't seem very clean but I don't know of a cleaner way to do it.
@gizmoguy 
https://github.com/MichaelWasher/faucet/tree/issue_3087
https://github.com/MichaelWasher/faucet/tree/issue_3087_alternate

**Comment by MichaelWasher** [comment]
(ignore the typos it's just for an idea.)

**Comment by gizmoguy** [comment]
I prefer d4adb3698436fe7980f870a8a9c33ab16c2f4ff6

**Comment by MichaelWasher** [comment]
https://github.com/faucetsdn/faucet/pull/3096

**Comment by MichaelWasher** [comment]
@gizmoguy Can you close this
