### ISSUE TITLE
Software switch testing with docker doesn't work as documented

### ISSUE THREAD

**Issue by lantz** [faucetsdn/faucet#3093]
https://docs.faucet.nz/en/latest/testing.html#software-switch-testing-with-docker says:

> You can build and run the mininet tests with the following commands:
> ```
> sudo docker build --pull -t faucet/tests -f Dockerfile.tests .
> sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.tcpdump
> sudo modprobe openvswitch
> sudo docker run --sysctl net.ipv6.conf.all.disable_ipv6=0 --privileged --rm \
>                 -v /var/local/lib/docker:/var/lib/docker \
>                 -v /tmp/faucet-pip-cache:/var/tmp/pip-cache \
>                 -ti faucet/tests
> ```

With the current master, this produces:

```
Using pip cache
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0d052297b8>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/chewie/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0d05229630>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/chewie/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0d05239240>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/chewie/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0d05239b70>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/chewie/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f0d052395c0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)': /simple/chewie/
...
```

**Comment by MichaelWasher** [comment]
Have you tried removing the /tmp/faucet-pip-cache folder from your local machine. This may be corrupt. 

I just build the docker image from source on master and it worked fine for me. Also, try jumping into your docker container and checking the network connectivity.
I saw a bug recently with docker not getting IP addresses inside the container, had to restart Docker.

try: 
sudo docker run --sysctl net.ipv6.conf.all.disable_ipv6=0 --privileged --rm \
                -v /var/local/lib/docker:/var/lib/docker \
                -v /tmp/faucet-pip-cache:/var/tmp/pip-cache \
                -ti faucet/tests bash -c "ip addr show"

**Comment by lantz** [comment]
It seems fine:

```
718: eth0@if719: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:acff:fe11:2/64 scope link tentative 
       valid_lft forever preferred_lft forever
```

Did you try the exact command(s) from above?

**Comment by gizmoguy** [comment]
Hi @lantz 

This appears to be all working for me right now:

```
brad@nix/50:/tmp/faucet$ sudo docker run --sysctl net.ipv6.conf.all.disable_ipv6=0 --privileged --rm \
>                 -v /var/local/lib/docker:/var/lib/docker \
>                 -v /tmp/faucet-pip-cache:/var/tmp/pip-cache \
>                 -e "-i FaucetSanityTest" -ti faucet/tests  
Using pip cache
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache -r /faucet-src/test-requirements.txt has exit status 0
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache -r /faucet-src/fuzz-requirements.txt has exit status 0
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache -r /faucet-src/docs/requirements.txt has exit status 0
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache -r /faucet-src/adapters/vendors/rabbitmq/requirements.txt has exit status 0
```

From your logs it seems to indicate your docker was having trouble resolving the DNS for pypi (so either they were having an outage when you tried this or your docker host isn't set up quite right).

If you want to keep debugging try the following command:

sudo docker run --sysctl net.ipv6.conf.all.disable_ipv6=0 -ti faucet/tests bash -c "ping pypi.python.org"

What we should see is that we can resolve pypi.python.org and that we get ICMP responses from this domain, if we don't see those then your docker host may need some network changes to allow the containers to reach the internet.

**Comment by anarkiwi** [comment]
Please re-open if still a problem.
