### ISSUE TITLE
periodic re-auth test flake with aaa_eap_resp is true. but data is false. This should never happen

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#3098]
======================================================================
FAIL: mininet_tests.Faucet8021XPeriodicReauthTest.test_untagged (subunit.RemotedTestCase)
mininet_tests.Faucet8021XPeriodicReauthTest.test_untagged
----------------------------------------------------------------------
testtools.testresult.real._StringException: Traceback (most recent call last):
  File "/faucet-src/tests/integration/mininet_tests.py", line 844, in test_untagged
    self.assertEquals(expected_total, total, msg='failed to successfully re-auth')
  File "/usr/lib/python3.6/unittest/case.py", line 1321, in deprecated_func
    return original_func(*args, **kwargs)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 2 != 1 : failed to successfully re-auth

Jul 13 00:49:57 faucet.Chewie INFO     running job reauth_port (MacAddress.from_string("ea:a3:42:98:8f:a6"), '00:00:00:00:00:07')
Jul 13 00:49:57 faucet.Chewie INFO     reauthenticating src_mac: ea:a3:42:98:8f:a6 on port: 00:00:00:00:00:07
Jul 13 00:49:57 faucet.Chewie INFO     sending premptive on port 00:00:00:00:00:07
Jul 13 00:49:57 faucet.Chewie INFO     running job event (<chewie.event.EventSessionTimeout object at 0x7fb3eaf80fd0>,)
Jul 13 00:49:57 faucet.Chewie.SM - port: 00:00:00:00:00:07, client: ea:a3:42:98:8f:a6 INFO     full state machine received event: <chewie.event.EventSessionTimeout object at 0x7fb3eaf80fd0>
Jul 13 00:49:57 faucet.Chewie.SM - port: 00:00:00:00:00:07, client: ea:a3:42:98:8f:a6 INFO     Entering logoff2_state
Jul 13 00:49:57 faucet.Chewie.SM - port: 00:00:00:00:00:07, client: ea:a3:42:98:8f:a6 INFO     end state: LOGOFF2
Jul 13 00:49:57 faucet.Chewie.SM - port: 00:00:00:00:00:07, client: ea:a3:42:98:8f:a6 INFO     client is logging off ea:a3:42:98:8f:a6
Jul 13 00:49:57 faucet INFO     Logoff from MAC ea:a3:42:98:8f:a6 on 7
Jul 13 00:49:57 faucet.Chewie INFO     Sending message 'IdentityMessage': src_mac: '01:80:c2:00:00:03', id: '0', code: '1', identity: '' from 00:00:00:00:00:07 to 01:80:c2:00:00:03
Jul 13 00:49:57 faucet.Chewie INFO     Received packed_message: b'\x00\x00\x00\x00\x00\x07\xea\xa3B\x98\x8f\xa6\x88\x8e\x01\x00\x00\t\x02\x00\x00\t\x01user'
Jul 13 00:49:57 faucet.Chewie INFO     Received eap message: 'IdentityMessage': src_mac: 'ea:a3:42:98:8f:a6', id: '0', code: '2', identity: 'user'
Jul 13 00:49:57 faucet.Chewie INFO     eap EAP(): 'IdentityMessage': src_mac: 'ea:a3:42:98:8f:a6', id: '0', code: '2', identity: 'user'
Jul 13 00:49:57 faucet.Chewie INFO     Port based state machines are as follows: {'ea:a3:42:98:8f:a6': <chewie.state_machines.eap_state_machine.FullEAPStateMachine object at 0x7fb3e7d25c50>}
Jul 13 00:49:57 faucet.Chewie DEBUG    eap packet is response to chewie initiated authentication
Jul 13 00:49:57 faucet.Chewie.SM - port: 00:00:00:00:00:07, client: ea:a3:42:98:8f:a6 INFO     Resetting eap due to received response to preemtive request
Jul 13 00:49:57 faucet.Chewie.SM - port: 00:00:00:00:00:07, client: ea:a3:42:98:8f:a6 INFO     full state machine received event: EventPreemptiveEAPResponseMessageReceived("'IdentityMessage': src_mac: 'ea:a3:42:98:8f:a6', id: '0', code: '2', identity: 'user'", "00:00:00:00:00:07")
Jul 13 00:49:57 faucet.Chewie.SM - port: 00:00:00:00:00:07, client: ea:a3:42:98:8f:a6 INFO     type: <class 'chewie.message_parser.IdentityMessage'>, message 'IdentityMessage': src_mac: 'ea:a3:42:98:8f:a6', id: '0', code: '2', identity: 'user' 
Jul 13 00:49:57 faucet.Chewie.SM - port: 00:00:00:00:00:07, client: ea:a3:42:98:8f:a6 INFO     Entering initialize_state
Jul 13 00:49:57 faucet.Chewie.SM - port: 00:00:00:00:00:07, client: ea:a3:42:98:8f:a6 INFO     Entering select_action_state
Jul 13 00:49:57 faucet.Chewie.SM - port: 00:00:00:00:00:07, client: ea:a3:42:98:8f:a6 INFO     Entering initialize_passthrough_state
Jul 13 00:49:57 faucet.Chewie.SM - port: 00:00:00:00:00:07, client: ea:a3:42:98:8f:a6 INFO     Entering aaa_idle_state
Jul 13 00:49:57 faucet.Chewie.SM - port: 00:00:00:00:00:07, client: ea:a3:42:98:8f:a6 INFO     end state: AAA_IDLE
Jul 13 00:49:57 faucet.Chewie.SM - port: 00:00:00:00:00:07, client: ea:a3:42:98:8f:a6 ERROR    aaa_eap_resp is true. but data is false. This should never happen

**Comment by MichaelWasher** [comment]
Was this running on your local machine or in Travis? Is there a way to access the logs / dumps from this? I've been trying to get it to fail on my machine with no luck.

**Comment by MichaelWasher** [comment]
Looks like the state machine replays the current state that it's in when it receives an event but doesn't change state.
Doesn't go into the right state when receiving a response to a preemptive requests that we send. 

Normally EapolStartMessage is first but it is IdentityMessage on preemptive
https://github.com/faucetsdn/chewie/blob/0703e718be4ef3d56e9847d779ba79cb616251ad/chewie/state_machines/eap_state_machine.py#L885-L890

I'll look into it more this weekend / next week.

**Comment by anarkiwi** [comment]
Still a problem with .49 - appears to happen when the reauth has ID 0.
Aug 25 06:26:36 faucet.Chewie DEBUG    port is active not sending on port 00:00:00:00:00:0c
Aug 25 06:26:36 faucet.Chewie INFO     Sending message 'IdentityMessage': src_mac: '01:80:c2:00:00:03', id: '127', code: '1', identity: '' from 00:00:
00:00:00:0b to 01:80:c2:00:00:03
Aug 25 06:26:46 faucet.Chewie INFO     running job reauth_port (MacAddress.from_string("aa:60:35:22:b1:68"), '00:00:00:00:00:0c')
Aug 25 06:26:46 faucet.Chewie INFO     reauthenticating src_mac: aa:60:35:22:b1:68 on port: 00:00:00:00:00:0c
Aug 25 06:26:46 faucet.Chewie INFO     sending premptive on port 00:00:00:00:00:0c
Aug 25 06:26:46 faucet.Chewie INFO     running job event (<chewie.event.EventSessionTimeout object at 0x7f2b68e67278>,)
Aug 25 06:26:46 faucet.Chewie.SM - port: 00:00:00:00:00:0c, client: aa:60:35:22:b1:68 INFO     full state machine received event: <chewie.event.EventS
essionTimeout object at 0x7f2b68e67278>
Aug 25 06:26:46 faucet.Chewie.SM - port: 00:00:00:00:00:0c, client: aa:60:35:22:b1:68 INFO     Entering logoff2_state
Aug 25 06:26:46 faucet.Chewie.SM - port: 00:00:00:00:00:0c, client: aa:60:35:22:b1:68 INFO     end state: LOGOFF2
Aug 25 06:26:46 faucet.Chewie.SM - port: 00:00:00:00:00:0c, client: aa:60:35:22:b1:68 INFO     client is logging off aa:60:35:22:b1:68
Aug 25 06:26:46 faucet INFO     Logoff from MAC aa:60:35:22:b1:68 on 12
Aug 25 06:26:46 faucet.Chewie INFO     Sending message 'IdentityMessage': src_mac: '01:80:c2:00:00:03', id: '0', code: '1', identity: '' from 00:00:00
:00:00:0c to 01:80:c2:00:00:03
Aug 25 06:26:46 faucet.Chewie INFO     Received packed_message: b'\x00\x00\x00\x00\x00\x0c\xaa`5"\xb1h\x88\x8e\x01\x00\x00\t\x02\x00\x00\t\x01user'
Aug 25 06:26:46 faucet.Chewie INFO     Received eap message: 'IdentityMessage': src_mac: 'aa:60:35:22:b1:68', id: '0', code: '2', identity: 'user'
Aug 25 06:26:46 faucet.Chewie INFO     eap EAP(): 'IdentityMessage': src_mac: 'aa:60:35:22:b1:68', id: '0', code: '2', identity: 'user'
Aug 25 06:26:46 faucet.Chewie INFO     Port based state machines are as follows: {'aa:60:35:22:b1:68': <chewie.state_machines.eap_state_machine.FullEA
PStateMachine object at 0x7f2b65a52080>}
Aug 25 06:26:46 faucet.Chewie DEBUG    eap packet is response to chewie initiated authentication
Aug 25 06:26:46 faucet.Chewie.SM - port: 00:00:00:00:00:0c, client: aa:60:35:22:b1:68 INFO     Resetting eap due to received response to preemtive req
uest
Aug 25 06:26:46 faucet.Chewie.SM - port: 00:00:00:00:00:0c, client: aa:60:35:22:b1:68 INFO     full state machine received event: EventPreemptiveEAPRe
sponseMessageReceived("'IdentityMessage': src_mac: 'aa:60:35:22:b1:68', id: '0', code: '2', identity: 'user'", "00:00:00:00:00:0c")
Aug 25 06:26:46 faucet.Chewie.SM - port: 00:00:00:00:00:0c, client: aa:60:35:22:b1:68 INFO     type: <class 'chewie.message_parser.IdentityMessage'>, 
message 'IdentityMessage': src_mac: 'aa:60:35:22:b1:68', id: '0', code: '2', identity: 'user' 
Aug 25 06:26:46 faucet.Chewie.SM - port: 00:00:00:00:00:0c, client: aa:60:35:22:b1:68 INFO     Entering initialize_state
Aug 25 06:26:46 faucet.Chewie.SM - port: 00:00:00:00:00:0c, client: aa:60:35:22:b1:68 INFO     Entering select_action_state
Aug 25 06:26:46 faucet.Chewie.SM - port: 00:00:00:00:00:0c, client: aa:60:35:22:b1:68 INFO     Entering initialize_passthrough_state
Aug 25 06:26:46 faucet.Chewie.SM - port: 00:00:00:00:00:0c, client: aa:60:35:22:b1:68 INFO     Entering aaa_idle_state
Aug 25 06:26:46 faucet.Chewie.SM - port: 00:00:00:00:00:0c, client: aa:60:35:22:b1:68 INFO     end state: AAA_IDLE
Aug 25 06:26:46 faucet.Chewie.SM - port: 00:00:00:00:00:0c, client: aa:60:35:22:b1:68 ERROR    aaa_eap_resp is true. but data is false. This should ne
ver happen
Aug 25 06:26:46 faucet.Chewie INFO     waiting for eap.
Aug 25 06:27:00 faucet.valve WARNING  DPID 4213520433 (0xfb253831) faucet-1 datapath down
Aug 25 06:27:00 faucet.valve INFO     DPID 4213520433 (0xfb253831) faucet-1 Port 10 (b10) down
Aug 25 06:27:00 faucet.valve INFO     DPID 4213520433 (0xfb253831) faucet-1 Port 11 (b11) down
Aug 25 06:27:00 faucet.valve INFO     DPID 4213520433 (0xfb253831) faucet-1 Port 12 (b12) down
Aug 25 06:27:00 faucet.Chewie.SM - port: 00:00:00:00:00:0c, client: aa:60:35:22:b1:68 INFO     full state machine received event: <chewie.event.EventP
ortStatusChange object at 0x7f2b659c1cc0>
Aug 25 06:27:00 faucet.Chewie.SM - port: 00:00:00:00:00:0c, client: aa:60:35:22:b1:68 INFO     Entering disabled_state
Aug 25 06:27:00 faucet.Chewie.SM - port: 00:00:00:00:00:0c, client: aa:60:35:22:b1:68 INFO     Entering disabled_state
Aug 25 06:27:00 faucet.Chewie.SM - port: 00:00:00:00:00:0c, client: aa:60:35:22:b1:68 INFO     end state: DISABLED
Aug 25 06:27:00 faucet.valve INFO     DPID 4213520433 (0xfb253831) faucet-1 Port 9 (b9) down
