### ISSUE TITLE
Single Dockerfile for both Faucet and Gauge

### ISSUE THREAD

**Issue by shivarammysore** [faucetsdn/faucet#3210]
Currently we use different Dockerfiles for Faucet and Gauge with 2 specific differences - `EXPOSE` ports and `CMD`.

In this proposal, I suggest we use a start script for `CMD` - say `faucet`. This script can be something like:

```
#!/bin/bash
case $1 in
    "faucet") python3 faucet --ofp-tcp-listen-port=6653 ...
     ;;
    "gauge") python3 gauge --ofp-tcp-listen-port=6654 ...
    ;;
   *) echo "$0 [faucet|gauge|check-faucet-config]"
esac
```

If `faucet` container is started with `--volumes`, then, for `gauge` we can use `--volumes-from=faucet` so that same directories can be loaded.

With the above method, we are building only one image as compared to 2.  On the disk, we store only one image.

**Comment by gizmoguy** [comment]
If the end goal is to save on disk space when both faucet and gauge image files are loaded on the same docker host, isn't the smarter option to just simply create a new intermediate docker image that both faucet/faucet and faucet/gauge inherit from?

**Comment by shivarammysore** [comment]
It is my opinion that anytime a docker image is built privately, we are
only increasing complexity.  The current model of using faucet and gauge as
2 different containers (each of 189MB size) is only from a microservices
perspective.  The suggestion made by me does not stay away from
microservice architecture model.  It greatly helps a IT operator in terms
of management.  Some examples include:

   1. Only file to upgrade a container from one version to another.
   2. Reduce download bandwidth as we are downloading only one time as
   compared to twice.
   3. By using the --volumes-from one can make sure that the same
   faucet.yaml files are loaded by both faucet & gauge - at in a co-located
   use case.

Basic goal of my suggestion is for simplification of trying to think which
container to download and how to manage.  An IT operator has 100s of
container images to manage.  Faucet/Gauge are one of the many pieces in a
microservice deployment.

Another ideal goal is to make it like a Nginx
<https://hub.docker.com/_/nginx> container which has same version tag, but
with a platform post-fixed to the name.

Thanks

**Comment by gizmoguy** [comment]
I'm not sure I fully understand your recommendation or what you want to change. Perhaps a full PR showing what you want to do might help?

I notice you say you are building the faucet dockers privately, if that's the case feel free to use whatever Dockerfiles you want to generate your own images. The Dockerfiles in the git repo are for generating our public images on dockerhub.

Also I believe my suggestion will solve your 3 points in a simpler way, due the the way docker image layers work.

**Comment by shivarammysore** [comment]
My suggestion is similar to what OVS does -
https://github.com/openvswitch/ovs/blob/master/utilities/docker/start-ovs

My suggestion was only to help simplify Faucet use and deployment.  Our
infrastructure is built differently.

**Comment by gizmoguy** [comment]
Okay I understand now with that example from OVS.

I think I'm still against this option as it would require us changing documentation and would break the commands people already run to start faucet and gauge.

I will leave this ticket open to track implementing my solution (use same base image for faucet/gauge dockers), I can't currently implement it as our docker build CI isn't smart enough to support dependency ordering, but the new one we'll be switching to (#3230) will let us do this easily.

Thanks for the suggestion!

**Comment by shivarammysore** [comment]
Sounds like a good plan.

**Comment by gizmoguy** [comment]
We should move to docker buildx for our docker image builds which will allow us to build images in multiple archs which will let us remove the various docker-compose-pi.yaml files we have in our repo.
