### ISSUE TITLE
When multi DP routing on stacking, FAUCET router can't resolve hosts on non-root DPs (because route resolver doesn't flood to stack ports)

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#3227]
See also.

https://github.com/faucetsdn/faucet/pull/3226

**Comment by gizmoguy** [comment]
Problem is likely due to _resolve_gw_on_vlan() in valve_route.py not knowing about stack links.

Can look at the following function for examples on using stack links for broadcast:

valve_flood.py
  edge_dp_for_host()
  _flood_actions()
