### ISSUE TITLE
Event socket connection doesn't timeout for subsequent connections after first connection times out

### ISSUE THREAD

**Issue by anurag6** [faucetsdn/faucet#3288]
I am using a simple client program to connect to the faucet event socket(Please find the py script attached). I use socket.shutdown and socket.close to close the socket on the client side. The first time, the server gets a broken pip exception and breaks the connection after some time. However subsequent connections don't time out even after closing the client side. 

This means that owing to the single client rule, no new connections are accepted. Please let me know if I am missing something here.

As a sidenote, is there a reason why faucet insists on enforcing a single client connection for the event socket?
[test_sock.py.zip](https://github.com/faucetsdn/faucet/files/3728628/test_sock.py.zip)

**Comment by cglewis** [comment]
@anurag6 see this issue for the reasons behind enforcing a single client connection: https://github.com/faucetsdn/faucet/issues/1312
