### ISSUE TITLE
of_port missing

### ISSUE THREAD

**Issue by jhughesbiot** [faucetsdn/faucet#3300]
of_port is mentioned in examples for configuring external hardware but is not a valid configurable property.  Attempting to validate the example config file (https://docs.faucet.nz/en/latest/vendors/ovs/faucet_testing_with_OVS_on_hardware.html#faucet-configuration-file) always is met with errors of unknown properties.  Simlarly, attempting to add of_port into a valid dp configuration section is also met with unknown property errors.

Has of_port been removed and replaced with a different property to define the control plane port?

**Comment by anarkiwi** [comment]
The example config file cited above is for the test suite, not FAUCET.

If you want to change the port on which FAUCET listens, use the CLI option:

faucet@faucet:~/faucet$ faucet --help
usage: faucet [-h] [--gauge] [-v] [-V] [--use-stderr] [--use-syslog]

  --ryu-ofp-ssl-listen-port RYU_OFP_SSL_LISTEN_PORT
                        openflow ssl listen port (default: 6653)
