### ISSUE TITLE
Prevent against egress packets being looped back into Faucet

### ISSUE THREAD

**Issue by grafnu** [faucetsdn/faucet#3302]
Since STP is not part of Faucet, if lacp/LAG is not in use, an externally broadcast packet (e.g. ARP) on a loop_protect_external port might be looped back in through another loop_protect_external port, which then gets broadcast back out the originating port. This results in the sending device receiving a reflected copy of its own broadcast packet, which would be bad.

Brad and I discussed this, and the thought was to make incoming packets on a loop_protect_external port dropped (make port down) on any non-root switch. So, only the stacking root would receive packets.

This was originally mentioned as part of https://github.com/faucetsdn/faucet/issues/3285 but we decided that solution was a "bad idea" and this would be better.

**Comment by anarkiwi** [comment]
See https://github.com/faucetsdn/faucet/pull/3371 et al.
