### ISSUE TITLE
Root Stack Exchange conditions can cause network to break

### ISSUE THREAD

**Issue by snak1219** [faucetsdn/faucet#3326]
Currently the root stack exchange is enacted if one of the following 3 cases are hit.

1.) If the current root itself is down and loses connection to controller
2.) If all stack ports are down and there are no healthy stackport connections
3.) If all lacp connections go down

No problem here:
![74455576_2356629964666423_3131084373428797440_n](https://user-images.githubusercontent.com/22568590/68152106-d8409880-fef7-11e9-8c29-ac1144af217e.jpg)

Now there is no problem with this but if for example, if we want to have lacp connections from the _stackroot_ to another stack root or one if its _stack edges_, the lacp will work but no stack exchanges will occur unless we actually bring down the datapath (case 1) or take down all links of the stack (case 2). 

![75369281_2500097756746087_4878530889123889152_n](https://user-images.githubusercontent.com/22568590/68151414-83505280-fef6-11e9-8a7d-31f3d06bf20a.jpg)

As a result, it causes the network to be in a broken state where all other _stack roots_ will not accept any external traffic but the _stack root_ itself is also disconnected from the network. 

Broken Network state as below.

![76609868_417130502306321_7413455574026682368_n](https://user-images.githubusercontent.com/22568590/68151424-88ad9d00-fef6-11e9-94e5-bdca8384b6e8.jpg)

**Comment by anarkiwi** [comment]
We think we have addressed this in master; would you be able to try?

https://github.com/faucetsdn/faucet/commit/8ec27066650a638b25ad4966269f501c62d48554

**Comment by snak1219** [comment]
Yes, so https://github.com/faucetsdn/faucet/commit/8ec27066650a638b25ad4966269f501c62d48554 handles case 2,  _if all stack ports are down and there are no healthy stackport connections_ . 

But you can see in the third diagram above that all the **stackports** are still up but the switch that is disconnected from the **external network** is still the active root so I believe this is a separate issue from what https://github.com/faucetsdn/faucet/commit/8ec27066650a638b25ad4966269f501c62d48554  fixes.

**Comment by snak1219** [comment]
Seeing https://github.com/faucetsdn/faucet/issues/3332 is intended, this is no longer an issue. Thanks Josh.
