### ISSUE TITLE
Remote coprocessor port support

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#3329]
We now have coprocessor support in faucet, see the dev blog for an explanation of how that works:

https://www.vandervecken.com/faucet/index.php/2019/10/31/injecting-services-into-the-dataplane-with-coprocessing/

What what be a nice next step is to be able to have "remote" coprocessor ports on a faucet stack and use something like stack tunnelling to get packets from A->B and B->A.

**Comment by anarkiwi** [comment]
This almost works with existing features, but there are some existing tunneling bugs.

1. You cannot have two rules in the same ACL that output to the same tunnel (config checker claims tunnel has been multiply defined).
2. Tunneling silently enables the vlan-acl table. The vlan-acl table on an allow goes to eth_src. If vlan-acl is present the copro table gotos vlan-acl, so eth_src tries to learn copro'd eth_srcs from the copro NFV port (incorrect)

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/pull/3590 fixes 1.

2 is outstanding.
