### ISSUE TITLE
Setting LACP on stack_ports doesn't pass config parser after v1.9.20

### ISSUE THREAD

**Issue by snak1219** [faucetsdn/faucet#3332]
Is this intended? Noticed https://github.com/faucetsdn/faucet/commit/503ddd10f9d9038c3368734b7baff363d5e33bd5 adds a config check which no longer allows you to aggregate stacked ports. (Other non_native vlan ports). This makes sense when dealing with other special ports such as **output_only** or **mirror** or **coprocessor port**, which the commit was intended to handle I believe.

`root_top:
     dp_id: 0x0000001122334455
     hardware: Allied-Telesis
     stack:
       priority: 2
     interfaces:
       2:
         stack:
           dp: root_middle
           port: 2
         lacp: 2
         lacp_active: true`

Now returns the following configError

`[InvalidConfigError('DP root_top: Cannot have VLAN option lacp: 2 on non-VLAN port Port 2',)]`

If this is intended, then I'll take it that faucet no longer supports aggregatable stack links so https://github.com/faucetsdn/faucet/issues/3326 also won't be an issue.

**Comment by snak1219** [comment]
So v1.9.20 allows aggregatable stack links but all releases after does not.

**Comment by anarkiwi** [comment]
This is intended behavior (LACP and stack cannot coexist on the same ports). You can add multiple stack links between DPs which accomplishes redundancy.
