### ISSUE TITLE
ValveFloodStackManagerReflection can't handle adding Non-FAUCET Network to stack_edge connected to another stack_edge

### ISSUE THREAD

**Issue by snak1219** [faucetsdn/faucet#3333]
We know currently that the following works as tested at  plugfest.

![74830690_2342745792652728_288425165803487232_n](https://user-images.githubusercontent.com/22568590/68245970-c2e96e00-ffcc-11e9-9c25-2dbed18b3d1b.jpg)

Adding an external network to the above diagram has no problems because all stack_edges are connected to the current stack root. The above diagram simplified would look like this :
![72971156_422478242034400_8135450301017620480_n](https://user-images.githubusercontent.com/22568590/68246324-6a66a080-ffcd-11e9-950d-ab07f8b707d9.jpg)

However, if you want to deploy multi-root stack, like the following diagram, current faucet flooding can't handle it.

![74415309_1421758567972437_9168860341998714880_n](https://user-images.githubusercontent.com/22568590/68246074-f3c9a300-ffcc-11e9-8e7b-653e112557f4.jpg)

The above diagram can be simplified into the following, where the **root candidate** becomes an edge in between the **current root** and the **bottom edge**. 

![74830690_2342745792652728_288425165803487232_n](https://user-images.githubusercontent.com/22568590/68246432-9d109900-ffcd-11e9-80b1-376281e87517.jpg)

If people want to add a L2 switch at the edge level for instance, this can be a major problem. 

So follow up to https://github.com/faucetsdn/faucet/commit/498ea0803fa81023dd0297ede669effa65425422

**Comment by anarkiwi** [comment]
Confirmed fixed.
