### ISSUE TITLE
faucet in docker can't connect to physical switch without host network

### ISSUE THREAD

**Issue by jhughesbiot** [faucetsdn/faucet#3337]
No matter what kind of network or port mapping I have attempted, the only way I can get faucet running in docker to connect to a physical open flow switch is to attach it to the host network.  Is there an undocumented procedure to get docker to connect to physical devices?  Additional flags? Settings? etc.

**Comment by cglewis** [comment]
How are you starting Faucet with Docker?  The easiest way is using `docker-compose` since there's already a provided `docker-compose.yml` file in the repo that specifies all of the needed flags that are necessary. Once the containers spin up, Faucet will be available on the host port 6653 (at the IP of the host), which is what you would point your physical switch to for the controller.

**Comment by jhughesbiot** [comment]
I had both built faucet from the official instructions directly and used docker-compose from this repo and setup all services including dashboards (just never had data). Modifying the network on faucet to use 

> network_mode: host 

to get it to communicate to the physical switch.  I just confirmed some port settings on my switch and realized it had gotten changed from 6653.  Not sure how it managed to find the new port when using the host network since it's not defined anywhere but it did.  Once I changed the port to match in the mapping that got the control of the switch without network host and one of the dashboards has data now.  Not sure why the port statistics doesn't have anything but that seems like a separate matter.

**Comment by gizmoguy** [comment]
We don't expect that you have to run docker in host networking mode to connect a switch.

Documentation on how to run faucet with docker is here: https://docs.faucet.nz/en/latest/installation.html#starting-dockers

But, it sounds like from your latest comment you worked out your issue so I'll close this now.
