### ISSUE TITLE
Removing/Changing port description causes faucet to cold start config

### ISSUE THREAD

**Issue by tweippert** [faucetsdn/faucet#3345]
I just do a simple test with faucet where i only remove/change a description of an port (single port) and the change triggers a cold start of the config. 

root@faucet01:~# faucet --version
Faucet 1.9.23

Attached are faucet.yaml before and after change, logfile and my setup file to recreate the lab, also a network.dot file for visualization of a single DP setup.

In a stack scenario, this causes also a cold start of "all" stack members (tested with only 2).

regards, 
tim

[remove-description.zip](https://github.com/faucetsdn/faucet/files/3858361/remove-description.zip)

**Comment by anarkiwi** [comment]
At the moment, FAUCET only warm starts in a few situations where we are confident we can (e.g. ACL, and only the ACL, changed on a port). If we're not sure we just cold start to be safe. There are lots of other possibilities where it could warm start, but I'd like to put some test coverage in first to make sure we get all the corner cases. We have another chunk of related work (generative topology testing) which I'd like to expand to include warm starts.

To set expectations addressing all this will likely take a while.
