### ISSUE TITLE
Faucet always cold restarts when a "router" is defined

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#3347]
From @mwutzke:

> If I remove the routers section, I no longer get the cold start operation - I get the expected warm start operation, for a simple port name change.
> 
> I suspect the issue is in this logic:
> 
> >        elif new_dp.routers != self.routers:
> >            logger.info('DP routers config changed - requires cold start')
> 
> I *think* - need to check, that a 'deep' compare needs to be used - but I've not verified that.

Possibly related to #3345

**Comment by mwutzke** [comment]
The vip_map_by_ipv attribute of faucet.Router contains PyTricia objects, and the 'str' representation of these objects renders the 'id()' of the object. eg:

```
 "('vip_map_by_ipv', OrderedDict([(4, <pytricia.PyTricia object at 0x7fc30da8cf50>), (6, <pytricia.PyTricia object at 0x7fc30da8ce90>)]))"
```

As such the 'hash' will be different for 2 logically identical objects, resulting in the 'router config changed' path being executed.
