### ISSUE TITLE
Faucet Port Statistics dashboard only shows 'no data'

### ISSUE THREAD

**Issue by cglewis** [faucetsdn/faucet#3401]
https://docs.faucet.nz/en/latest/_static/grafana-dashboards/faucet_port_statistics.json

I'm guessing some of the prometheus variables changed?

**Comment by gizmoguy** [comment]
Works for me using faucet version 1.9.28, grafana version 6.5.2 and prometheus version 2.14.0.

Any additional information you can supply about your environment that will help me track this down?

**Comment by cglewis** [comment]
I’m running:

Faucet: 1.9.28
Prometheus: 2.15.1
Grafana: 6.5.2

Maybe Prometheus broke something that I missed. Will be curious if you can reproduce with that version. If not, I’ll see if I goofed something up somehow.

**Comment by gizmoguy** [comment]
Also works for me under Prometheus 2.15.1.

Do the ``Datapath Name`` and ``Port`` drop downs populate with your switches and ports?

**Comment by gizmoguy** [comment]
Not reproducible right now, re-open if you can find a reproduction case.

**Comment by pryanwong** [comment]
I am working with:
Faucet 1.9.51
Prometheus: 2.15.2+ds
Grafana: 7.2.1

I can see the inventory of the mininet network, on the inventory screen.
I cannot see any of the port statistics.
The dropdown, in Datapath, does not have any options and only shows 'none'.
If I force 'sw1' in the datapath box, I will see the hosts as options in the Ports dropdown.
I do not see any port data in Prometheus/Grafana.

I am generating traffic through iPerf, and I can see the dataflow created in the Faucet logs.

Any advice?  I will see if I collect statistics directly through RYU and try to see where the data is lost.

**Comment by StrikerNZL** [comment]
am having the same issue with 
Grafana10.1
Prometheus  2.31.2+ds1  
Faucet 1.10.8

Followed the instructions as per the faucet.nz website for the installation.. it worked the very first time but had to reinstall the 22.04..

it doesn't list anything in the datapath or port dropdowns...

i am using the JSON from the faucet,nz docs website

**Comment by gizmoguy** [comment]
Do you have the faucet prometheus recording rules added to your prometheus config file?

This is the `faucet.rules.yml` file, prometheus must be restarted to enable the recording rules.

Documentation is here:

https://docs.faucet.nz/en/latest/tutorials/first_time.html#configure-prometheus

**Comment by StrikerNZL** [comment]
yes, I do have the recording rules in place....  well if they are in the documentation I do anyway as I literally went through it step by step..  I just checked thu the configs following the steps again and it all matches..

**Comment by gizmoguy** [comment]
Just ran through the faucet tutorial on a fresh ubuntu 22.04 box and everything works fine for me:

![Screenshot_20230920_111940](https://github.com/faucetsdn/faucet/assets/383287/90f62d77-57e5-4128-8596-c47034cc27aa)

Make sure the `of_port_rx_bytes` query works in prometheus, if it doesn't work that means you have the prometheus configuration wrong:

![Screenshot_20230920_111955](https://github.com/faucetsdn/faucet/assets/383287/effd5dfc-4e4c-4795-a18b-fdfb6667b8d3)
