### ISSUE TITLE
Faucet 1.9.31 FaucetSanityTest.test_untagged failed due to missing gauge-state.txt

### ISSUE THREAD

**Issue by ejietia** [faucetsdn/faucet#3443]
est results
============
---
mininet_tests.FaucetSanityTest.test_untagged:
  output: "Traceback (most recent call last):\t  File '/faucet-src/tests/integration/mininet_tests.py',\
    \ line 162, in test_untagged\t    self.gauge_smoke_test()\t  File '/faucet-src/clib/mininet_test_base.py',\
    \ line 1407, in gauge_smoke_test\t    missing_watcher_files, set(), msg='Gauge\
    \ missing logs: %s' % missing_watcher_files)\tAssertionError: Items in the first\
    \ set but not the second:\t'/var/tmp/faucet-tests-bjjzxtgj/FaucetSanityTest-test_untagged/gauge-state.txt'\t\
    '/var/tmp/faucet-tests-bjjzxtgj/FaucetSanityTest-test_untagged/gauge-ports.txt'\
    \ : Gauge missing logs: {'/var/tmp/faucet-tests-bjjzxtgj/FaucetSanityTest-test_untagged/gauge-state.txt',\
    \ '/var/tmp/faucet-tests-bjjzxtgj/FaucetSanityTest-test_untagged/gauge-ports.txt'}\t"
  status: FAIL
  test_duration_secs: 120
...
[faucet-tests-bjjzxtgj.tar.gz](https://github.com/faucetsdn/faucet/files/4140203/faucet-tests-bjjzxtgj.tar.gz)

**Comment by anarkiwi** [comment]
It looks like the test was run on the old code?

josh@vek-x:~/Downloads/faucet-tests-bjjzxtgj/FaucetSanityTest-test_untagged$ grep ver faucet-prometheus.log 
python_info{implementation="CPython",major="3",minor="6",patchlevel="9",version="3.6.9"} 1.0
# HELP faucet_pbr_version Faucet PBR version
# TYPE faucet_pbr_version gauge
**faucet_pbr_version{version="1.9.30"} 1.0**
faucet_valve_service_secs_bucket{dp_id="0x1",dp_name="faucet-1",le="0.0001",valve_service="advertise"} 4.0
faucet_valve_service_secs_bucket{dp_id="0x1",dp_name="faucet-1",le="0.001",valve_service="advertise"} 4.0
faucet_valve_service_secs_bucket{dp_id="0x1",dp_name="faucet-1",le="0.01",valve_service="advertise"} 4.0
faucet_valve_service_secs_bucket{dp_id="0x1",dp_name="faucet-1",le="0.1",valve_service="advertise"} 4.0
faucet_valve_service_secs_bucket{dp_id="0x1",dp_name="faucet-1",le="1.0",valve_service="advertise"} 4.0
faucet_valve_service_secs_bucket{dp_id="0x1",dp_name="faucet-1",le="+Inf",valve_service="advertise"} 4.0
faucet_valve_service_secs_count{dp_id="0x1",dp_name="faucet-1",valve_service="advertise"} 4.0
faucet_valve_service_secs_sum{dp_id="0x1",dp_name="faucet-1",valve_service="advertise"} 2.7663976652547717e-05
faucet_valve_service_secs_bucket{dp_id="0x1",dp_name="faucet-1",le="0.0001",valve_service="fast_advertise"} 8.0
faucet_valve_service_secs_bucket{dp_id="0x1",dp_name="faucet-1",le="0.001",valve_service="fast_advertise"} 8.0
faucet_valve_service_secs_bucket{dp_id="0x1",dp_name="faucet-1",le="0.01",valve_service="fast_advertise"} 8.0
faucet_valve_service_secs_bucket{dp_id="0x1",dp_name="faucet-1",le="0.1",valve_service="fast_advertise"} 8.0
faucet_valve_service_secs_bucket{dp_id="0x1",dp_name="faucet-1",le="1.0",valve_service="fast_advertise"} 8.0
faucet_valve_service_secs_bucket{dp_id="0x1",dp_name="faucet-1",le="+Inf",valve_service="fast_advertise"} 8.0
faucet_valve_service_secs_count{dp_id="0x1",dp_name="faucet-1",valve_service="fast_advertise"} 8.0
faucet_valve_service_secs_sum{dp_id="0x1",dp_name="faucet-1",valve_service="fast_advertise"} 0.00010471296263858676
faucet_valve_service_secs_created{dp_id="0x1",dp_name="faucet-1",valve_service="advertise"} 1.5804830850370758e+09
faucet_valve_service_secs_created{dp_id="0x1",dp_name="faucet-1",valve_service="fast_advertise"} 1.5804830850371697e+09
josh@vek-x:~/Downloads/faucet-tests-bjjzxtgj/FaucetSanityTest-test_untagged$
