### ISSUE TITLE
docker-compose.yaml not working on Windows 10

### ISSUE THREAD

**Issue by pryanwong** [faucetsdn/faucet#3462]
I tried installing Faucet using Docker and the docker-compose.yaml file.

I received the following error when I executed "docker-compose up"

Creating docker_prometheus_1 ... error

ERROR: for docker_prometheus_1  Cannot start service prometheus: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/c/Users/seanferenci/OneDrive - IS5Communications Inc/Documents/Coursera/SDN/Docker/etc/prometheus/prometheus-docker-compose.yml\\\" to rootfs \\\"/var/lib/docker/overlay2/642bdde0cb86966463c601037e0cbc65153fabbb06388b03bbdd43761fb91e9b/merged\\\" at \\\"/var/lib/docker/overlay2/642bdde0cb86966463c601037e0cbc65153fabbb06388b03bbdd43761fb91e9b/merged/etc/prometheus/prometheus.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for prometheus  Cannot start service prometheus: OCI runtime create failed: container_linux.go:346: starting container process caused "process_linux.go:449: container init caused \"rootfs_linux.go:58: mounting \\\"/host_mnt/c/Users/seanferenci/OneDrive - IS5Communications Inc/Documents/Coursera/SDN/Docker/etc/prometheus/prometheus-docker-compose.yml\\\" to rootfs \\\"/var/lib/docker/overlay2/642bdde0cb86966463c601037e0cbc65153fabbb06388b03bbdd43761fb91e9b/merged\\\" at \\\"/var/lib/docker/overlay2/642bdde0cb86966463c601037e0cbc65153fabbb06388b03bbdd43761fb91e9b/merged/etc/prometheus/prometheus.yml\\\" caused \\\"not a directory\\\"\"": unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.

**Comment by cglewis** [comment]
Hi @pryanwong,

I’m not entirely sure this would work on Windows, but the error your encountering is a mounting issue with docker. You can override the default root path by adding the environment variable FAUCET_PREFIX. That how you can get around mounting issues on OS X at least. Not sure if this will cover Windows, but worth a try.

**Comment by pryanwong** [comment]
I think I may have it working.  I rewrote the docker-compose.yml, Prometheus portion, as follows:

prometheus:
        restart: always
        image: 'prom/prometheus:v2.15.2'
        user: 'root'
        ports:
            - '9090:9090'
        volumes:
            - '/opt/prometheus:/c/tmp/prometheus'
            - '/opt/prometheus/prometheus-docker-compose.yml:/c/tmp/prometheus.yml'
            - '/opt/prometheus/faucet.rules.yml:/c/prometheus/faucet.rules.yml'
        links:
            - faucet
            - gauge

I moved prometheus.yml into my c:\tmp folder.  The service launches.  I will test it out later today.  Thanks for your help.

**Comment by pryanwong** [comment]
I was not able to wire all of the docker instances together.  I switched to Vagrant/Ubuntu and installed successfully on Windows 10.
