### ISSUE TITLE
Faucet 1.9.33 FaucetSanityTest.test_untagged failed due to missing gauge-state.txt

### ISSUE THREAD

**Issue by ejietia** [faucetsdn/faucet#3472]
It seems that #3443 comes back on 1.9.33

FAIL: test_untagged (mininet_tests.FaucetSanityTest)
All hosts on the same untagged VLAN should have connectivity.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/faucet-src/tests/integration/mininet_tests.py", line 162, in test_untagged
    self.gauge_smoke_test()
  File "/faucet-src/clib/mininet_test_base.py", line 1371, in gauge_smoke_test
    missing_watcher_files, set(), msg='Gauge missing logs: %s' % missing_watcher_files)
AssertionError: Items in the first set but not the second:
'/var/tmp/faucet-tests-zqzd2hfo/FaucetSanityTest-test_untagged/gauge-state.txt'
'/var/tmp/faucet-tests-zqzd2hfo/FaucetSanityTest-test_untagged/gauge-ports.txt' : Gauge missing logs: {'/var/tmp/faucet-tests-zqzd2hfo/FaucetSanityTest-test_untagged/gauge-ports.txt', '/var/tmp/faucet-tests-zqzd2hfo/FaucetSanityTest-test_untagged/gauge-state.txt'}

----------------------------------------------------------------------
Ran 4 tests in 246.780s

FAILED (failures=1)

**Comment by gizmoguy** [comment]
Hi @ejietia, could we get a tarball of the test output please and I'll take a look for you.

**Comment by ejietia** [comment]
[faucet-tests-zqzd2hfo.tar.gz](https://github.com/faucetsdn/faucet/files/4232920/faucet-tests-zqzd2hfo.tar.gz)

**Comment by gizmoguy** [comment]
Hi @ejietia, looks like the same problem as last time, you are running an old version of faucet:

faucet_pbr_version{version="1.9.28.dev4"} 1.0

Upgrade to faucet 1.9.33 in your test environment and this test should pass.

**Comment by ejietia** [comment]
Yes, my fault. Really sorry. Create 1.9.33 without "git checkout 1.9.33" and after correcting I did "git checkout 1.8.33". Retest it, pass. Case can be closed. But Paul meet other issue on 1.9.33, will contact you soon when I narrow down the issue. Thanks again.
