### ISSUE TITLE
Same VLAN IDs on multiple DPs

### ISSUE THREAD

**Issue by PandyDev** [faucetsdn/faucet#3503]
Hello,

is there a way to define the same vlan id twice (or more) to have it available on other DPs?

Example:
Network 1 has VLAN 100 and network 2 has VLAN 100.
Both have a seperated layer2 env and both network have a different network for that vlan.
Network 1 vlan 100: 192.168.0.1/24
Network 2 vlan 100: 192.168.1.1/24

Error:
[InvalidConfigError('DP sw1: VLAN VID 100 multiply configured',)]

Is there a simple solution?

**Comment by gizmoguy** [comment]
Hi @PandyDev the recommended solution to this would be to run multiple faucet controllers (one per L2 domain). You would basically provide each faucet controller the same configuration file (except change which subnet is in use) and then run two of them on the same server listening on different OpenFlow TCP ports.

Faucet doesn't understand disconnected L2 segments at the moment and it's not something that is on our radar for implementing any time soon.
