### ISSUE TITLE
BGP error - DP server_addresses value must be list, not frozenset

### ISSUE THREAD

**Issue by PetersonPereira** [faucetsdn/faucet#3516]
I have two questions about BGP Faucet configuration, this is my faucet,yaml:

include:
    - acls.yaml

vlans:
    office:
        vid: 100
        description: "office network"
        faucet_mac: "0e:00:00:00:10:01"
        faucet_vips: ['192.168.0.254/24']
    guest:
        vid: 200
        description: "guest network"
        faucet_mac: "0e:00:00:00:20:01"
        faucet_vips: ['20.0.0.254/8']
routers:
    router-office-guest:
        vlans: [office, guest]
        bgp:
            vlan: office
            connect_mode: "passive"
            as: 65000
            port: 9179
            routerid: '192.168.0.252'
            server_addresses: ["127.0.0.1"]
            neighbor_addresses: ["127.0.0.1"]
            neighbor_as: 65000
dps:

      sw3:
             dp_id: 0x3
             hardware: "Open vSwitch"
             interfaces:
                 1:
                     name: "OVS1-CONN"
                     description: "ovs1 connection"
                     native_vlan: guest
      swdev:
             dp_id: 0xf
             hardware: "Open vSwitch"
             interfaces:
                 1:
                     name: "client 1"
                     native_vlan: "office"
                 2:
                     name: "client 2"
                     native_vlan: "guest"
                 3:
                     name: "client 3"
                     native_vlan: guest
                 99:
                     name: "Faucet "
                     native_vlan: office

In this configuration, faucet show this error message:

root@faucet:~# check_faucet_config /etc/faucet/faucet.yaml
including file: /etc/faucet/acls.yaml
[InvalidConfigError("DP swdev: server_addresses value frozenset({IPv4Address('127.0.0.1')}) must be <class 'list'> not <class 'frozenset'>")]

If I remove one dataplane (anyone), faucet work and no show error message.

Is Facet limited to one Dataplane vswitch when use BGP?

Other question is:

After remove one dataplane, my faucet connect by BGP to Bird, but no send vlan guest and addicionally send vlan office with:

root@faucet:~# birdc show route protocol faucet
BIRD 1.6.6 ready.
192.168.0.0/24     unreachable [faucet 01:18:14 from 127.0.0.1] * (100/-) [i]
root@faucet:~# 

Is possible Faucet export Vlan guest and vlan office to Bird?

I Search in user guide and development guide, but no found a example or how to more detailed.

Thanks so much for any information or documentation.

**Comment by gizmoguy** [comment]
Splitting this issue into two sub-issues:

#3517 
#3518
