### ISSUE TITLE
test_set_fields_generic_ udp fails with NoviFlow Switch

### ISSUE THREAD

**Issue by ejietia** [faucetsdn/faucet#3549]
Faucet:1.9.37
NoviWare:NW500.2.10

======================================================================
FAIL: test_set_fields_generic_udp (mininet_tests.FaucetOrderedSetFieldsTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/faucet-src/tests/integration/mininet_tests.py", line 7843, in test_set_fields_generic_
udp
    tcpdump_txt))
AssertionError: None is not true

======================================================================

There're 13 test cases failed when running towards NoviSwitch, but succeeded on OpenVswitch. This is just one example. I will attached all the logs for both running scenarios.

I have checked faucet-xxx-of.cap for both scenarios, but I found except flow_mod port_desc, there're table_feature messages running in NoviSwitch, but not in running on OpenVswitch.

So could you please some hints what should check when troubleshooting this kind of failure?
[OpenvSwitch.tar.gz](https://github.com/faucetsdn/faucet/files/4577478/OpenvSwitch.tar.gz)
[NoviSwitch.tar.gz](https://github.com/faucetsdn/faucet/files/4577482/NoviSwitch.tar.gz)

**Comment by ejietia** [comment]
[NoviFlow.txt](https://github.com/faucetsdn/faucet/files/4577512/NoviFlow.txt)
[OpenvSwitch.txt](https://github.com/faucetsdn/faucet/files/4577515/OpenvSwitch.txt)

Those 2 txt are printouts after running docker run commands.

**Comment by gizmoguy** [comment]
Reached out via an email thread to help debug this test failure.
