### ISSUE TITLE
Gauge automatic config reload functionality broken

### ISSUE THREAD

**Issue by cglewis** [faucetsdn/faucet#3564]
The port statistics dashboard (https://docs.faucet.nz/en/latest/_static/grafana-dashboards/faucet_port_statistics.json) doesn't add new DPs that are added to a Faucet config except when Gauge are restarted. Since I reload the config without restarting Faucet or Gauge the dashboard never populates if there's a new DP.

On the other hand, the inventory dashboard seems to update correctly.

**Comment by gizmoguy** [comment]
Correct, gauge needs to know every time faucet.yaml changes so it can poll the new switches for statistics.

We tried to fix this issue in https://github.com/faucetsdn/faucet/pull/3228, any chance you could take a look at work out why this fix didn't work for you?

**Comment by cglewis** [comment]
Yup, I'll take a poke at it.

**Comment by cglewis** [comment]
So looking at the logs, I see that once the DP connects (not defined) then Gauge will throw continuously:
```
May 21 01:03:23 gauge  ERROR    <ryu.controller.dpset.EventDP object at 0xffff99660890>: unknown datapath DPID 21 (0x15)
```

After a proper restart it's happy again:
```
May 21 01:04:04 gauge  INFO     version 1.9.42
May 21 01:04:04 gauge  INFO     Reloading configuration
May 21 01:04:06 gauge  INFO     watching FAUCET config /etc/faucet/faucet.yaml
May 21 01:04:06 gauge  INFO     config complete
May 21 01:04:13 gauge  INFO     DPID 21 (0x15) up
```

I started poking at adding `self._load_config()` here: https://github.com/faucetsdn/faucet/blob/master/faucet/gauge.py#L66 but that didn't seem to have any effect unfortunately.

**Comment by cglewis** [comment]
Also for reference in case I've got something weird here I missed:
```
$ cat /etc/faucet/gauge.yaml 
faucet_configs:
    - '/etc/faucet/faucet.yaml'
watchers:
    port_status_poller:
        type: 'port_state'
        all_dps: True
        db: 'prometheus'
    port_stats_poller:
        type: 'port_stats'
        all_dps: True
        interval: 10
        db: 'prometheus'
    flow_table_poller:
        type: 'flow_table'
        all_dps: True
        interval: 60
        db: 'prometheus'
dbs:
    prometheus:
        type: 'prometheus'
        prometheus_addr: '0.0.0.0'
        prometheus_port: 9303
    ft_file:
        type: 'text'
        compress: True
        file: 'flow_table.yaml.gz'
```

**Comment by cglewis** [comment]
This is totally my bad... I didn't have `GAUGE_CONFIG_STAT_RELOAD: '1'` set. Sorry about that, and thanks @anarkiwi for helping me track that down!
