### ISSUE TITLE
Northbound API for Faucet?

### ISSUE THREAD

**Issue by snak1219** [faucetsdn/faucet#3595]
Is there anyway we could extract the ARP information from faucet for an external service (via coprocessor) as of right now?  Could we ask faucet from an external service to resolve some ip address for instance? 

Any guidance/pointers would be useful thank you.

**Comment by anarkiwi** [comment]
FAUCET does log events via the event API (see https://github.com/faucetsdn/faucet/blob/master/tests/integration/mininet_tests.py#L14 for an example).

This includes L2 and L3 learns. Of course you will get only L2 if routing is not running in FAUCET.

**Comment by anarkiwi** [comment]
Please reopen if there are any other additions to this question?
