### ISSUE TITLE
Config file edit (wildcard size)

### ISSUE THREAD

**Issue by YarneThatsMe** [faucetsdn/faucet#3612]
I'm trying to find the faucet SDN controller config file to change the wildcard size of the controller.

Faucet is somewhat like the Ryu SDN controller and I can't find any details on how to change the config of the faucet controller, nor the Ryu controller.

I am researching a (D)DoS using mininet and the faucet controller. I came across a hping3 script which sends every second like 17.000 packets. Now when I look with Wireshark at the connection between mininet and faucet it spikes for one moment to ±170 request per second and than stables out to around 9 per second.

So it seems like the faucet controller sends out a wildcard with information like: "everything other than 192.168.x.x needs to be discarded" (since I'm only using local ip addresses).

Therefore I can't really do a (D)DoS attack.

Do you guys maybe know how I can change the settings of the faucet controller so it doesn't send out wildcard or how to change the time a flow is alive?

This could help me further with my research! Any help would be appreciated!

**Comment by anarkiwi** [comment]
Hi YarneThatsMe,

Would you send a message to the faucet-users email list? https://lists.geant.org/sympa/info/faucet-users. I wasn't able to understand your question about wildcarding; perhaps when you post your question you could share some more details about the test you're running to help us understand better.

Thanks,
