### ISSUE TITLE
Is lacp_passthrough a boolean or list?

### ISSUE THREAD

**Issue by shivarammysore** [faucetsdn/faucet#3622]
In https://github.com/faucetsdn/faucet/blob/master/faucet/port.py#L112, we have
```
'lacp_passthrough': None,
```
In https://github.com/faucetsdn/faucet/blob/master/faucet/port.py#L174, we have
```
'lacp_passthrough': list,
```
Per https://github.com/faucetsdn/faucet/blob/master/faucet/valve_switch_standalone.py#L787, it is implied that this is Boolean
```
if port.lacp_passthrough:
```
Am I mistaken?

**Comment by gizmoguy** [comment]
It is a list, if you look at the next line you will see we iterate through the list:

`for peer_num in port.lacp_passthrough:`

The reason behind the if statement, is that in python we can use this test to see if the list is empty or None:

```
>>> if []:
...     print("not an empty list or None")
... 
>>> if ["test"]:
...     print("not an empty list or None")
... 
not an empty list or None
```

**Comment by shivarammysore** [comment]
Thanks @gizmoguy
