### ISSUE TITLE
Question regarding Switch Support - with hardware: "Generic" type

### ISSUE THREAD

**Issue by AndrewLosty** [faucetsdn/faucet#3629]
The Faucet documentation clearly details the supported hardware switch vendors. 

I have Aruba 2930F switches but also want to work with switch manufacturers that are not documented.
In particular I am looking to work with Extreme X440G2 and Juniper EX4600 switches.

I can clearly see I an use the hardware: "Generic" type and can add a Extreme switch using this this however I wanted to ask the level of support I should expect to have using the "Generic" hardware type.

Any pointers in support for other platforms would be really appreciated

**Comment by anarkiwi** [comment]
Hi Andrew,

FAUCET essentially requires an OF1.3 compliant switch with multiple tables. There are some vendor dependent quirks - for example, some switches choose to leverage the TFM (Table Features Message) feature to configure resources, while some others don't. The "generic" type implements no quirks (and no use of TFM - if you would like that, use "GenericTFM").

IME neither Extreme nor Juniper have the critical multiple table support necessary for FAUCET to work.  However, you might want to run FAUCET's built in hardware integration tests (https://docs.faucet.nz/en/latest/testing.html#hardware-switch-testing-with-docker). This will tell you automatically what won't work.

If you have any other questions please re-open or feel free to post to faucet-users.

Thanks,
