### ISSUE TITLE
Fault-tolerance incorrect flooding

### ISSUE THREAD

**Issue by mab68** [faucetsdn/faucet#3683]
The fault-tolerance tests have detected failures to correctly pings between hosts on nodes in the following graphs.

Red edges are the edges that have been torn down due to the fault-tolerance tests.
The green node is the root node.

![G162](https://user-images.githubusercontent.com/33644913/91770114-b6f22b00-ec34-11ea-8106-829297c69664.png)
![G206](https://user-images.githubusercontent.com/33644913/91770121-b8235800-ec34-11ea-8f8e-404dc5393978.png)
![G208](https://user-images.githubusercontent.com/33644913/91770124-b8bbee80-ec34-11ea-9bd5-927415d20ba3.png)

**Comment by anarkiwi** [comment]
It looks like what they all have in common is every node is expected to have a direct connection to the root, so they no-reflection topology handler will be selected, which doesn't know how to deal with a node not directly connected. Maybe one solution is to change handlers to root reflection if this failed topology is detected?

**Comment by mab68** [comment]
Ran these tests after reverting my stack refactoring and they all pass. So seems like I broke something during the refactor.
