### ISSUE TITLE
Ryu does not support BGP per vlan

### ISSUE THREAD

**Issue by trungdtbk** [faucetsdn/faucet#383]
Currently, each VLAN has its own BGP configs and thus, its own BGP speaker.
But Ryu seems not to support two speakers in the same PC.
I run a test and got this message:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ryu/services/protocols/bgp/api/base.py", line 204, in call
    return call(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ryu/services/protocols/bgp/api/core.py", line 37, in start
    raise RuntimeConfigError('Current context has to be stopped to start '
RuntimeConfigError: 200.1 - Current context has to be stopped to start a new context.

ryu.services.protocols.bgp.rtconf.base.RuntimeConfigError: 200.1 - Current context has to be stopped to start a new context.

I think Faucet should have a single BGP config that works for all VLANs, making a VLAN an IP interface.

**Comment by anarkiwi** [comment]
Done: https://github.com/faucetsdn/faucet/commit/fba28c6b65ceb226a4afbc6ebdd028226145ff9c
