### ISSUE TITLE
No ICMP echo replies from VIP addresses

### ISSUE THREAD

**Issue by bozakov** [faucetsdn/faucet#3858]
I am trying to ping the IPv6 (and v4) VIP addresses, but not seeing any reply generated by the controller.
Looking at the OpenFlow channel with tshark it seems the Echo Requests are forwarded to the controller (`OFPT_PACKET_IN`), but no reply is generated. 

Is there anything that must be configured to enable this?

**Comment by bozakov** [comment]
My configuration had the MAC address in upper case. Changing it to lower case seems to have fixed the issue.

Maybe worth handling the case here: https://github.com/faucetsdn/faucet/blob/63ad6a35fa20efee06bc8afc45f807310f142d97/faucet/valve_route.py#L162 ?

**Comment by anarkiwi** [comment]
Thanks for your report, a fix will be submitted.
