### ISSUE TITLE
FaucetUntaggedIPv4ControlPlaneFuzzTest.test_fuzz_controller failed

### ISSUE THREAD

**Issue by ejietia** [faucetsdn/faucet#3869]
faucet@test-srv-05:~$ sudo docker run --privileged --rm --net=host --cap-add=NET_ADMIN -v /var/local/lib/docker:/var/lib/docker -v /tmp/faucet-pip-cache:/var/tmp/pip-cache -v /etc/faucet:/etc/faucet -v /var/tmp:/var/tmp -ti -e FAUCET_TESTS="-unk FaucetUntaggedIPv4ControlPlaneFuzzTest -o 0,1,2,3" faucet/1.9.54 2>&1 | tee FaucetUntaggedIPv4ControlPlaneFuzzTest
[sudo] password for faucet:
Using pip cache
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache wheel has exit status 0
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache -r /faucet-src/test-requirements.txt has exit status 0
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache -r /faucet-src/fuzz-requirements.txt has exit status 0
pip3 install -q --upgrade --cache-dir=/var/tmp/pip-cache -r /faucet-src/adapters/vendors/rabbitmq/requirements.txt has exit status 0
========== checking IPv4/v6 localhost is up =====
PING ::1(::1) 56 data bytes
64 bytes from ::1: icmp_seq=1 ttl=64 time=0.031 ms

--- ::1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.031/0.031/0.031/0.000 ms
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.036 ms

--- 127.0.0.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.036/0.036/0.036/0.000 ms
========== Starting OVS =========================
[warn] /usr/local/etc/openvswitch/conf.db does not exist ... (warning).
[ ok ] Creating empty database /usr/local/etc/openvswitch/conf.db.
[ ok ] Starting ovsdb-server.
[FAIL] system ID not configured, please use --system-id ... failed!
[ ok ] Configuring Open vSwitch system IDs.
[ ok ] Starting ovs-vswitchd.
[ ok ] Enabling remote OVSDB managers.
2fdba6e2-88c1-447f-a7da-9c9da4201c5a
    ovs_version: "2.15.0"
net.ipv4.neigh.default.gc_interval = 300
net.ipv4.neigh.default.gc_thresh1 = 8192
net.ipv4.neigh.default.gc_thresh2 = 16384
net.ipv4.neigh.default.gc_thresh3 = 32768
net.ipv6.neigh.default.gc_interval = 300
net.ipv6.neigh.default.gc_thresh1 = 8192
net.ipv6.neigh.default.gc_thresh2 = 16384
net.ipv6.neigh.default.gc_thresh3 = 32768
========== Starting docker container ==========
[ ok ] Starting Docker: docker.
========== Running faucet system tests ==========
========== Running faucet integration tests ==========
testing module ['mininet_tests', 'mininet_multidp_tests']
Cleaning up test interfaces, processes and openvswitch configuration from previous test runs
testing module ['mininet_tests', 'mininet_multidp_tests']
Skipping dependency checks
port order: -o 0,1,2,3
start port: --port 4
Using config from /etc/faucet/hw_switch_config.yaml
Testing hardware, forcing test serialization
Logging test results in /var/tmp/faucet-tests-nvuktdso
test ports server started
adding test FaucetUntaggedIPv4ControlPlaneFuzzTest

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
running 0 tests in parallel and 4 tests serial
test_flap_ping_controller (mininet_tests.FaucetUntaggedIPv4ControlPlaneFuzzTest) ... ok
test_fuzz_controller (mininet_tests.FaucetUntaggedIPv4ControlPlaneFuzzTest) ... FAIL
test_ping_fragment_controller (mininet_tests.FaucetUntaggedIPv4ControlPlaneFuzzTest) ... ok
test_untagged (mininet_tests.FaucetUntaggedIPv4ControlPlaneFuzzTest)
All hosts on the same untagged VLAN should have connectivity. ... ok

======================================================================
FAIL: test_fuzz_controller (mininet_tests.FaucetUntaggedIPv4ControlPlaneFuzzTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/faucet-src/tests/integration/mininet_tests.py", line 4396, in test_fuzz_controller
    fuzz_cmd, fuzz_out))
AssertionError: None is not true : python3 -c "from scapy.all import * ; scapy.all.send(fuzz(ARP(pdst='10.0.0.254')), count=1000)": Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/venv/lib/python3.7/site-packages/scapy/sendrecv.py", line 429, in send
    **kargs
  File "/venv/lib/python3.7/site-packages/scapy/sendrecv.py", line 397, in _send
    realtime=realtime, return_packets=return_packets)
  File "/venv/lib/python3.7/site-packages/scapy/sendrecv.py", line 360, in __gen_send
    s.send(p)
  File "/venv/lib/python3.7/site-packages/scapy/arch/linux.py", line 605, in send
    self.outs.bind(sdto)
TypeError: argument 1 must be str, not NetworkInterface

----------------------------------------------------------------------
Ran 4 tests in 312.775s

FAILED (failures=1)

test results
============
---
mininet_tests.FaucetUntaggedIPv4ControlPlaneFuzzTest.test_fuzz_controller:
  output: "Traceback (most recent call last):\t  File '/faucet-src/tests/integration/mininet_tests.py',\
    \ line 4396, in test_fuzz_controller\t    fuzz_cmd, fuzz_out))\tAssertionError:\
    \ None is not true : python3 -c 'from scapy.all import * ; scapy.all.send(fuzz(ARP(pdst='10.0.0.254')),\
    \ count=1000)': Traceback (most recent call last):\r\t  File '<string>', line\
    \ 1, in <module>\r\t  File '/venv/lib/python3.7/site-packages/scapy/sendrecv.py',\
    \ line 429, in send\r\t    **kargs\r\t  File '/venv/lib/python3.7/site-packages/scapy/sendrecv.py',\
    \ line 397, in _send\r\t    realtime=realtime, return_packets=return_packets)\r\
    \t  File '/venv/lib/python3.7/site-packages/scapy/sendrecv.py', line 360, in __gen_send\r\
    \t    s.send(p)\r\t  File '/venv/lib/python3.7/site-packages/scapy/arch/linux.py',\
    \ line 605, in send\r\t    self.outs.bind(sdto)\r\tTypeError: argument 1 must\
    \ be str, not NetworkInterface\r\t\t"
  status: FAIL
  test_duration_secs: 51
...

table: 0
  matches: ['OFPXMT_OFB_IN_PORT', 'OFPXMT_OFB_VLAN_VID'] (max 2)
  table_instructions: ['OFPIT_APPLY_ACTIONS', 'OFPIT_GOTO_TABLE'] (max 2)
  table_actions: ['OFPAT_PUSH_VLAN', 'OFPAT_SET_FIELD'] (max 2)
table: 1
  matches: ['OFPXMT_OFB_ETH_DST', 'OFPXMT_OFB_ETH_SRC', 'OFPXMT_OFB_ETH_TYPE', 'OFPXMT_OFB_IN_PORT', 'OFPXMT_OFB_VLAN_VID'] (max 3)
  table_instructions: ['OFPIT_APPLY_ACTIONS', 'OFPIT_GOTO_TABLE'] (max 2)
  table_actions: ['OFPAT_OUTPUT'] (max 1)
table: 2
  matches: ['OFPXMT_OFB_ETH_TYPE', 'OFPXMT_OFB_IPV4_DST', 'OFPXMT_OFB_IPV4_DST/Mask', 'OFPXMT_OFB_VLAN_VID'] (max 3)
  table_instructions: ['OFPIT_APPLY_ACTIONS', 'OFPIT_GOTO_TABLE'] (max 2)
  table_actions: ['OFPAT_DEC_NW_TTL', 'OFPAT_SET_FIELD'] (max 3)
table: 3
  matches: ['OFPXMT_OFB_ARP_TPA', 'OFPXMT_OFB_ETH_DST', 'OFPXMT_OFB_ETH_TYPE', 'OFPXMT_OFB_IP_PROTO'] (max 3)
  table_instructions: ['OFPIT_APPLY_ACTIONS', 'OFPIT_GOTO_TABLE'] (max 2)
  table_actions: ['OFPAT_OUTPUT'] (max 1)
table: 4
  matches: ['OFPXMT_OFB_ETH_DST', 'OFPXMT_OFB_VLAN_VID'] (max 2)
  table_instructions: ['OFPIT_APPLY_ACTIONS', 'OFPIT_GOTO_TABLE'] (max 1)
  table_actions: ['OFPAT_OUTPUT', 'OFPAT_POP_VLAN'] (max 2)
table: 5
  matches: ['OFPXMT_OFB_ETH_DST', 'OFPXMT_OFB_ETH_DST/Mask', 'OFPXMT_OFB_IN_PORT', 'OFPXMT_OFB_VLAN_VID'] (max 3)
  table_instructions: ['OFPIT_APPLY_ACTIONS'] (max 1)
  table_actions: ['OFPAT_OUTPUT', 'OFPAT_POP_VLAN'] (max 5)

log/debug files for failed tests are in /var/tmp/faucet-tests-nvuktdso

real	5m17.122s
user	1m11.897s
sys	0m50.076s
testing module ['clib_mininet_tests']
Skipping dependency checks
port order: -o 0,1,2,3
start port: --port 1
Using config from /etc/faucet/hw_switch_config.yaml
Testing hardware, forcing test serialization
Logging test results in /var/tmp/faucet-tests-7p9ypclb
test ports server started
no tests selected

real	0m1.758s
user	0m0.693s
sys	0m0.064s
Test failures:  mininet_main[
[FaucetUntaggedIPv4ControlPlaneFuzzTest-test_fuzz_controller.tar.zip](https://github.com/faucetsdn/faucet/files/6813521/FaucetUntaggedIPv4ControlPlaneFuzzTest-test_fuzz_controller.tar.zip)
](url)

**Comment by ejietia** [comment]
NS2128-206# show stats table tableid all
	+--------------+
	| Table id: 0  |
	+--------------+
	Active count	: 5
	Max entries	: 2048
	Lookup count	: 59
	Match count	: 59

	+--------------+
	| Table id: 1  |
	+--------------+
	Active count	: 12
	Max entries	: 2048
	Lookup count	: 59
	Match count	: 59

	+--------------+
	| Table id: 2  |
	+--------------+
	Active count	: 3
	Max entries	: 4096
	Lookup count	: 0
	Match count	: 0

	+--------------+
	| Table id: 3  |
	+--------------+
	Active count	: 8
	Max entries	: 2048
	Lookup count	: 29
	Match count	: 29

	+--------------+
	| Table id: 4  |
	+--------------+
	Active count	: 6
	Max entries	: 256
	Lookup count	: 55
	Match count	: 55

	+--------------+
	| Table id: 5  |
	+--------------+
	Active count	: 9
	Max entries	: 4096
	Lookup count	: 23
	Match count	: 23

**Comment by mwutzke** [comment]
I also see failures on the `FaucetUntaggedIPv6ControlPlaneFuzzTest.test_fuzz_controller` test as well, which I believe is the same error:
```
 TypeError: argument 1 must be str, not NetworkInterface
 ```

**Comment by mwutzke** [comment]
Executing in a `faucet/test-base:9.0.1`, the following shows the issue:
```
>>> from scapy.all import *
>>> scapy.all.send(fuzz(ARP(pdst='172.17.0.1')))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv/lib/python3.7/site-packages/scapy/sendrecv.py", line 429, in send
    **kargs
  File "/venv/lib/python3.7/site-packages/scapy/sendrecv.py", line 397, in _send
    realtime=realtime, return_packets=return_packets)
  File "/venv/lib/python3.7/site-packages/scapy/sendrecv.py", line 360, in __gen_send
    s.send(p)
  File "/venv/lib/python3.7/site-packages/scapy/arch/linux.py", line 605, in send
    self.outs.bind(sdto)
TypeError: argument 1 must be str, not NetworkInterface
```

There are comments elsewhere that indicate downgrading Scapy can resolve the problem.

**Comment by mwutzke** [comment]
As a quick test, I attempted the following:
```
root@9fc6286b942b:/faucet-src# pip install scapy==2.4.4
Collecting scapy==2.4.4
...
Successfully built scapy
Installing collected packages: scapy
  Found existing installation: scapy 2.4.5
    Uninstalling scapy-2.4.5:
      Successfully uninstalled scapy-2.4.5
root@9fc6286b942b:/faucet-src#
```

After which this now passes
```
docker/runtests.sh --integration \
  FaucetUntaggedIPv6ControlPlaneFuzzTest FaucetUntaggedIPv4ControlPlaneFuzzTest
```

**Comment by anarkiwi** [comment]
This should be fixed - please reopen if still a problem.
