### ISSUE TITLE
Documentation of native_vlan field states integer but appears differently in example yaml

### ISSUE THREAD

**Issue by dwalter0** [faucetsdn/faucet#3921]
Documentation here
https://docs.faucet.nz/en/latest/configuration.html

![native_vlan](https://user-images.githubusercontent.com/1719888/128173818-8b591a0f-6567-4494-b7df-ee251bd72d71.png)
![native_vlan_2](https://user-images.githubusercontent.com/1719888/128173822-685f8539-264e-4986-9e00-8d734afda33c.png)

native_vlan in the interfaces configuration item is noted as being an integer but does not appear as an integer in the example.

**Comment by anarkiwi** [comment]
Fixed by https://github.com/faucetsdn/faucet/issues/3921
