### ISSUE TITLE
"cgcreate: libcgroup initialization failed: Cgroup is not mounted" error when trying to run Faucet tests

### ISSUE THREAD

**Issue by rakshijain123n** [faucetsdn/faucet#3957]
Hello,

When I am trying to run the Faucet integration tests, I am running into this error. Please help.
Complete test run logs as follows.

========== Skipping unit tests ==========
========== Skipping code checks ==========
========== checking IPv4/v6 localhost is up =====
PING ::1(::1) 56 data bytes
64 bytes from ::1: icmp_seq=1 ttl=64 time=0.036 ms

--- ::1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.036/0.036/0.036/0.000 ms
PING 127.0.0.1 (127.0.0.1) 56(84) bytes of data.
64 bytes from 127.0.0.1: icmp_seq=1 ttl=64 time=0.032 ms

--- 127.0.0.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.032/0.032/0.032/0.000 ms
========== Starting OVS =========================
/usr/local/etc/openvswitch/conf.db does not exist ... (warning).
Creating empty database /usr/local/etc/openvswitch/conf.db.
Starting ovsdb-server.
system ID not configured, please use --system-id ... failed!
Configuring Open vSwitch system IDs.
Starting ovs-vswitchd.
Enabling remote OVSDB managers.
538ec6a3-c24b-4e7d-87bd-75324ab0ca34
    ovs_version: "2.15.1"
sysctl: cannot stat /proc/sys/net/ipv4/neigh/default/gc_interval: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/neigh/default/gc_thresh1: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/neigh/default/gc_thresh2: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv4/neigh/default/gc_thresh3: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv6/neigh/default/gc_interval: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv6/neigh/default/gc_thresh1: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv6/neigh/default/gc_thresh2: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv6/neigh/default/gc_thresh3: No such file or directory
========== Starting docker container ==========
mount: /sys/fs/cgroup/cpuset: permission denied.
mount: /sys/fs/cgroup/cpu: permission denied.
mount: /sys/fs/cgroup/cpuacct: permission denied.
mount: /sys/fs/cgroup/blkio: permission denied.
mount: /sys/fs/cgroup/memory: permission denied.
mount: /sys/fs/cgroup/devices: permission denied.
mount: /sys/fs/cgroup/freezer: permission denied.
mount: /sys/fs/cgroup/net_cls: permission denied.
mount: /sys/fs/cgroup/perf_event: permission denied.
mount: /sys/fs/cgroup/net_prio: permission denied.
mount: /sys/fs/cgroup/hugetlb: permission denied.
mount: /sys/fs/cgroup/pids: permission denied.
mount: /sys/fs/cgroup/rdma: permission denied.
Starting Docker: docker.
========== Running faucet system tests ==========
========== Running faucet integration tests ==========
testing module ['mininet_tests', 'mininet_multidp_tests']
Cleaning up test interfaces, processes and openvswitch configuration from previous test runs
test_listening (mininet_tests.FaucetSanityTest) ... *** Error setting resource limits. Mininet's performance may be affected.
testing module ['mininet_tests', 'mininet_multidp_tests']
Checking library/binary dependencies
port order: -o 3,2,0,1
start port: --port 4
Using config from /etc/faucet/hw_switch_config.yaml
Testing hardware, forcing test serialization
Logging test results in /var/tmp/faucet-tests-ctfge_oy
test ports server started
adding test FaucetSanityTest

test results
============
---
mininet_tests.FaucetSanityTest.test_listening:
  output: "Traceback (most recent call last):\t  File '/faucet-src/tests/integration/mininet_tests.py',\
    \ line 138, in setUp\t    self.start_net()\t  File '/faucet-src/clib/mininet_test_base.py',\
    \ line 622, in start_net\t    self._start_faucet(controller_intf, controller_ipv6)\t\
    \  File '/faucet-src/clib/mininet_test_base.py', line 737, in _start_faucet\t\
    \    controller=self.faucet_controllers[0])\t  File '/venv/lib/python3.7/site-packages/mininet/net.py',\
    \ line 178, in __init__\t    self.build()\t  File '/venv/lib/python3.7/site-packages/mininet/net.py',\
    \ line 508, in build\t    self.buildFromTopo( self.topo )\t  File '/venv/lib/python3.7/site-packages/mininet/net.py',\
    \ line 479, in buildFromTopo\t    self.addHost( hostName, **topo.nodeInfo( hostName\
    \ ) )\t  File '/venv/lib/python3.7/site-packages/mininet/net.py', line 232, in\
    \ addHost\t    h = cls( name, **defaults )\t  File '/faucet-src/clib/mininet_test_topo.py',\
    \ line 59, in __init__\t    super().__init__(*args, **kwargs)\t  File '/venv/lib/python3.7/site-packages/mininet/node.py',\
    \ line 695, in __init__\t    errFail( 'cgcreate -g ' + self.cgroup )\t  File '/venv/lib/python3.7/site-packages/mininet/util.py',\
    \ line 197, in errFail\t    % ( cmd, ret, err ) )\tException: errFail: ('cgcreate\
    \ -g cpu,cpuacct,cpuset:/u011',) failed with return code 81: cgcreate: libcgroup\
    \ initialization failed: Cgroup is not mounted\t\t"
  status: ERROR
  test_duration_secs: 0
...

log/debug files for failed tests are in /var/tmp/faucet-tests-ctfge_oy

ERROR

======================================================================
ERROR: test_listening (mininet_tests.FaucetSanityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/faucet-src/tests/integration/mininet_tests.py", line 138, in setUp
    self.start_net()
  File "/faucet-src/clib/mininet_test_base.py", line 622, in start_net
    self._start_faucet(controller_intf, controller_ipv6)
  File "/faucet-src/clib/mininet_test_base.py", line 737, in _start_faucet
    controller=self.faucet_controllers[0])
  File "/venv/lib/python3.7/site-packages/mininet/net.py", line 178, in __init__
    self.build()
  File "/venv/lib/python3.7/site-packages/mininet/net.py", line 508, in build
    self.buildFromTopo( self.topo )
  File "/venv/lib/python3.7/site-packages/mininet/net.py", line 479, in buildFromTopo
    self.addHost( hostName, **topo.nodeInfo( hostName ) )
  File "/venv/lib/python3.7/site-packages/mininet/net.py", line 232, in addHost
    h = cls( name, **defaults )
  File "/faucet-src/clib/mininet_test_topo.py", line 59, in __init__
    super().__init__(*args, **kwargs)
  File "/venv/lib/python3.7/site-packages/mininet/node.py", line 695, in __init__
    errFail( 'cgcreate -g ' + self.cgroup )
  File "/venv/lib/python3.7/site-packages/mininet/util.py", line 197, in errFail
    % ( cmd, ret, err ) )
Exception: errFail: ('cgcreate -g cpu,cpuacct,cpuset:/u011',) failed with return code 81: cgcreate: libcgroup initialization failed: Cgroup is not mounted

----------------------------------------------------------------------
Ran 1 test in 4.347s

FAILED (errors=1)

real	0m6.519s
user	0m2.552s
sys	0m0.919s
testing module ['clib_mininet_tests']
Checking library/binary dependencies
port order: -o 3,1,2,0
start port: --port 1
Using config from /etc/faucet/hw_switch_config.yaml
Testing hardware, forcing test serialization
Logging test results in /var/tmp/faucet-tests-4zuogtj9
test ports server started
no tests selected

real	0m1.732s
user	0m0.651s
sys	0m0.082s
Test failures:  mininet_main
+ rm /root/faucet-results/master:2021-10-11T18:23+00:00.json.pipe
+ exec
+ wait
+ jq --slurp 'reduce .[] as $r ({}; . * $r)'
+ '[' -s /root/faucet-results/master:2021-10-11T18:23+00:00.json ']'
+ ln -sf /root/faucet-results/master:2021-10-11T18:23+00:00.json /root/faucet-results/latest.json
+ set +o xtrace
results-json-sentinel-bdcbdb1b-ac78-4090-bf02-3f1c6cefe221
{
  "hw_config": {
    "hw_switch": true,
    "hardware": "CiscoC9K",
    "dp_ports": {
      "109": "test-if0",
      "148": "test-if1",
      "209": "test-if2",
      "501": "test-if3"
    },
    "dpid": 475589510543040,
    "cpn_intf": "test-cpn0",
    "of_port": 6633,
    "gauge_of_port": 6637
  },
  "tests": {
    "mininet_tests.FaucetSanityTest.test_listening": {
      "status": "ERROR",
      "output": "Traceback (most recent call last):\t  File '/faucet-src/tests/integration/mininet_tests.py', line 138, in setUp\t    self.start_net()\t  File '/faucet-src/clib/mininet_test_base.py', line 622, in start_net\t    self._start_faucet(controller_intf, controller_ipv6)\t  File '/faucet-src/clib/mininet_test_base.py', line 737, in _start_faucet\t    controller=self.faucet_controllers[0])\t  File '/venv/lib/python3.7/site-packages/mininet/net.py', line 178, in __init__\t    self.build()\t  File '/venv/lib/python3.7/site-packages/mininet/net.py', line 508, in build\t    self.buildFromTopo( self.topo )\t  File '/venv/lib/python3.7/site-packages/mininet/net.py', line 479, in buildFromTopo\t    self.addHost( hostName, **topo.nodeInfo( hostName ) )\t  File '/venv/lib/python3.7/site-packages/mininet/net.py', line 232, in addHost\t    h = cls( name, **defaults )\t  File '/faucet-src/clib/mininet_test_topo.py', line 59, in __init__\t    super().__init__(*args, **kwargs)\t  File '/venv/lib/python3.7/site-packages/mininet/node.py', line 695, in __init__\t    errFail( 'cgcreate -g ' + self.cgroup )\t  File '/venv/lib/python3.7/site-packages/mininet/util.py', line 197, in errFail\t    % ( cmd, ret, err ) )\tException: errFail: ('cgcreate -g cpu,cpuacct,cpuset:/u011',) failed with return code 81: cgcreate: libcgroup initialization failed: Cgroup is not mounted\t\t",
      "test_duration_secs": 0
    }
  }
}
results-json-sentinel-bdcbdb1b-ac78-4090-bf02-3f1c6cefe221
+ cleanupResultsPipe
+ rm /root/faucet-results/master:2021-10-11T18:23+00:00.json.pipe
rm: cannot remove '/root/faucet-results/master:2021-10-11T18:23+00:00.json.pipe': No such file or directory

Regards,
Rakshith

**Comment by gizmoguy** [comment]
Hi there,

What linux distribution/version are you running and what kernel version?

Also what docker command did you run to invoke the faucet test suite?

**Comment by rakshijain123n** [comment]
Any update on this?

**Comment by gizmoguy** [comment]
I've been having a discussion with the Mininet developer about the cgroup error you're having.

Mininet uses cgroup v1 at the moment and we think your system must have this disabled in favor of cgroup v2. We don't have access to a rodete image ourselves to test this theory but that is the best idea we've come up with so far.

If you could try run the test suite under a Debian bullseye or Ubuntu 20.04 VM we think it should work.

**Comment by rakshijain123n** [comment]
No longer required. Thanks for looking into this issue @gizmoguy.
