### ISSUE TITLE
Connecting Open vSwitch switch to Faucet controller through Unix Domain Socket

### ISSUE THREAD

**Issue by lamnt205210** [faucetsdn/faucet#4579]
When running the Faucet controller and Open vSwitch on the same host, connection between the controller and the switch through Unix Domain Socket should be provide better performance than through the OS TCP/IP Stack. 
Is there a way to do this with Faucet ?

**Comment by gizmoguy** [comment]
The openflow channel for faucet is managed by os-ken, I can't immediately see any os-ken options that would allow for listening on a unix domain socket instead of a tcp port.

**Comment by lamnt205210** [comment]
Okay i've got it closing this issue now

**Comment by lamnt205210** [comment]
Okay I got it closing this issue now
