### ISSUE TITLE
Layer 3 groups with OpenvSwitch don't seem to work

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#738]
I just attempted to enable "group_table: True" against an OpenvSwitch bridge which is doing routing and things don't seem to work quite right:

> brad@faucet:~$ sudo grep ERROR /var/log/ryu/faucet/faucet.log
> Jul 04 15:03:10 faucet ERROR    send_flow_msgs: DPID 70 (0x46) not up
> Jul 04 15:03:13 faucet ERROR    BGP nexthop 127.0.0.1 for prefix 163.7.136.0/23 is not a connected network
> Jul 04 15:03:28 faucet ERROR    send_flow_msgs: DPID 70 (0x46) not up
> Jul 04 15:03:30 faucet ERROR    BGP nexthop 127.0.0.1 for prefix 163.7.136.0/23 is not a connected network
> Jul 04 15:06:09 faucet ERROR    send_flow_msgs: DPID 70 (0x46) not up
> Jul 04 15:06:12 faucet ERROR    BGP nexthop 127.0.0.1 for prefix 163.7.136.0/23 is not a connected network
> Jul 04 15:06:24 faucet ERROR    send_flow_msgs: DPID 70 (0x46) not up
> Jul 04 15:06:27 faucet ERROR    BGP nexthop 127.0.0.1 for prefix 163.7.136.0/23 is not a connected network

**Comment by anarkiwi** [comment]
We should retry this (since there's been a lot of refactoring) and the debug here says the OF channel is not up - we'll need an OF channel dump to figure out what happened. We should re open to investigate further (or we will gradually move towards groups for everything, anyway).
