### ISSUE TITLE
Add makefile target for performing a new release

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#767]
13:02:51 <@gizmoguy> potentially "make release 1.5.4" should:

13:03:11 <@gizmoguy> a) git branch current commit as "1.5.4"
13:03:25 <@gizmoguy> b) replace version in README.rst & docker-compose.yaml
13:03:28 <@gizmoguy> c) commit to 1.5.4
13:03:37 <@gizmoguy> d) tag that branch as 1.5.4

13:04:02 <@gizmoguy> then if you get git master you will install the "master" version of faucet, otherwise you get a tagged proper version

**Comment by gizmoguy** [comment]
We've changed our release process, here is how it works now:

1. Bump version in README.rst and docker-compose.yaml to match setup.cfg
2. Commit and push to master
3. Tag this commit as $version
4. Bump version in setup.cfg
5. Commit and push to master

**Comment by cglewis** [comment]
with the merge of https://github.com/faucetsdn/faucet/pull/1148, `docker-compose-pi.yaml` file would need the version bump too.

**Comment by anarkiwi** [comment]
Noted for regular next release (Monday).
