### ISSUE TITLE
Gauge support for Avro

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#804]
https://docs.aws.amazon.com/athena/latest/ug/avro.html

**Comment by shivarammysore** [comment]
A more elementary functionality would be to support storing in S3.  Suggestion is to add another "file type" for storage and it would be on a datastore such as AWS S3.  Flows, stats, etc everything that is stored in InfluxDB must be sent to S3 Storage - JSON format is perfectly acceptable.  Please add "Controller ID" or "Controller Name" to the same for storage.  Please note that a S3 Bucket can accept data from multiple controllers (I am not sure if current InfluxDB model supports storing data from various controllers).

**Comment by anarkiwi** [comment]
Revisiting this - would it be acceptable to use a service like https://www.weave.works/docs/cloud/latest/concepts/prometheus-monitoring/?

I'd like to try to concentrate on supporting just one monitoring technology (Prometheus primarily) with flat-file storage as diagnostic/alternative. We are looking at a separate system for events (possibly RabbitMQ). If we have to support more we could, just concerned about dev resources (especially as storage technologies change it will be a challenge to keep the storage adaptors up to date - like our experience with CouchDB).

Note that's all separate for adding additional labels to existing Prometheus data (dp_name, etc, which is on the list - I've been able to make some progress on the backlog so it might be there by next release).

**Comment by shivarammysore** [comment]
Hi Josh,
Agree with you wholeheartedly that - "we support only one monitoring
technology - Prometheus"

Avro, etc are all fast changing services - I think any consumer can push
from or pull from Prometheus datasource as required - it will possibly be
also tied to other logic.  I like simplicity with Prometheus.

thanks

/Shivaram
