### ISSUE TITLE
Automatic config file reload based on setting - equivalent of manual SIGHUP

### ISSUE THREAD

**Issue by shivarammysore** [faucetsdn/faucet#809]
When faucet configuration (`faucet.yaml` or `gauge.yaml` or `dps.yaml` or `vlans.yaml` or `acls.yaml`) files change on the disk, if `config_reload_on_change` value was set (`=true`) in `faucet.yaml` or `gauge.yaml` then corresponding Faucet/Gauge needs to do a complete reload of all config files (equivalent to a **SIGHUP**) by noticing that file on the disk has changed.

This is necessary for automated environments and when deploying controller via Containers.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/pull/1223
