### ISSUE TITLE
Mirror ACLs causes Faucet not installing flows of all ports having ID equal to the mirror port.

### ISSUE THREAD

**Issue by trungdtbk** [faucetsdn/faucet#911]
As long as there exists a ACL with mirror action, Faucet does not install any flows for that port, even the ACL is not configured anywhere. 
mirror ACL should only be active for specific port or VLAN that has been configured with acl_in pointing to the ACL.

**Comment by trungdtbk** [comment]
I think it is because the resolve_names_in_acls method in dp does not check if an acl is in use or not.
As long as it sees 'mirror', it marks the port as mirror_destination. That causes every dp to drop traffic of the port.

**Comment by anarkiwi** [comment]
It is possible to refer to a port by name, not by number. The ACL therefore can specify a port by name as a mirror port. This will restrict the problem to just the port. There is still a bug that if the ACL is not active at all, that particular port should of course pass traffic normally.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/c4acd488b315153f12f3b94b36b742269026493b
