### ISSUE TITLE
Gauge/Faucet should expose dp_name as well as dp_id as prometheus labels

### ISSUE THREAD

**Issue by gizmoguy** [faucetsdn/faucet#912]
At the moment if we want to provide a friendly name for a DP instead of the hexidecimal ID we can do a join in prometheus like so:

> bgp_neighbor_routes * on (instance, job, dpid) group_left(name) faucet_config_dp_name

However, grafana doesn't have fantastic support of this approach when it comes to templates and prometheus seems to have issues joining range vectors that have had a rate() aggregation applied. We should consider providing both dp_name and dp_id as labels to our prometheus metrics.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/d62b54523011d0aa1c7db8ac4737f84d9bddcd8b
