### ISSUE TITLE
fctl tool

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#947]
It would be great to have a way to "command line" query FAUCET controllers and present state in a familiar way. For example, to show which MACs have been learned on what ports/VLANs. The tool fctl would just use Prometheus queries to FAUCET and Gauge and wouldn't modify the controller's state.

**Comment by vladimir-mencl-eresearch** [comment]
Hi,

Just thinking that if the tool does not *control* Faucet and only makes queries, perhaps the name should not be `fctl` but maybe something like `fquery` ... ?

Cheers,
Vlad

**Comment by shivarammysore** [comment]
I was thinking that we should restrict monitoring like tools for Faucet,
but enable them for Gauge.  Specifically, I am ok with fctl/fquery running
on either Faucet or Gauge - very useful for debugging purposes to exactly
understand what is seen by that particular controller.  I would be more
inclined to remove Prometheus integration for Faucet and focus only on
Gauge for monitoring.  Today, this functionality is simple and cool.  But,
maintaining it over a longer period of time is going to be hard.

Thanks

**Comment by anarkiwi** [comment]
Because FAUCET and Gauge are separate (a good thing for reliability, etc),
they need to both be monitored separately (for example, Prometheus can
monitor that both/all processes have good connections to dataplanes, which
is an essential and basic monitoring requirement). Therefore, I think
Prometheus has to be in FAUCET ongoing for at least these reasons. It does
not hurt anything, quite the reverse.

**Comment by anarkiwi** [comment]
That is so, today it doesn't modify state. One can imagine in the future
though it might include convenient helpers (for example, request a config
reload).

**Comment by vladimir-mencl-eresearch** [comment]
@anarkiwi - OK, if it's not completely restricted from modifying state, I'm happy for it to be called `fctl` :-)

**Comment by simeonmiteff** [comment]
I have an early prototype for folks to play with here: https://github.com/simeonmiteff/faucet/commit/6418f9627e6c243068b27cb44e13c30b674e2efc

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/commit/aab5649891cebed4cced5d87bd07fca6c286fffc

josh@windscale:~/tmp$ ./fctl.py  -h

Retrieve FAUCET/Gauge state using Prometheus.

    ./fctl.py [-n] <-e|--endpoints=http://prometheus:port> [-m|--metrics=prometheus_metrics,] [-l|--labels=name:value,]

    -n: Don't report 0 values
    -e|--endpoints: list of Prometheus endpoints to query (comma separated)
    -m|--metrics: list of Prometheus variables to query (comma separated)
    -l|--labels: filter list of Prometheus variables by labels that must be present (comma separated)

Examples:

    MACs learned on a DP.

    ./fctl.py -n --endpoints=http://172.17.0.1:9244 --metrics=learned_macs --labels=dp_id:0xb827eb608918

    Status of all DPs

    ./fctl.py -n --endpoints=http://172.17.0.1:9244 --metrics=dp_status


josh@windscale:~/tmp$ ./fctl.py -n --endpoints=http://172.17.0.1:9244 --metrics=dp_status 
dp_status	{u'dp_id': u'0xb827eb608918'}	1.0
dp_status	{u'dp_id': u'0xeccd6df72de7'}	1.0
josh@windscale:~/tmp$ ./fctl.py -n --endpoints=http://172.17.0.1:9244 --metrics=learned_macs --labels=dp_id:0xb827eb608918
learned_macs	{u'dp_id': u'0xb827eb608918', u'vlan': u'2004', u'port': u'2', u'n': u'0'}	9cf387b5f4c6
learned_macs	{u'dp_id': u'0xb827eb608918', u'vlan': u'2004', u'port': u'2', u'n': u'1'}	a45e60c55ced
learned_macs	{u'dp_id': u'0xb827eb608918', u'vlan': u'2004', u'port': u'2', u'n': u'2'}	da0204d4a435

**Comment by anarkiwi** [comment]
This has been implemented and improved with some further contributions.
