### ISSUE TITLE
Ability to apply multiple ACLs on a port

### ISSUE THREAD

**Issue by shivarammysore** [faucetsdn/faucet#972]
Lets say we have 2 ACLS - one for mirroring traffic and other for dropping IPv6 packets.  I need an ability to apply both (or a list) of those ACLs on a single port.  For example:

`acl_in: [ipv6_only_drop, mirror_traffic]`

Last ACL applied may override previously applied rules.  For example per above, only IPv4 traffic will be mirrored.

**Comment by anarkiwi** [comment]
Some refactoring has been done to support this internally, but it is not yet exposed to the user.

**Comment by anarkiwi** [comment]
@rsanger thanks for your contribution sir!
