### ISSUE TITLE
Adding more Gauge unit tests

### ISSUE THREAD

**Issue by libunamari** [faucetsdn/faucet#974]
The existing Gauge unit tests are system tests. We propose adding some unit tests that check individual methods. We're only testing public methods for the following classes:
- gauge.py
- gauge_influx.py
- gauge_nsodbc.py
- gauge_pollers.py
- gauge_prom.py
- nsodbc.py
- watchers.py

Are there other classes we should test?

**Comment by anarkiwi** [comment]
Unit tests for these would be amazing and would cover the bulk Gauge.

**Comment by anarkiwi** [comment]
https://github.com/faucetsdn/faucet/blob/master/tests/test_gauge.py et al.
