### ISSUE TITLE
pbr.VersionInfo() performance in prom_client.py

### ISSUE THREAD

**Issue by byllyfish** [faucetsdn/faucet#977]
Just a heads up on a performance issue, this is not really a bug...

In prom_client.py, the following line takes several hundred milliseconds on my computer (2011 MacBook Air). It's enough however to notice that Faucet is starting slower.

```
version = VersionInfo('faucet').semantic_version().release_string()
```

When Faucet is installed with setuptools, the above line averages 200 ms.

When Faucet is not installed, the above line averages 700 ms. On a cold start, obtaining the version can take over a second.  This appears to be the worst case.

Performance-wise, using a (possibly duplicate) __version__ variable would be a simple alternative, if pbr doesn't bring anything else to the table.

**Comment by anarkiwi** [comment]
That is an annoying startup delay (only paid once on startup, but still).

From a systems admin point of view we make use of this variable (helps the
automation determine fairly conclusively where the running FAUCET came
from). Will be good to see if we can get the cost of this one call down.

**Comment by anarkiwi** [comment]
https://bugs.launchpad.net/pbr/+bug/1688405

**Comment by anarkiwi** [comment]
Moved this to a TODO (https://github.com/faucetsdn/faucet/commit/32e46e83b50ae0540ff10e05b26865739cd53186)
