### ISSUE TITLE
Docker images are too large

### ISSUE THREAD

**Issue by anarkiwi** [faucetsdn/faucet#981]
Image Size
As is obvious from the container image sizes below faucet and gauge containers are huge. I’m not familiar with python runtime sizes but there is a python-slim base container that might help reduce these sizes. Also, switching to an alpine user land as NginX has done may help.
Container size doesn’t directly impact performance; however, it does add general resource overhead. Container images are the ‘new’ executable. Running an instance of faucet and gauge should not require a combined 1.5GB executable.
REPOSITORY                           TAG                 IMAGE ID            CREATED             SIZE
faucet/faucet                        latest              36ffc6aa1e66        2 days ago          787.8 MB
faucet/gauge                         latest              af38531f9343        11 days ago         779.7 MB
grafana/grafana                      latest              e4accc9ea909        5 days ago          302.8 MB
prom/prometheus                      latest              4da113bb6ae3        3 months ago        74.49 MB
google/cadvisor                      latest              f9ba08bafdea        6 months ago        57.32 MB
nginx                                alpine              21a2450d623e        6 days ago          15.51 MB
alpine                               latest              7328f6f8b418        12 weeks ago        3.962 MB

**Comment by anarkiwi** [comment]
I reduced the controllers to about 385M, and the test image from 2G to 1.1G (mostly by removing unneeded dependencies). Potentially this could be a lot better (eg. Alpine) but would require thorough testing.

reannz/faucet         latest              b90ceb3c05e9        4 seconds ago       385.4 MB
<none>                <none>              39fcdc5c91f5        21 seconds ago      385.4 MB
reannz/faucet-tests   latest              44b8b8421d10        18 minutes ago      1.16 GB

**Comment by byllyfish** [comment]
The /faucet-src directory on the faucet image includes the .git and docs directories. If you add a .dockerignore file for those two items, I think you can slim down the images another 40 MB.

Also, the Gauge image is basically the Faucet image with a different command. (You've still got the "FROM osrg/ryu" line right now though.) You could count on docker to share the layers, or make the Gauge docker image just be:

```
FROM faucet/faucet
CMD ["ryu-manager", "faucet.gauge"]
```

**Comment by byllyfish** [comment]
Ignore the comment about Gauge; my git pull wasn't up to date. I see the port numbers are slightly different also.

**Comment by anarkiwi** [comment]
I slimmed down the test image as much as possible, and after lots of testing switched the non-test images to Alpine Linux. This reduces container size to about 160M (from 359 under python:3-slim. Not bad, especially not needing a full libc. Good enough to leave here for quite a while.

root@windscale:/home/josh/bin# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
faucet/gauge        latest              2fedec1cdb02        5 minutes ago       162.2 MB
faucet/faucet       latest              f350d6160828        7 minutes ago       162.2 MB
faucet/gauge        <none>              1d3de8fba5d8        About an hour ago   359 MB
faucet/faucet       <none>              e5b213c221d9        About an hour ago   359 MB
