### ISSUE TITLE
Support for Logging with systemd 

### ISSUE THREAD

**Issue by shivarammysore** [faucetsdn/faucet#997]
`Systemd` is the de facto system management daemon in most Linux systems today.  Logging module in Faucet will need an update to use Systemd

**Comment by gizmoguy** [comment]
I think to make this work we just need to support logging messages to stdout and exceptions to stderr.

**Comment by anarkiwi** [comment]
I implemented this: https://github.com/faucetsdn/faucet/commit/1a74105abf8e8d397ae8f9d72640267bfc757818
